* AD734~ linking file

*AD 10MHz, 4-Quadrant Multiplier/Divider pkg:DIP14 1,2,3,4,5,6,7,8,9,10,11,12,13,14
.PARAM XAD734 File:Ad3.lib

*AD 10MHz, 4-Quadrant Multiplier/Divider pkg:DIP14 1,2,3,4,5,6,7,8,9,10,11,12,13,14
.PARAM XAD734A File:Ad3.lib

*AD 10MHz, 4-Quadrant Multiplier/Divider pkg:DIP14 1,2,3,4,5,6,7,8,9,10,11,12,13,14
.PARAM XAD734B File:Ad3.lib

*AD 10MHz, 4-Quadrant Multiplier/Divider pkg:DIP14 1,2,3,4,5,6,7,8,9,10,11,12,13,14
.PARAM XAD734S File:Ad3.lib
