*====================
*LED Pinout: 1=A, 2=K
*====================

*Typ INFRARED GaAs LED: Vf=1.2V Vr=5V If=40mA trr=3uS
.PARAM DLED0 File:Mcediode.lib

*Typ RED GaAs LED: Vf=1.7V Vr=4V If=40mA trr=3uS
.PARAM DLED1 File:Mcediode.lib

*Typ RED,GREEN,YELLOW,AMBER GaAs LED: Vf=2.1V Vr=4V If=40mA trr=3uS
.PARAM DLED2 File:Mcediode.lib

*Typ BLUE SiC LED: Vf=3.4V Vr=5V If=40mA trr=3uS
.PARAM DLED3 File:Mcediode.lib
