*==============================================
*NJFET Pinout: 1=D, 2=G, 3=S
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*Default N-Ch J-FET parameters pkg:TO-92B 3,1,2
.PARAM JNJFET~ File:Mcejfets.lib

*40V 30mA Depl pkg:TO-18 2,3,1
.PARAM J2N4393 File:Mcejfets.lib

*25V  25mA  250 ohm Depl pkg:TO-92B 3,1,2
.PARAM J2N5457 File:Mcejfets.lib

*25V  25mA  250 ohm Depl pkg:TO-92B 3,1,2
.PARAM J2N5459 File:Mcejfets.lib

*25V  30mA  175 ohm Depl pkg:TO-92B 3,1,2
.PARAM J2N5484 File:Mcejfets.lib

*25V  30mA  28.8ohm  Depl pkg:TO-92B 3,1,2
.PARAM J2N5486 File:Mcejfets.lib

*30V  20mA  35.3ohm  Depl pkg:TO-92B 3,1,2
.PARAM J2N5640 File:Mcejfets.lib

*25V  20mA  35.3ohm  Depl pkg:TO-92B 3,1,2
.PARAM J2N5668 File:Mcejfets.lib

*25V  20mA  35.3ohm  Depl pkg:TO-92B 3,1,2
.PARAM J2N5669 File:Mcejfets.lib

*25V  20mA  35.3ohm  Depl pkg:TO-92B 3,1,2
.PARAM J2N5670 File:Mcejfets.lib

*30V 150mA Depl pkg:TO-92B 1,2,3
.PARAM J2N4416 File:Mcejfets.lib

*30V 50mA Depl pkg:TO-92B 1,2,3
.PARAM JBF244A File:Mcejfets.lib

*30V 50mA Depl pkg:TO-92B 1,2,3
.PARAM JBF244B File:Mcejfets.lib

*30V 50mA Depl pkg:TO-92B 1,2,3
.PARAM JBF244C File:Mcejfets.lib

*30V 0.1A 15.8ohm TO-92B 1,3,2
.PARAM JBF245 File:Mcejfets.lib

*30V 0.1A 15.8ohm TO-92B 1,3,2
.PARAM JBF245A File:Mcejfets.lib

*30V 0.1A 15.8ohm TO-92B 1,3,2
.PARAM JBF245B File:Mcejfets.lib

*30V 0.1A 15.8ohm TO-92B 1,3,2
.PARAM JBF245C File:Mcejfets.lib

*25V 0.1A 15.8ohm TO-92B 1,2,3
.PARAM JBF246A File:Mcejfets.lib

*25V 0.1A 15.8ohm TO-92B 1,2,3
.PARAM JBF246B File:Mcejfets.lib

*25V 0.1A 15.8ohm TO-92B 3,1,2
.PARAM JBF247B File:Mcejfets.lib

*30V 0.1A 15.8ohm TO-92B 1,3,2
.PARAM JBF256B File:Mcejfets.lib

*30V 0.1A 15.8ohm TO-92B 1,3,2
.PARAM JBF256C File:Mcejfets.lib

*50V 0.01A 50ohm TO-92B 3,1,2
.PARAM JMPF3821 File:Mcejfets.lib

*50V 0.01A 50ohm TO-92B 3,1,2
.PARAM JMPF3822 File:Mcejfets.lib

*pkg: TO-92B 2,1,3
.PARAM J2N3370 File:Mcejfets.lib

*pkg: TO-18
.PARAM J2N3458 File:Mcejfets.lib

*pkg: TO-18
.PARAM J2N3459 File:Mcejfets.lib

*pkg: TO-72 2,3,1
.PARAM J2N3684 File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N3685 File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N3686 File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N3687 File:Mcejfets.lib

*pkg: TO-72 2,3,1
.PARAM J2N3821 File:Mcejfets.lib

*pkg: TO-72 2,3,1
.PARAM J2N3822 File:Mcejfets.lib

*pkg: TO-72 2,3,1
.PARAM J2N3823 File:Mcejfets.lib

*pkg: TO-72 2,3,1
.PARAM J2N3824 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N3921 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N3922 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N3954 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N3954A File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N3955 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N3955A File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N3956 File:Mcejfets.lib

*Dual pkg: TO-71 (A:2,3,1)(B:6,7,5)
.PARAM J2N3957 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N3958 File:Mcejfets.lib

*pkg: TO-72 
.PARAM J2N3966 File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N3967 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N3970 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N3971 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N3972 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N4084 File:Mcejfets.lib

*pkg: TO-18 2,3,1 
.PARAM J2N4091 File:Mcejfets.lib

*pkg: TO-18 2,3,1 
.PARAM J2N4092 File:Mcejfets.lib

*pkg: TO-18 2,3,1 
.PARAM J2N4093 File:Mcejfets.lib

*pkg: TO-72 
.PARAM J2N4117 File:Mcejfets.lib

*pkg: TO-72 
.PARAM J2N4117A File:Mcejfets.lib

*pkg: TO-72 
.PARAM J2N4118 File:Mcejfets.lib

*pkg: TO-72 
.PARAM J2N4118A File:Mcejfets.lib

*pkg: TO-72 
.PARAM J2N4119 File:Mcejfets.lib

*pkg: TO-72 
.PARAM J2N4119A File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N4220 File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N4220A File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N4221 File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N4221A File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N4222 File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N4222A File:Mcejfets.lib

*pkg: TO-72 1,3,2
.PARAM J2N4223 File:Mcejfets.lib

*pkg: TO-18 1,3,2
.PARAM J2N4338 File:Mcejfets.lib

*pkg: TO-18 
.PARAM J2N4339 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4340 File:Mcejfets.lib

*pkg: TO-18 
.PARAM J2N4341 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4391 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4392 File:Mcejfets.lib

*pkg: TO-72 2,3,1
.PARAM J2N4416A File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4856 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4856A File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4857 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4857A File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4858 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4858A File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4859 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4859A File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4860 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4860A File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4861 File:Mcejfets.lib

*pkg: TO-18 2,3,1
.PARAM J2N4861A File:Mcejfets.lib

*pkg: TO-71 1,3,2
.PARAM J2N5045 File:Mcejfets.lib

*pkg: TO-71 1,3,2
.PARAM J2N5046 File:Mcejfets.lib

*pkg: Dual TO-71 (A:2,3,1)(B:6,7,5)
.PARAM J2N5047 File:Mcejfets.lib

*pkg: TO-72 2,3,1
.PARAM J2N5078 File:Mcejfets.lib

*pkg: TO-72 
.PARAM J2N5103 File:Mcejfets.lib

*pkg: TO-72 
.PARAM J2N5105 File:Mcejfets.lib

*pkg: Dual TO-71 (A:2,3,1)(B:6,7,5)
.PARAM J2N5196 File:Mcejfets.lib

*pkg: Dual TO-71 (A:2,3,1)(B:6,7,5)
.PARAM J2N5197 File:Mcejfets.lib

*pkg: Dual TO-71 (A:2,3,1)(B:6,7,5)
.PARAM J2N5199 File:Mcejfets.lib

*pkg: TO-72 
.PARAM J2N5358 File:Mcejfets.lib

*pkg: TO-72 2,3,1
.PARAM J2N5397 File:Mcejfets.lib

*pkg: TO-72 2,3,1
.PARAM J2N5398 File:Mcejfets.lib

*pkg: TO-52 
.PARAM J2N5432 File:Mcejfets.lib

*pkg: TO-52 
.PARAM J2N5433 File:Mcejfets.lib

*pkg: TO-52 
.PARAM J2N5434 File:Mcejfets.lib

*pkg: Dual TO-71 (A:2,3,1)(B:6,7,5)
.PARAM J2N5452 File:Mcejfets.lib

*pkg: Dual TO-71 (A:2,3,1)(B:6,7,5)
.PARAM J2N5454 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5515 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5516 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5517 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5518 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5519 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5520 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5521 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5522 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5523 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5524 File:Mcejfets.lib

*pkg: Dual TO-71 (A:2,3,1)(B:6,7,5)
.PARAM J2N5545 File:Mcejfets.lib

*pkg: TO-72 3,2,1
.PARAM J2N5556 File:Mcejfets.lib

*pkg: TO-72 3,2,1
.PARAM J2N5557 File:Mcejfets.lib

*pkg: TO-72 3,2,1
.PARAM J2N5558 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5565 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N5566 File:Mcejfets.lib

*pkg: TO-78 
.PARAM J2N5902 File:Mcejfets.lib

*pkg: TO-78 
.PARAM J2N5904 File:Mcejfets.lib

*pkg: TO-78 
.PARAM J2N5905 File:Mcejfets.lib

*pkg: TO-78 
.PARAM J2N5906 File:Mcejfets.lib

*pkg: TO-78 
.PARAM J2N5907 File:Mcejfets.lib

*pkg: TO-78 
.PARAM J2N5909 File:Mcejfets.lib

*pkg: TO-78 
.PARAM J2N5911 File:Mcejfets.lib

*pkg: TO-78 
.PARAM J2N5912 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N6483 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N6484 File:Mcejfets.lib

*pkg: TO-71 
.PARAM J2N6485 File:Mcejfets.lib

*pkg: DIP8 
.PARAM JJ401 File:Mcejfets.lib

*pkg: DIP8 
.PARAM JJ402 File:Mcejfets.lib

*pkg: DIP8 
.PARAM JJ403 File:Mcejfets.lib

*pkg: DIP8 
.PARAM JJ404 File:Mcejfets.lib

*pkg: DIP8 
.PARAM JJ405 File:Mcejfets.lib

*pkg: DIP8 
.PARAM JJ406 File:Mcejfets.lib

*pkg: DIP8 
.PARAM JJ410 File:Mcejfets.lib

*pkg: DIP8 
.PARAM JJ411 File:Mcejfets.lib

*pkg: DIP8 
.PARAM JJ412 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JNDF9406 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JNDF9407 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JNDF9409 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JNDF9410 File:Mcejfets.lib

*pkg: TO-78 
.PARAM JU257 File:Mcejfets.lib

*pkg: TO-52 
.PARAM JU308 File:Mcejfets.lib

*pkg: TO-52 
.PARAM JU309 File:Mcejfets.lib

*pkg: TO-52 
.PARAM JU310 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JU401 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JU402 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JU403 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JU404 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JU405 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JU406 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JU440 File:Mcejfets.lib

*pkg: TO-71 
.PARAM JU441 File:Mcejfets.lib

