*==============================================
*NPN Trans Pinout: C,B,E
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*=========================================
*MicroCode Engineering

*Default NPN BJT pkg:TO-92B 1,2,3
.PARAM QNPN~ File:Mcebjt.lib

*pkg:TO-92B 1,2,3
.PARAM QQNPN File:Mcebjt.lib

*Si 800mW 40V 800mA 350MHz GenPurp pkg:TO-5 3,2,1
.PARAM Q2N2219A File:Mcebjt.lib

*Si 500mW 40V 800mA 300MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2222A File:Mcebjt.lib

*Si 360mW 15V 500mA 600MHz Switching pkg:TO-18 3,2,1
.PARAM Q2N2369A File:Mcebjt.lib

*Si 360mW 60V 50mA 100MHz pkg:TO-18 3,2,1
.PARAM Q2N2484 File:Mcebjt.lib

*Si 800mW 80V 1A 190MHz pkg:TO-5 3,2,1
.PARAM Q2N3019 File:Mcebjt.lib

*Si 5W 40V 700mA 185MHz pkg:TO-5 3,2,1
.PARAM Q2N3053 File:Mcebjt.lib

*Si 115W 70V 15A 20kHz pkg:TO-3 3,2,1
.PARAM Q2N3055 File:Mcebjt.lib

*Si 1W 150V 300mA 283MHz pkg:TO-5 3,2,1
.PARAM Q2N3501 File:Mcebjt.lib

*Si 1W 50V 3A 60MHz pkg:TO-5 3,2,1
.PARAM Q2N3507 File:Mcebjt.lib

*Si 500mW 80V 1A 190MHz pkg:TO-18 3,2,1
.PARAM Q2N3700 File:Mcebjt.lib

*Si 625mW 40V 200mA 300MHz pkg:TO-92B 1,2,3
.PARAM Q2N3904 File:Mcebjt.lib

*Si 350mW 40V 200mA 300MHz alias:Q2N3904 pkg:SOT-23 1,3,2
.PARAM AMMBT3904

*Si 1W 40V 200mA 300MHz alias:Q2N3904 pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM AMMPQ3904

*Si 1W 40V 200mA 300MHz alias:Q2N3904 pkg:SOT-223 2,1,3
.PARAM APZT3904

*Si 360mW 40V 200mA 346MHz pkg:TO-18 3,2,1
.PARAM Q2N3947 File:Mcebjt.lib

*Si 625mW 40V 600mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4401 File:Mcebjt.lib

*Si 350mW 40V 600mA 250MHz GenPurp alias:Q2N4401 pkg:SOT-23 1,3,2
.PARAM AMMBT4401

*Si 625mW 160V 600mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5551 File:Mcebjt.lib

*Si 350mW 160V 600mA 300MHz GenPurp alias:Q2N5551 pkg:SOT-23 1,3,2
.PARAM AMMBT5551

*Si 500mW 300V 50mA 300MHz pkg:TO-18 3,2,1
.PARAM Q2N6431 File:Mcebjt.lib

*Si 625mW 350V 500mA 200MHz pkg:TO-92B 1,2,3
.PARAM Q2N6517 File:Mcebjt.lib

*Si 50W 150V 8A 70MHz pkg:TO-220 2,1,3
.PARAM XMJE15030 File:Mcebjt.lib

*Si 625mW 75V 500mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QPN100 File:Mcebjt.lib

*Si 350mW 75V 500mA 250MHz GenPurp alias:QPN100 pkg:SOT-23 1,3,2
.PARAM AMMBT100

*Si 625mW 75V 500mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QPN100A File:Mcebjt.lib

*Si 350mW 75V 500mA 250MHz GenPurp alias:QPN100A pkg:SOT-23 1,3,2
.PARAM AMMBT100A

*Si 350mW 15V 50mA 690MHz RF pkg:TO-92B 1,2,3
.PARAM QPN918 File:Mcebjt.lib

*Si 225mW 15V 50mA 690MHz RF alias:QPN918 pkg:SOT-23 1,3,2
.PARAM AMMBT918

*Si 1W 80V 1A 155MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QTN3019A File:Mcebjt.lib

*Si 1W 250V 100mA 60MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QTN3440A File:Mcebjt.lib

*Si 350mW 15V 50mA 690MHz RF pkg:TO-92B 1,2,3
.PARAM QPN3563 File:Mcebjt.lib

*Si 1W 40V 1.2A 300MHz Switching pkg:TO-92B 1,2,3
.PARAM QTN3725A File:Mcebjt.lib

*Si 1W 40V 1.2A 300MHz Switching alias:QTN3725A pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM AMMPQ3725

*Si 625mW 25V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4124 File:Mcebjt.lib

*Si 350mW 25V 200mA 300MHz GenPurp alias:Q2N4124 pkg:SOT-23 1,3,2
.PARAM AMMBT4124

*Si 625mW 30V 100mA 50MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5088 File:Mcebjt.lib

*Si 350mW 30V 100mA 50MHz GenPurp alias:Q2N5088 pkg:SOT-23 1,3,2
.PARAM AMMBT5088

*Si 625mW 25V 100mA 50MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5089 File:Mcebjt.lib

*Si 625mW 50V 100mA 30MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5210 File:Mcebjt.lib

*Si 1W 30V 2A 110MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QTN6714A File:Mcebjt.lib

*Si 1W 30V 2A 110MHz GenPurp alias:QTN6714A pkg:SOT-223 2,1,3
.PARAM ANZT6714

*Si 1W 40V 1.5A 127MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QTN6715A File:Mcebjt.lib

*Si 1W 40V 1.5A 127MHz GenPurp alias:QTN6715A pkg:SOT-223 2,1,3
.PARAM ANZT6715

*Si 1W 80V 1.2A 141MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QTN6717A File:Mcebjt.lib

*Si 1W 80V 1.2A 141MHz GenPurp alias:QTN6717A pkg:SOT-223 2,1,3
.PARAM ANZT6717

*Si 625mW 25V 1A 155MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPS8050 File:Mcebjt.lib

*Si 625mW 300V 200mA 50MHz HiVoltAmp pkg:TO-92B 1,2,3
.PARAM QMPSA42 File:Mcebjt.lib

*Si 1W 300V 200mA 50MHz HiVoltAmp alias:QMPSA42 pkg:SOT-223 2,1,3
.PARAM APZTA42

*Si 625mW 200V 200mA 50MHz HiVoltAmp pkg:TO-92B 1,2,3
.PARAM QMPSA43 File:Mcebjt.lib

*Si 350mW 200V 200mA 50MHz HiVoltAmp alias:QMPSA43 pkg:SOT-23 1,3,2
.PARAM AMMBTA43

*Si 350mW 25V 50mA 650MHz RF pkg:TO-92B 1,2,3
.PARAM QMPSH10 File:Mcebjt.lib

*Si 225mW 25V 50mA 650MHz RF alias:QMPSH10 pkg:SOT-23 1,3,2
.PARAM AMMBTH10

*Si 350mW 25V 50mA 650MHz RF pkg:TO-92B 1,2,3
.PARAM QMPSH11 File:Mcebjt.lib

*Si 225mW 25V 50mA 650MHz RF alias:QMPSH11 pkg:SOT-23 1,3,2
.PARAM AMMBTH11

*Si 625mW 30V 50mA 400MHz RF pkg:TO-92B 1,2,3
.PARAM QMPSH24 File:Mcebjt.lib

*Si 60W 60V 8A 50MHz PwrAmp pkg:TO-220 2,1,3
.PARAM XD44H8 File:Mcebjt.lib

*Si 1.5W 60V 8A 50MHz PwrAmp alias:XD44H8 pkg:SOT-223 2,1,3
.PARAM ANZT44H8

*Si 1.5W  300V 100mA  60MHz pkg:SOT-223 2,1,3
.PARAM QBF720 File:Mcebjt.lib

*Si 200W 250V 10A HiPwr LinAmp pkg:TO-3 3,1,2
.PARAM XECG87 File:Mcebjt.lib

*Si 40W 300V 3A AF PwrAmp pkg:TO-66 3,1,2
.PARAM XECG175 File:Mcebjt.lib

*Si 10W 80V 2A AF Driver PwrAmp pkg:TO-202
.PARAM XECG188 File:Mcebjt.lib

*Si 10W 300V 500mA HV A/V Amp pkg:TO-202
.PARAM XECG191 File:Mcebjt.lib

*Si 10W 350V 1A HiSpeedSw LinAmp A/V pkg:TO-202
.PARAM XECG228A File:Mcebjt.lib

*Si 25W 150V 3A VertDefl AF Amp pkg:TO-220 2,1,3
.PARAM XECG375 File:Mcebjt.lib

*Si 1.5W 300V 150mA PwrAmp pkg:TO-220 2,1,3
.PARAM XECG376 File:Mcebjt.lib

*Si 250W 250V 16A HiPwr AF Amp pkg:TO-3 3,1,2
.PARAM XECG388  File:Mcebjt.lib

*Si 20.8W 300V 500mA pkg:TO-220 2,3,1
.PARAM XMJE340 File:Mcebjt.lib

*Si 1W 40V 500mA 307MHz pkg:TO-39 3,2,1
.PARAM QMM3725 File:Mcebjt.lib

*Si 225mW 25V 50mA 600MHz pkg:SOT-23 1,3,2
.PARAM QMMBT5089 File:Mcebjt.lib

*Si 225mW 350V 500mA 200MHz pkg:SOT-23 1,3,2
.PARAM QMMBT6517 File:Mcebjt.lib

*Si 225mW 80V 500mA 200MHz pkg:SOT-23 1,3,2
.PARAM QMMBTA06 File:Mcebjt.lib

*Si 225mW 300V 500mA 60MHz pkg:SOT-23 1,3,2
.PARAM QMMBTA42 File:Mcebjt.lib

*Si 225mW 30V 50mA 620MHz pkg:SOT-23 1,3,2
.PARAM QMMBTH24 File:Mcebjt.lib

*Si 625mW 60V 2A 110MHz pkg:TO-92B 1,2,3
.PARAM QMPS651 File:Mcebjt.lib

*Si 350mW 15V 50mA 800MHz pkg:TO-92B 1,2,3
.PARAM QMPS918 File:Mcebjt.lib

*Si 625mW 40V 600mA 300MHz pkg:TO-92B 1,2,3
.PARAM QMPS2222A File:Mcebjt.lib

*Si 310mW 18V 100mA 490MHz pkg:TO-92B 1,2,3
.PARAM QMPS2711 File:Mcebjt.lib

*Si 310mW 18V 100mA 490MHz pkg:TO-92B 1,2,3
.PARAM QMPS2712 File:Mcebjt.lib

*Si 310mW 18V 200mA 250MHz pkg:TO-92B 1,2,3
.PARAM QMPS2713 File:Mcebjt.lib

*Si 310mW 18V 200mA 250MHz pkg:TO-92B 1,2,3
.PARAM QMPS2714 File:Mcebjt.lib

*Si 625mW 15V 300mA 400MHz pkg:TO-92B 1,2,3
.PARAM QMPS3646 File:Mcebjt.lib

*Si 625mW 40V 100mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPS3904 File:Mcebjt.lib

*Si 350mW 12V 50mA 1.5GHz RF pkg:TO-92B 1,2,3
.PARAM QMPS5179 File:Mcebjt.lib

*Si 225mW 12V 50mA 1.5GHz RF alias:QMPS5179 pkg:SOT-23 1,3,2
.PARAM AMMBT5179

*Si 625mW 25V 100mA 490MHz pkg:TO-92B 1,2,3
.PARAM QMPS6521 File:Mcebjt.lib

*Si 350mW 12V 50mA 1.5GHz pkg:TO-92B 1,2,3
.PARAM QMPS6595 File:Mcebjt.lib

*Si 625mW 40V 1A 210MHz pkg:TO-92B 1,2,3
.PARAM QMPS6602 File:Mcebjt.lib

*Si 625mW 80V 500mA 225MHz pkg:TO-92B 1,2,3
.PARAM QMPS8099 File:Mcebjt.lib

*Si 625mW 80V 500mA 219MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPSA06 File:Mcebjt.lib

*Si 1W 80V 500mA 219MHz GenPurp alias:QMPSA06 pkg:SOT-223 2,1,3
.PARAM APZTA06

*Si 350mW 40V 100mA 125MHz pkg:TO-92B 1,2,3
.PARAM QMPSA17 File:Mcebjt.lib

*Si 625mW 45V 200mA 450MHz pkg:TO-92B 1,2,3
.PARAM QMPSA18 File:Mcebjt.lib

*Si 625mW 400V 300mA 200MHz pkg:TO-92B 1,2,3
.PARAM QMPSA44 File:Mcebjt.lib

*Si 350mW 30V 100mA 620MHz RF pkg:TO-92B 1,2,3
.PARAM QMPSH20 File:Mcebjt.lib

*Si 225mW 30V 100mA 620MHz RF alias:QMPSH20 pkg:SOT-23 1,3,2
.PARAM AMMBTH20

*Si 1W 40V 1A 210MHz pkg:TO-92B 1,2,3
.PARAM QMPSW01A File:Mcebjt.lib

*Si 1W 80V 500mA 219MHz pkg:TO-92B 1,2,3
.PARAM QMPSW06 File:Mcebjt.lib

*Si 200mW 20V 200mA 346MHz pkg:SC-59 1,3,2
.PARAM QMSC1621 File:Mcebjt.lib

*Si 200mW 20V 30mA 300MHz pkg:SC-59 1,3,2
.PARAM QMSC2295B File:Mcebjt.lib

*Si 200mW 20V 30mA 300MHz pkg:SC-59 1,3,2
.PARAM QMSC2295C File:Mcebjt.lib

*Si 200mW 20V 15mA 1.2GHz pkg:SC-59 1,3,2
.PARAM QMSC2404C File:Mcebjt.lib

*Si 200mW 10V 50mA 2GHz pkg:SC-59 1,3,2
.PARAM QMSC3130 File:Mcebjt.lib

*Si 200mW 25V 100mA 490MHz pkg:SC-59 1,3,2
.PARAM QMSD601R File:Mcebjt.lib

*Si 200mW 25V 500mA 219MHz pkg:SC-59 1,3,2
.PARAM QMSD602R File:Mcebjt.lib

*Si 200mW 20V 500mA 219MHz pkg:SC-59 1,3,2
.PARAM QMSD1328R File:Mcebjt.lib

*Si 625mW 20V 2A 45MHz GenPurp pkg:TO-92B 2,1,3
.PARAM QBC368 File:Mcebjt.lib

*Si 350mW 45V 1.5A 127MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC817-25 File:Mcebjt.lib

*Si 350mW 45V 1.5A 127MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC817-40 File:Mcebjt.lib

*Si 350mW 25V 1.5A 127MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC818-25 File:Mcebjt.lib

*Si 350mW 25V 1.5A 127MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC818-40 File:Mcebjt.lib

*Si 325mW 65V 100mA 100MHz pkg:SOT-23 1,3,2
.PARAM QBC846A File:Mcebjt.lib

*Si 325mW 45V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC847A File:Mcebjt.lib

*Si 325mW 45V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC847C File:Mcebjt.lib

*Si 1.5W 45V 1.5A 127MHz GenPurp pkg:SOT-223 2,1,3
.PARAM QBCP54 File:Mcebjt.lib

*Si 350mW 32V 500mA 200MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW31 File:Mcebjt.lib

*Si 350mW 32V 500mA 200MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW33 File:Mcebjt.lib

*Si 350mW 32V 1A 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW65C File:Mcebjt.lib

*Si 350mW 45V 500mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW71 File:Mcebjt.lib

*Si 1.2W 60V 4A 75MHz CurrentDrvr pkg:SOT-223 2,1,3
.PARAM XNZT651 File:Mcebjt.lib

*Si 625mW 40V 200mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N3903 File:Mcebjt.lib

*Si 625mW 30V 200mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4123 File:Mcebjt.lib

*Si 350mW 15V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4264 File:Mcebjt.lib

*Si 350mW 12V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4265 File:Mcebjt.lib

*Si 625mW 40V 600mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4400 File:Mcebjt.lib

*Si 625mW 80V 250mA 100MHz Amp pkg:TO-92B 1,2,3
.PARAM Q2N4410 File:Mcebjt.lib

*Si 625mW 50V 50mA 30MHz Amp pkg:TO-92B 1,2,3
.PARAM Q2N5209 File:Mcebjt.lib

*Si 625mW 140V 600mA 200MHz Amp pkg:TO-92B 1,2,3
.PARAM Q2N5550 File:Mcebjt.lib

*Si 625mW 250V 500mA 100MHz HiVolt pkg:TO-92B 1,2,3
.PARAM Q2N6515 File:Mcebjt.lib

*Si 625mW 300V 500mA 100MHz HiVolt pkg:TO-92B 1,2,3
.PARAM Q2N6516 File:Mcebjt.lib

*Si 625mW 45V 800mA 210MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC337-16 File:Mcebjt.lib

*Si 625mW 45V 800mA 210MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC337-25 File:Mcebjt.lib

*Si 625mW 45V 800mA 210MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC337-40 File:Mcebjt.lib

*Si 625mW 25V 800mA 210MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC338-16 File:Mcebjt.lib

*Si 625mW 25V 800mA 210MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC338-25 File:Mcebjt.lib

*Si 625mW 25V 800mA 210MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC338-40 File:Mcebjt.lib

*Si 625mW 80V 500mA 200MHz HiCurr pkg:TO-92B 3,2,1
.PARAM QBC489 File:Mcebjt.lib

*Si 625mW 80V 500mA 200MHz HiCurr pkg:TO-92B 3,2,1
.PARAM QBC489A File:Mcebjt.lib

*Si 625mW 80V 500mA 200MHz HiCurr pkg:TO-92B 3,2,1
.PARAM QBC489B File:Mcebjt.lib

*Si 625mW 65V 100mA 300MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC546A File:Mcebjt.lib

*Si 625mW 65V 100mA 300MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC546B File:Mcebjt.lib

*Si 625mW 45V 100mA 300MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC547A File:Mcebjt.lib

*Si 625mW 45V 100mA 300MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC547B File:Mcebjt.lib

*Si 625mW 45V 100mA 300MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC547C File:Mcebjt.lib

*Si 625mW 30V 100mA 300MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC548A File:Mcebjt.lib

*Si 625mW 30V 100mA 300MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC548B File:Mcebjt.lib

*Si 625mW 30V 100mA 300MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC548C File:Mcebjt.lib

*Si 625mW 45V 500mA 200MHz HiCurr pkg:TO-92B 2,1,3
.PARAM QBC635 File:Mcebjt.lib

*Si 625mW 60V 500mA 200MHz HiCurr pkg:TO-92B 2,1,3
.PARAM QBC637 File:Mcebjt.lib

*Si 625mW 80V 500mA 200MHz HiCurr pkg:TO-92B 2,1,3
.PARAM QBC639 File:Mcebjt.lib

*Si 225mW 45V 500mA 200MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC817-16LT1 File:Mcebjt.lib

*Si 225mW 65V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC846ALT1 File:Mcebjt.lib

*Si 225mW 65V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC846BLT1 File:Mcebjt.lib

*Si 225mW 45V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC847ALT1 File:Mcebjt.lib

*Si 225mW 45V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC847BLT1 File:Mcebjt.lib

*Si 225mW 45V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC847CLT1 File:Mcebjt.lib

*Si 225mW 30V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC848ALT1 File:Mcebjt.lib

*Si 225mW 30V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC848BLT1 File:Mcebjt.lib

*Si 225mW 30V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC848CLT1 File:Mcebjt.lib

*Si 225mW 30V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC849ALT1 File:Mcebjt.lib

*Si 225mW 30V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC849BLT1 File:Mcebjt.lib

*Si 225mW 30V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC849C File:Mcebjt.lib

*Si 225mW 45V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC850ALT1 File:Mcebjt.lib

*Si 225mW 45V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC850BLT1 File:Mcebjt.lib

*Si 225mW 45V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC850CLT1 File:Mcebjt.lib

*Si 1.5W 80V 1A 130MHz HiCurr pkg:SOT-223 2,1,3
.PARAM QBCP56T1 File:Mcebjt.lib

*Si 1.5W 80V 1A 130MHz HiCurr pkg:SOT-223 2,1,3
.PARAM QBCP56-10T1 File:Mcebjt.lib

*Si 1.5W 80V 1A 130MHz HiCurr pkg:SOT-223 2,1,3
.PARAM QBCP56-16T1 File:Mcebjt.lib

*Si 1.5W 25V 1A 60MHz HiCurr pkg:SOT-223 2,1,3
.PARAM QBCP68T1 File:Mcebjt.lib

*Si 225mW 32V 100mA 125MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW60ALT1 File:Mcebjt.lib

*Si 225mW 32V 100mA 125MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW60BLT1 File:Mcebjt.lib

*Si 225mW 32V 100mA 125MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW60DLT1 File:Mcebjt.lib

*Si 225mW 45V 500mA 219MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCX19LT1 File:Mcebjt.lib

*Si 225mW 25V 500mA 219MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCX20LT1 File:Mcebjt.lib

*Si 225mW 45V 200mA 125MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCX70GLT1 File:Mcebjt.lib

*Si 225mW 45V 200mA 125MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCX70JLT1 File:Mcebjt.lib

*Si 225mW 45V 200mA 125MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCX70KLT1 File:Mcebjt.lib

*Si 1W 100V 500mA 50MHz Amp pkg:TO-92B 2,1,3
.PARAM QBDC01D File:Mcebjt.lib

*Si 1W 300V 500mA 60MHz HiVolt pkg:TO-92B 2,1,3
.PARAM QBDC05 File:Mcebjt.lib

*Si 350mW 25V 100mA 750MHz RF pkg:TO-92B 3,1,2
.PARAM QBF199 File:Mcebjt.lib

*Si 350mW 30V 50mA 600MHz RF pkg:TO-92B 3,1,2
.PARAM QBF224 File:Mcebjt.lib

*Si 350mW 40V 25mA 600MHz AM/FM pkg:TO-92B 3,1,2
.PARAM QBF240 File:Mcebjt.lib

*Si 350mW 25V 100mA 800MHz VHF pkg:TO-92B 1,3,2
.PARAM QBF374 File:Mcebjt.lib

*Si 625mW 200V 500mA 50MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QBF391 File:Mcebjt.lib

*Si 625mW 250V 500mA 50MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QBF392 File:Mcebjt.lib

*Si 625mW 300V 500mA 50MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QBF393 File:Mcebjt.lib

*Si 625mW 300V 500mA 60MHz HiVolt pkg:TO-92B 2,1,3
.PARAM QBF420 File:Mcebjt.lib

*Si 625mW 250V 500mA 60MHz HiVolt pkg:TO-92B 2,1,3
.PARAM QBF422 File:Mcebjt.lib

*Si 625mW 400V 300mA 283MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QBF844 File:Mcebjt.lib

*Si 625mW 20V 100mA 700MHz VHF pkg:TO-92B 3,1,2
.PARAM QBF959 File:Mcebjt.lib

*Si 800mW 350V 1A 70MHz HiVolt pkg:SOT-223 2,1,3
.PARAM QBSP19AT1 File:Mcebjt.lib

*Si 800mW 250V 1A 70MHz HiVolt pkg:SOT-223 2,1,3
.PARAM QBSP20AT1 File:Mcebjt.lib

*Si 225mW 80V 100mA 60MHz Driver pkg:SOT-23 1,3,2
.PARAM QBSS64LT1 File:Mcebjt.lib

*Si 225mW 12V 100mA 400MHz Switching pkg:SOT-23 1,3,2
.PARAM QBSV52LT1 File:Mcebjt.lib

*Si 225mW 30V 600mA 250MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QMMBT2222LT1 File:Mcebjt.lib

*Si 225mW 40V 600mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QMMBT2222ALT1 File:Mcebjt.lib

*Si 225mW 15V 200mA 347MHz Switching pkg:SOT-23 1,3,2
.PARAM QMMBT2369LT1 File:Mcebjt.lib

*Si 225mW 15V 200mA 347MHz Switching pkg:SOT-23 1,3,2
.PARAM QMMBT2369ALT1 File:Mcebjt.lib

*Si 225mW 60V 50mA 693MHz LoNoise pkg:SOT-23 1,3,2
.PARAM QMMBT2484LT1 File:Mcebjt.lib

*Si 225mW 140V 600mA 200MHz HiVolt pkg:SOT-23 1,3,2
.PARAM QMMBT5550LT1 File:Mcebjt.lib

*Si 225mW 50V 200mA 400MHz Amp pkg:SOT-23 1,3,2
.PARAM QMMBT6428LT1 File:Mcebjt.lib

*Si 225mW 45V 200mA 400MHz Amp pkg:SOT-23 1,3,2
.PARAM QMMBT6429LT1 File:Mcebjt.lib

*Si 225mW 60V 500mA 100MHz Driver pkg:SOT-23 1,3,2
.PARAM QMMBTA05LT1 File:Mcebjt.lib

*Si 225mW 40V 100mA 125MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QMMBTA20LT1 File:Mcebjt.lib

*Si 225mW 200V 500mA 50MHz HiVolt pkg:SOT-23 1,3,2
.PARAM QMMBTA43LT1 File:Mcebjt.lib

*Si 1W 30V 500mA 350MHz Quad GenPurp pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM QMMPQ2222 File:Mcebjt.lib

*Si 1W 40V 500mA 350MHz Quad GenPurp pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM QMMPQ2222A File:Mcebjt.lib

*Si 720mW 15V 500mA 550MHz Quad Switch pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM QMMPQ2369 File:Mcebjt.lib

*Si 720mW 30V 200mA 350MHz Quad MpuClkBuff pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM QMMPQ6842 File:Mcebjt.lib

*Si 1.9W 30V 500mA 200MHz Quad GenPurp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ2222 File:Mcebjt.lib

*Si 1.9W 40V 500mA 200MHz Quad GenPurp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ2222A File:Mcebjt.lib

*Si 1.5W 15V 500mA 550MHz Quad Switch pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ2369 File:Mcebjt.lib

*Si 900mW 40V 50mA 100MHz Quad Amp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ2483 File:Mcebjt.lib

*Si 900mW 40V 50mA 100MHz Quad Amp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ2484 File:Mcebjt.lib

*Si 2.5W 40V 1A 275MHz Quad CoreDriver pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ3725 File:Mcebjt.lib

*Si 900mW 40V 200mA 300MHz Quad AmpSwitch pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ3904 File:Mcebjt.lib

*Si 1.7W 150V 500mA 80MHz Quad Amp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ7041 File:Mcebjt.lib

*Si 1.7W 200V 500mA 80MHz Quad Amp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ7042 File:Mcebjt.lib

*Si 1.7W 250V 500mA 80MHz Quad Amp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ7043 File:Mcebjt.lib

*Si 625mW 40V 2A 75MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS650 File:Mcebjt.lib

*Si 350mW 12V 50mA 1GHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS3563 File:Mcebjt.lib

*Si 625mW 30V 600mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPS2222 File:Mcebjt.lib

*Si 625mW 15V 200mA 347MHz Switch pkg:TO-92B 1,2,3
.PARAM QMPS2369 File:Mcebjt.lib

*Si 625mW 15V 200mA 347MHz Switch pkg:TO-92B 1,2,3
.PARAM QMPS2369A File:Mcebjt.lib

*Si 625mW 30V 400mA 500MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS3866 File:Mcebjt.lib

*Si 625mW 30V 200mA 100MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS4123 File:Mcebjt.lib

*Si 625mW 25V 200mA 170MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS4124 File:Mcebjt.lib

*Si 625mW 20V 50mA 800MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6507 File:Mcebjt.lib

*Si 625mW 25V 100mA 490MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6520 File:Mcebjt.lib

*Si 625mW 40V 600mA 200MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6530 File:Mcebjt.lib

*Si 625mW 40V 600mA 200MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6531 File:Mcebjt.lib

*Si 625mW 25V 500mA 60MHz Audio pkg:TO-92B 1,2,3
.PARAM QMPS6560 File:Mcebjt.lib

*Si 350mW 20V 50mA 550MHz VHF pkg:TO-92B 1,3,2
.PARAM QMPS6568A File:Mcebjt.lib

*Si 625mW 20V 50mA 175MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6571 File:Mcebjt.lib

*Si 625mW 25V 1A 100MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6601 File:Mcebjt.lib

*Si 1W 30V 1A 155MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6714 File:Mcebjt.lib

*Si 1W 40V 1A 155MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6715 File:Mcebjt.lib

*Si 1W 80V 500mA 219MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6717 File:Mcebjt.lib

*Si 625mW 60V 500mA 150MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS8098 File:Mcebjt.lib

*Si 625mW 60V 500mA 150MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSA05 File:Mcebjt.lib

*Si 350mW 40V 100mA 150MHz Chopper pkg:TO-92B 1,2,3
.PARAM QMPSA16 File:Mcebjt.lib

*Si 625mW 80V 100mA 80MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSH04 File:Mcebjt.lib

*Si 350mW 40V 50mA 720MHz IF pkg:TO-92B 1,3,2
.PARAM QMPSH34 File:Mcebjt.lib

*Si 625mW 120V 150mA 60MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSL01 File:Mcebjt.lib

*Si 1W 30V 1A 70MHz HiCurr pkg:TO-92B 1,2,3
.PARAM QMPSW01 File:Mcebjt.lib

*Si 1W 60V 500mA 50MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSW05 File:Mcebjt.lib

*Si 1W 300V 500mA 50MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QMPSW10 File:Mcebjt.lib

*Si 1W 300V 500mA 60MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QMPSW42 File:Mcebjt.lib

*Si 200mW 30V 100mA 490MHz GenPurpAmp pkg:SOT-23 1,3,2
.PARAM QMSD601-ST1 File:Mcebjt.lib

*Si 150mW 60V 100mA 490MHz GenPurpAmp pkg:SOT-23 1,3,2
.PARAM QMSD1819A-RT1 File:Mcebjt.lib

*Si 150mW 60V 100mA 490MHz GenPurpAmp pkg:SOT-23 1,3,2
.PARAM QMSD1819A-ST1 File:Mcebjt.lib

*Si 625mW 300V 500mA 50MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QPBF259 File:Mcebjt.lib

*Si 625mW 300V 500mA 50MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QPBF259S File:Mcebjt.lib

*Si 625mW 300V 500mA 50MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QPBF259RS File:Mcebjt.lib

*Si 625mW 40V 600mA 350MHz Amp pkg:TO-92B 3,2,1
.PARAM QP2N2222A File:Mcebjt.lib

*Si 800mW 60V 2A 100MHz HiCurr pkg:SOT-223 2,1,3
.PARAM QPZT651T1 File:Mcebjt.lib

*Si 1.2W 45V 30mA 60MHz Amp pkg:TO-18 3,2,1
.PARAM Q2N930 File:Mcebjt.lib

*Si 1.2W 45V 30mA 90MHz Amp pkg:TO-18 3,2,1
.PARAM Q2N930A File:Mcebjt.lib

*Si 1.2W 80V 500mA 90MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N1893 File:Mcebjt.lib

*Si 1W 65V 1A 90MHz Amp pkg:TO-39 3,2,1
.PARAM Q2N2102 File:Mcebjt.lib

*Si 800mW 40V 800mA 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N2218A File:Mcebjt.lib

*Si 800mW 30V 800mA 300MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N2219 File:Mcebjt.lib

*Si 400mW 30V 800mA 300MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2222 File:Mcebjt.lib

*Si 1W 45V 1A 250MHz Amp pkg:TO-39 3,2,1
.PARAM Q2N2270 File:Mcebjt.lib

*Si 360mW 15V 200mA 500MHz Switch pkg:TO-18 3,2,1
.PARAM Q2N2369 File:Mcebjt.lib

*Si 500mW 65V 1A 150MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2895 File:Mcebjt.lib

*Si 500mW 90V 1A 150MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2896 File:Mcebjt.lib

*Si 800mW 80V 1A 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3020 File:Mcebjt.lib

*Si 1W 60V 700mA 150MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3053A File:Mcebjt.lib

*Si 1W 150V 300mA 200MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3500 File:Mcebjt.lib

*Si 500mW 40V 1A 400MHz Switch pkg:TO-18 3,2,1
.PARAM Q2N4014 File:Mcebjt.lib

*Si 800mW 40V 1A 70MHz Amp pkg:TO-39 3,2,1
.PARAM QBC140-10 File:Mcebjt.lib

*Si 800mW 40V 1A 70MHz Amp pkg:TO-39 3,2,1
.PARAM QBC140-16 File:Mcebjt.lib

*Si 800mW 60V 1A 70MHz Amp pkg:TO-39 3,2,1
.PARAM QBC141-10 File:Mcebjt.lib

*Si 800mW 60V 1A 70MHz Amp pkg:TO-39 3,2,1
.PARAM QBC141-16 File:Mcebjt.lib

*Si 400mW 180V 500mA 110MHz HiVolt pkg:TO-18 3,2,1
.PARAM QBC394 File:Mcebjt.lib

*Si 800mW 250V 100mA 110MHz HiVolt pkg:TO-39 3,2,1
.PARAM QBF258 File:Mcebjt.lib

*Si 500mW 200V 500mA 70MHz HiVolt pkg:TO-18 3,2,1
.PARAM QBSS71 File:Mcebjt.lib

*Si 500mW 250V 500mA 70MHz HiVolt pkg:TO-18 3,2,1
.PARAM QBSS72 File:Mcebjt.lib

*Si 500mW 300V 500mA 70MHz HiVolt pkg:TO-18 3,2,1
.PARAM QBSS73 File:Mcebjt.lib

*Si 360mW 15V 500mA 500MHz pkg:TO-18 3,2,1
.PARAM QBSX20 File:Mcebjt.lib

*Si 600mW 65V 600mA 90MHz Amp pkg:TO-39 3,2,1
.PARAM QCV12253 File:Mcebjt.lib

*Si 1W 150V 200mA 200MHz pkg:TO-39 3,2,1
.PARAM QMM3001 File:Mcebjt.lib

*Si 600mW 12V 70mA 5GHz pkg:TO-92B 1,3,2
.PARAM  QECG10 File:Mcebjt.lib

*Si 750mW 20V 5000mA 150MHz pkg:TO-92B 2,1,3
.PARAM  QECG11 File:Mcebjt.lib

*Si 600mW 20V 500mA 200MHz pkg:TO-126 2,3,1
.PARAM  QECG13 File:Mcebjt.lib

*Si 300mW 18V 50mA 600MHz pkg:TO-126 2,1,3
.PARAM  QECG15 File:Mcebjt.lib

*Si 300mW 40V 100mA 180MHz pkg:TO-126 2,3,1
.PARAM  QECG16 File:Mcebjt.lib

*Si 1W 80V 700mA 120MHz pkg:TO-126 2,3,1
.PARAM  QECG18 File:Mcebjt.lib

*Si 1W 32V 2000mA 100MHz pkg:TO-126 2,3,1
.PARAM  QECG20 File:Mcebjt.lib

*Si 1W 80V 1A 100MHz pkg:TO-126 2,3,1
.PARAM  QECG22 File:Mcebjt.lib

*Si 250mW 14V 500mA 2GHz pkg:TO-92B 1,3,2
.PARAM  QECG23 File:Mcebjt.lib

*Si 1W 80V 1.25A 50MHz pkg:TO-92B 2,1,3
.PARAM  QECG24 File:Mcebjt.lib

*Si 300mW 120V 50mA 100MHz pkg:TO-92B 2,1,3
.PARAM  QECG26 File:Mcebjt.lib

*Si 900mW 160V 1A 20MHz pkg:TO-92B 2,1,3
.PARAM  QECG31 File:Mcebjt.lib

*Si 400mW 100V 50mA 150MHz pkg:SIP5A 2,1,3
.PARAM  QECG40 File:Mcebjt.lib

*Si 400mW 5V 100mA 150MHz pkg:SIP5A 2,1,3
.PARAM  QECG42 File:Mcebjt.lib

*Si 400mW 100V 100mA 100MHz pkg:SIP5A 2,3,1
.PARAM  QECG44 File:Mcebjt.lib

*Si 350mW 45V 200mA 140MHz pkg:TO-92B 1,2,3
.PARAM  QECG47 File:Mcebjt.lib

*Si 75W 400V 4A 4MHz pkg:TO-220 2,1,3
.PARAM  QECG51 File:Mcebjt.lib

*Si 125W 450V 5A 69.3MHz pkg:TO-3 3,2,1
.PARAM  QECG52 File:Mcebjt.lib

*Si 175W 400V 15A 8MHz pkg:TO-3 3,2,1
.PARAM  QECG53 File:Mcebjt.lib

*Si 200W 200V 17A 20MHz pkg:TB-35 2,1,3
.PARAM  QECG58 File:Mcebjt.lib

*Si 250mW 35V 50mA 850MHz pkg:TO-92B 1,3,2
.PARAM  QECG69 File:Mcebjt.lib

*Si 200W 90V 20A 20MHz pkg:TO-126 1,2,3
.PARAM  QECG71 File:Mcebjt.lib

*Si 115W 100V 10A 30MHz pkg:TO-126 1,2,3
.PARAM  QECG72 File:Mcebjt.lib

*Si 60W 100V 7A 30MHz pkg:TO-126 1,2,3
.PARAM  QECG74 File:Mcebjt.lib

*Si 3500mW 30V 400mA 1800MHz pkg:TO-39 3,2,1
.PARAM  QECG77 File:Mcebjt.lib

*Si 5W 18V 600mA 200MHz pkg:TO-202 2,1,3
.PARAM  QECG78 File:Mcebjt.lib

*Si 10W 18V 2A 110MHz pkg:TO-202 2,1,3
.PARAM  QECG79 File:Mcebjt.lib

*Si 600mW 40V 600mA 300MHz Dual pkg:CAN8 (1,2,3)(7.6.5)
.PARAM  QECG81 File:Mcebjt.lib

*Si 600mW 70V 400mA 245MHz pkg:TO-92B 2,1,3
.PARAM  QECG85 File:Mcebjt.lib

*Si 50W 150V 5A 15MHz pkg:TO-3 3,2,1
.PARAM  QECG86 File:Mcebjt.lib

*Si 50W 600V 7A 58.6MHz pkg:TO-3 3,2,1
.PARAM  QECG89 File:Mcebjt.lib

*Si 750mW 120V 50mA 350MHz pkg:TO-92B 2,1,3
.PARAM  QECG90 File:Mcebjt.lib

*Si 100W 300V 5A 5MHz pkg:TO-3 3,2,1
.PARAM  QECG94 File:Mcebjt.lib

*Si 70W 250V 3A 40MHz pkg:TO-126 1,2,3
.PARAM  QECG95 File:Mcebjt.lib

*Ge 150mW 20V 300mA 5MHz pkg:TO-5 3,2,1
.PARAM  QECG101 File:Mcebjt.lib

*Ge 150mW 16V 250mA 2MHz pkg:TO-5 3,2,1
.PARAM  QECG103 File:Mcebjt.lib

*Ge 340mW 32V 500mA 2.5MHz pkg:TO-5 3,2,1
.PARAM  QECG103A File:Mcebjt.lib

*Si 250mW 35V 50mA 900MHz pkg:TO-92B 2,1,3
.PARAM  QECG107 File:Mcebjt.lib

*Si 600mW 15V 50mA 900MHz pkg:TO-92B 1,2,3
.PARAM  QECG108 File:Mcebjt.lib

*Si 800mW 30V 800mA 250MHz pkg:TO-39 3,2,1
.PARAM  QECG123 File:Mcebjt.lib

*Si 500mW 40V 800mA 300MHz pkg:TO-5 3,2,1
.PARAM  QECG123A File:Mcebjt.lib

*Si 500mW 40V 600mA 300MHz pkg:TO-92B 1,2,3
.PARAM  QECG123AP File:Mcebjt.lib

*Si 20W 300V 150mA 300MHz pkg:TO-66 3,1,2
.PARAM  QECG124 File:Mcebjt.lib

*Si 1W 80V 1A 120MHz pkg:TO-39 3,2,1
.PARAM  QECG128 File:Mcebjt.lib

*Si 1W 80V 1A 100MHz pkg:TO-92B 1,2,3
.PARAM  QECG128P File:Mcebjt.lib

*Si 1W 300V 500mA 40MHz pkg:TO-39 3,2,1
.PARAM  QECG154 File:Mcebjt.lib

*Si 180mW 45V 50mA 800MHz pkg:TO-5 3,2,1
.PARAM  QECG161 File:Mcebjt.lib

*Si 100W 300V 3A 89.5MHz pkg:TO-3 3,2,1
.PARAM  QECG162 File:Mcebjt.lib

*Si 50W 700V 1A 1MHz pkg:TO-3 3,2,1
.PARAM  QECG164 File:Mcebjt.lib

*Si 50W 1400V 5A 69.3MHz pkg:TO-3 3,2,1
.PARAM  QECG165 File:Mcebjt.lib

*Si 200W 100V 30A 5MHz pkg:TO-3 3,1,2
.PARAM  QECG181 File:Mcebjt.lib

*Si 350mW 160V 600mA 100MHz pkg:TO-92B 1,2,3
.PARAM  QECG194 File:Mcebjt.lib

*Si 2W 500V 1A 20MHz pkg:TO-220 2,1,3
.PARAM  QECG198 File:Mcebjt.lib

*Si 360mW 50V 100mA 100MHz pkg:TO-92B 2,1,3
.PARAM  QECG199 File:Mcebjt.lib

*Si 1.33W 75V 1A 200MHz pkg:TO-126 3,2,1
.PARAM  QECG210 File:Mcebjt.lib

*Si 1W 50V 1.5A 300MHz pkg:TO-92B 1,2,3
.PARAM  QECG216 File:Mcebjt.lib

*Si 10W 350V 1A 15MHz pkg:TO-39 1,2,3
.PARAM  QECG225 File:Mcebjt.lib

*Si 1W 300V 100mA 50MHz pkg:TO-92B 1,2,3
.PARAM  QECG227 File:Mcebjt.lib

*Si 425mW 40V 50mA 600MHz pkg:TO-92B 1,3,2
.PARAM  QECG229 File:Mcebjt.lib

*Si 625mW 30V 100mA 300MHz pkg:TO-92B 1,2,3
.PARAM  QECG233 File:Mcebjt.lib

*Si 60W 80V 4A 2MHz pkg:TO-220 2,1,3
.PARAM  QECG241 File:Mcebjt.lib

*Si 1W 300V 1A 40MHz pkg:TO-92B 1,2,3
.PARAM  QECG255 File:Mcebjt.lib

*Si 3.5W 30V 400mA 1.3GHz pkg:TO-39 3,2,1
.PARAM  QECG278 File:Mcebjt.lib

*Si 100W 140V 12A 6MHz pkg:TO-3 3,2,1
.PARAM  QECG280 File:Mcebjt.lib

*Si 100W 325V 10A 6MHz pkg:TO-3 3,2,1
.PARAM  QECG283 File:Mcebjt.lib

*Si 625mW 300V 500mA 50MHz pkg:TO-92B 1,2,3
.PARAM  QECG287 File:Mcebjt.lib

*Si 5W 40V 1A 160MHz pkg:TO-126 2,3,1
.PARAM  QECG295 File:Mcebjt.lib

*Si 7W 40V 1.5A 70MHz pkg:TO-126 1,2,3
.PARAM  QECG300 NPN File:Mcebjt.lib

*Si 5W 30V 400mA 900MHz pkg:TO-39 3,2,1
.PARAM  QECG311 File:Mcebjt.lib

*Si 750mW 50V 1A 80MHz pkg:TO-92B 2,1,3
.PARAM  QECG315 File:Mcebjt.lib

*Si 15W 700V 1.5A 127MHz pkg:TO-66 3,2,1
.PARAM  QECG321 File:Mcebjt.lib

*Si 400mW 12V 40mA 5000MHz pkg:TO-126 1,2,3
.PARAM QECG63 File:Mcebjt.lib

*Si 350mW 15V 30mA 4500MHz pkg:TO-126 1,2,3
.PARAM QECG64 File:Mcebjt.lib

*Si 5W 30V 400mA 1800MHz pkg:TO-126 1,2,3
.PARAM QECG76 File:Mcebjt.lib

*Si 150mW 50V 1A 400MHz pkg:TO-126 1,2,3
.PARAM QECG313 File:Mcebjt.lib

*Si 200mW 15V 50mA 1400MHz pkg:TO-72 3,2,1
.PARAM QECG316 File:Mcebjt.lib

*Si 220W 36V 15A 40MHz pkg:TO-126 1,2,3
.PARAM QECG317 File:Mcebjt.lib

*Si 80W 36V 6A 63.3MHz pkg:TO-126 1,2,3
.PARAM QECG318 File:Mcebjt.lib

*Si 500mW 30V 50mA 400MHz pkg:TO-92B 1,3,2
.PARAM QECG319P File:Mcebjt.lib

*Si 80W 36V 6A 250MHz pkg:TO-126 1,2,3
.PARAM QECG320 File:Mcebjt.lib

*Si 80W 36V 6A 250MHz pkg:TO-126 1,2,3
.PARAM QECG320F File:Mcebjt.lib

*Si 750mW 18V 500mA 155MHz pkg:TO-92B 2,1,3
.PARAM QECG340 File:Mcebjt.lib

*Si 8W 18V 640mA 155MHz pkg:TO-39 1,2,3
.PARAM QECG341 File:Mcebjt.lib

*Si 12.5W 17V 2A 155MHz pkg:TO-220 3,1,2
.PARAM QECG342 File:Mcebjt.lib

*Si 25W 17V 3.5A 155MHz pkg:TO-220 3,1,2
.PARAM QECG343 File:Mcebjt.lib

*Si 1W 20V 400mA 155MHz pkg:TO-39 3,2,1
.PARAM QECG346 File:Mcebjt.lib

*Si 60W 35V 5A 155MHz pkg:TO-126 1,2,3
.PARAM QECG360 File:Mcebjt.lib

*Si 40W 400V 3A 7MHz pkg:TO-66 3,1,2
.PARAM QECG369 File:Mcebjt.lib

*Si .9W 100V 1A 140MHz pkg:TO-92B 2,1,3
.PARAM QECG382 File:Mcebjt.lib

*Si 10W 350V 1A 20MHz pkg:TO-39 3,2,1
.PARAM QECG396 File:Mcebjt.lib

*Si .9W 300V 100mA 60MHz pkg:TO-92B 2,1,3
.PARAM QECG399 File:Mcebjt.lib

*Si 5W 16V 400mA 400MHz pkg:TO-39 3,2,1
.PARAM QECG472 File:Mcebjt.lib

*Si 7W 18V 1A 155MHz pkg:TO-39 3,2,1
.PARAM QECG473 File:Mcebjt.lib

*Si 9.5W 18V 600A 88MHz pkg:TO-126 3,1,2
.PARAM QECG474 File:Mcebjt.lib

*Si 3.5W 14V 400A 500MHz pkg:TO-39 3,2,1
.PARAM QECG479 File:Mcebjt.lib

*Si 2.5W 20V 150A 1900MHz pkg:TO-39 3,2,1
.PARAM QECG486 File:Mcebjt.lib

*Si 5W 18V 400A 500MHz pkg:TO-39 3,2,1
.PARAM QECG487 File:Mcebjt.lib

*Si 8W 18V 800A 150MHz pkg:TO-39 3,2,1
.PARAM QECG488 File:Mcebjt.lib

*Si 1.9W 40V 500mA 350MHz Quad pkg:DIP14 (1,2,3)(7,6,5)(8,9,10)(14,13,12)
.PARAM QECG2321 File:Mcebjt.lib

*Si 1.7W 200V 500mA 80MHz Quad pkg:DIP14 (1,2,3)(7,6,5)(8,9,10)(14,13,12)
.PARAM QECG2323 File:Mcebjt.lib

*Si 1W 80V 4A 50MHz pkg:TO-39 3,2,1
.PARAM QECG2347 File:Mcebjt.lib

*Si 1W 50V 2A 150MHz pkg:TO-92B 2,1,3
.PARAM QECG2363 File:Mcebjt.lib

*Si 1W 80V 1A 100MHz pkg:SOT-89 2,1,3
.PARAM QECG2428 File:Mcebjt.lib

*Si 1W 350V 1A 70MHz pkg:SOT-89 2,1,3
.PARAM QECG2430 File:Mcebjt.lib

*Si .6W 25V 700mA 270MHz pkg:TO-92B 2,1,3
.PARAM QECG2503 File:Mcebjt.lib

*Si 1W 25V 2A 260MHz pkg:TO-126 2,3,1
.PARAM QECG2505 File:Mcebjt.lib

*Si 300W 80V 50A 2MHz Power pkg:TO-3 3,2,1
.PARAM XECG29    File:Mcebjt.lib

*Si 115W 60V 15A .8MHz Power pkg:TO-3 3,2,1
.PARAM XECG130   File:Mcebjt.lib

*Si 250W 140V 20A 2MHz Power pkg:TO-3 3,2,1
.PARAM XECG60    File:Mcebjt.lib

*Si 140W 130V 15A 60MHz Power pkg:TO-3 3,2,1
.PARAM XECG328   File:Mcebjt.lib

*Si 200W 150V 25A 40MHz Power pkg:TO-3 3,2,1
.PARAM XECG327   File:Mcebjt.lib

*Si 250W 150V 50A 30MHz Power pkg:TO-3 3,2,1
.PARAM XECG387   File:Mcebjt.lib

*Si 150W 180V 16A 6MHz Power pkg:TO-3 3,2,1
.PARAM XECG284   File:Mcebjt.lib

*Si 150W 350V 10A 4.65MHz Power pkg:TO-3 3,2,1
.PARAM XECG385   File:Mcebjt.lib

*Si 100W 700V 3A 8.49MHz Power pkg:TO-3 3,2,1
.PARAM XECG163A  File:Mcebjt.lib

*Si 175W 500V 20A 3.29MHz Power pkg:TO-3 3,2,1
.PARAM XECG386   File:Mcebjt.lib

*Si 175W 450V 15A 3.8MHz Power pkg:TO-3 3,2,1
.PARAM XECG2319  File:Mcebjt.lib

*Si 100W 1500V 4A 5MHz Power pkg:TO-3 3,2,1
.PARAM XECG389   File:Mcebjt.lib

*Si 50W 1500V 7A 5.56MHz Power pkg:TO-3 3,2,1
.PARAM XECG238   File:Mcebjt.lib

*Si 25W 250V 2A 8MHz Power pkg:TO-66 3,1,2
.PARAM XECG286   File:Mcebjt.lib

*Si 45W 350V 7A 2MHz Power pkg:TO-66 3,1,2
.PARAM XECG384   File:Mcebjt.lib

*Si 150W 200V 15A 30MHz Power pkg:TO-3 2,1,3
.PARAM XECG2328  File:Mcebjt.lib

*Si 300W 500V 50A 18MHz Power pkg:TO-3 2,1,3
.PARAM XECG2596  File:Mcebjt.lib

*Si 300W 800V 25A 15MHz Power pkg:TO-3 2,1,3
.PARAM XECG2598  File:Mcebjt.lib

*Si 180W 800V 12A 4.24MHz Power pkg:TO-3 2,1,3
.PARAM XECG2365  File:Mcebjt.lib

*Si 250W 800V 25A 2.94MHz Power pkg:TO-3 2,1,3
.PARAM XECG2533  File:Mcebjt.lib

*Si 10W 40V 3A 150MHz Power pkg:TO37 3,2,1
.PARAM XECG237   File:Mcebjt.lib

*Si 10W 60V 2A 200MHz Power pkg:TO-39 3,2,1
.PARAM XECG224   File:Mcebjt.lib

*Si 150W 200V 15A 20MHz Power pkg:TB-35 2,1,3
.PARAM XECG92    File:Mcebjt.lib

*Si 80W 100V 10A 3MHz Power pkg:TO-3 2,1,3
.PARAM XECG390   File:Mcebjt.lib

*Si 125W 100V 25A 3MHz Power pkg:TO-3 2,1,3
.PARAM XECG392   File:Mcebjt.lib

*Si 125W 160V 16A 2MHz Power pkg:TO-3 2,1,3
.PARAM XECG2305  File:Mcebjt.lib

*Si 100W 400V 3A 2.5MHz Power pkg:TO-3 2,1,3
.PARAM XECG394   File:Mcebjt.lib

*Si 125W 450V 8A 5.2MHz Power pkg:TO-3 2,1,3
.PARAM XECG2310  File:Mcebjt.lib

*Si 150W 450V 15A 3.8MHz Power pkg:TO-3 2,1,3
.PARAM XECG2311  File:Mcebjt.lib

*Si 125W 700V 8A 7MHz Power pkg:TO-3 2,1,3
.PARAM XECG2300  File:Mcebjt.lib

*Si 125W 700V 8A 7MHz Power pkg:TO-3 2,1,3
.PARAM XECG2318  File:Mcebjt.lib

*Si 100W 750V 5A 4MHz Power pkg:TO-3 2,1,3
.PARAM XECG2301  File:Mcebjt.lib

*Si 80W 55V 4A 7.35MHz Power pkg:TO-3 2,1,3
.PARAM XECG2330  File:Mcebjt.lib

*Si 90W 50V 15A 20MHz Power pkg:TO-3 2,1,3
.PARAM XECG2304  File:Mcebjt.lib

*Si 80W 80V 12A 20MHz Power pkg:TO-3 2,1,3
.PARAM XECG2534  File:Mcebjt.lib

*Si 150W 100V 40A 2.32MHz Power pkg:TO-3 2,1,3
.PARAM XECG2536  File:Mcebjt.lib

*Si 100W 140V 12A 15MHz Power pkg:TO-3 2,1,3
.PARAM XECG36    File:Mcebjt.lib

*Si 80W 180V 5A 6.57MHz Power pkg:TO-3 2,1,3
.PARAM XECG2307  File:Mcebjt.lib

*Si 100W 400V 12A 20MHz Power pkg:TO-3 2,1,3
.PARAM XECG2308  File:Mcebjt.lib

*Si 160W 400V 25A 20MHz Power pkg:TO-3 2,1,3
.PARAM XECG2539  File:Mcebjt.lib

*Si 100W 800V 6A 15MHz Power pkg:TO-3 2,1,3
.PARAM XECG2309  File:Mcebjt.lib

*Si 150W 800V 10A 15MHz Power pkg:TO-3 2,1,3
.PARAM XECG2348  File:Mcebjt.lib

*Si 120W 800V 5A 3MHz Power pkg:TO-3 2,1,3
.PARAM XECG2302  File:Mcebjt.lib

*Si 150W 800V 8A 5.2MHz Power pkg:TO-3 2,1,3
.PARAM XECG2324  File:Mcebjt.lib

*Si 150W 800V 10A 4.65MHz Power pkg:TO-3 2,1,3
.PARAM XECG2354  File:Mcebjt.lib

*Si 60W 400V 16A 20MHz Power pkg:TO-3 2,1,3
.PARAM XECG2538  File:Mcebjt.lib

*Si 55W 500V 15A 18MHz Power pkg:TO-3 2,1,3
.PARAM XECG2594  File:Mcebjt.lib

*Si 65W 800V 12A 15MHz Power pkg:TO-3 2,1,3
.PARAM XECG2597  File:Mcebjt.lib

*Si 60W 800V 6A 6MHz Power pkg:TO-3 2,1,3
.PARAM XECG2331  File:Mcebjt.lib

*Si 70W 800V 10A 4.65MHz Power pkg:TO-3 2,1,3
.PARAM XECG2353  File:Mcebjt.lib

*Si 50W 60V 7A 10MHz Power pkg:TO-220 2,1,3
.PARAM XECG152   File:Mcebjt.lib

*Si 50W 80V 10A 50MHz Power pkg:TO-220 2,1,3
.PARAM XECG377   File:Mcebjt.lib

*Si 50W 80V 7A .8MHz Power pkg:TO-220 2,1,3
.PARAM XECG196   File:Mcebjt.lib

*Si 15W 80V 500mA 1200MHz Power pkg:TO-220 2,1,3
.PARAM XECG2561  File:Mcebjt.lib

*Si 30W 80V 3A 15MHz Power pkg:TO-220 2,1,3
.PARAM XECG56    File:Mcebjt.lib

*Si 90W 100V 15A 3MHz Power pkg:TO-220 2,1,3
.PARAM XECG331   File:Mcebjt.lib

*Si 40W 120V 4A 4MHz Power pkg:TO-220 2,1,3
.PARAM XECG291   File:Mcebjt.lib

*Si 50W 150V 8A 85MHz Power pkg:TO-220 2,1,3
.PARAM XECG54    File:Mcebjt.lib

*Si 20W 200V 300mA 400MHz Power pkg:TO-220 2,1,3
.PARAM XECG2507  File:Mcebjt.lib

*Si 50W 200V 7A 100MHz Power pkg:TO-220 2,1,3
.PARAM XECG2579  File:Mcebjt.lib

*Si 70W 400V 12A 20MHz Power pkg:TO-220 2,1,3
.PARAM XECG2581  File:Mcebjt.lib

*Si 80W 400V 8A 4MHz Power pkg:TO-220 2,1,3
.PARAM XECG2312  File:Mcebjt.lib

*Si 100W 400V 12A 4MHz Power pkg:TO-220 2,1,3
.PARAM XECG379   File:Mcebjt.lib

*Si 50W 800V 3A 15MHz Power pkg:TO-220 2,1,3
.PARAM XECG2325  File:Mcebjt.lib

*Si 40W 450V 2A 20MHz Power pkg:TO-220 2,1,3
.PARAM XECG2313  File:Mcebjt.lib

*Si 125W 450V 8A 5.2MHz Power pkg:TO-220 2,1,3
.PARAM XECG2333  File:Mcebjt.lib

*Si 65W 750V 2.5A 4MHz Power pkg:TO-220 2,1,3
.PARAM XECG2303  File:Mcebjt.lib

*Si 25W 30V 12A 120MHz Power pkg:TO-220 2,1,3
.PARAM XECG2562  File:Mcebjt.lib

*Si 30W 50V 12A 10MHz Power pkg:TO-220 2,1,3
.PARAM XECG2566  File:Mcebjt.lib

*Si 30W 60V 10A 100MHz Power pkg:TO-220 2,1,3
.PARAM XECG2568  File:Mcebjt.lib

*Si 30W 80V 7A 20MHz Power pkg:TO-220 2,1,3
.PARAM XECG2570  File:Mcebjt.lib

*Si 10W 120V 400mA 400MHz Power pkg:TO-220 2,1,3
.PARAM XECG2574  File:Mcebjt.lib

*Si 20W 180V 2A 60MHz Power pkg:TO-220 2,1,3
.PARAM XECG2576  File:Mcebjt.lib

*Si 30W 60V 4.5A 10MHz Power pkg:TO-220 2,1,3
.PARAM XECG2578  File:Mcebjt.lib

*Si 40W 400V 12A 20MHz Power pkg:TO-220 2,1,3
.PARAM XECG2582  File:Mcebjt.lib

*Si 35W 400V 10A 20MHz Power pkg:TO-220 2,1,3
.PARAM XECG2583  File:Mcebjt.lib

*Si 40W 500V 7A 5.56MHz Power pkg:TO-220 2,1,3
.PARAM XECG2337  File:Mcebjt.lib

*Si 40W 800V 3A 8.49MHz Power pkg:TO-220 2,1,3
.PARAM XECG2339  File:Mcebjt.lib

*Si 2W 1200V 30mA 6MHz Power pkg:TO-220 2,1,3
.PARAM XECG2588  File:Mcebjt.lib

*Si 2W 1800V 15mA 6MHz Power pkg:TO-220 2,1,3
.PARAM XECG2592  File:Mcebjt.lib

*Si 2W 2100V 10mA 6MHz Power pkg:TO-220 2,1,3
.PARAM XECG2593  File:Mcebjt.lib

*Si 30W 30V 8A 120MHz Power pkg:TO-220 2,1,3
.PARAM XECG2564  File:Mcebjt.lib

*Si 40W 80V 7A 20MHz Power pkg:TO-220 2,1,3
.PARAM XECG2572  File:Mcebjt.lib

*Si 50W 400V 7A 20MHz Power pkg:TO-220 2,1,3
.PARAM XECG2580  File:Mcebjt.lib

*Si 50W 500V 5A 18MHz Power pkg:TO-220 2,1,3
.PARAM XECG2584  File:Mcebjt.lib

*Si 1.65W 800V 20mA 40MHz Power pkg:TO-220 2,1,3
.PARAM XECG2585  File:Mcebjt.lib

*Si 50W 800V 3A 15MHz Power pkg:TO-220 2,1,3
.PARAM XECG2586  File:Mcebjt.lib

*Si 1.2W 900V 50mA 6MHz Power pkg:TO-220 2,1,3
.PARAM XECG2590  File:Mcebjt.lib

*Si 1.2W 900V 20mA 6MHz Power pkg:TO-220 2,1,3
.PARAM XECG2591  File:Mcebjt.lib

*Si 10W 60V 500mA 800MHz Power pkg:TO-126 2,3,1
.PARAM XECG2511  File:Mcebjt.lib

*Si 40W 80V 4A 2MHz Power pkg:TO-126 2,3,1
.PARAM XECG184   File:Mcebjt.lib

*Si 5W 95V 400mA 1000MHz Power pkg:TO-126 2,3,1
.PARAM XECG2506  File:Mcebjt.lib

*Si 1W 160V 1.5A 140MHz Power pkg:TO-126 2,3,1
.PARAM XECG373   File:Mcebjt.lib

*Si 20.8W 300V 500mA 10MHz Power pkg:TO-126 2,3,1
.PARAM XECG157   File:Mcebjt.lib

*Si 20W 450V 500mA 20MHz Power pkg:TO-126 2,3,1
.PARAM XECG2327  File:Mcebjt.lib

*Si 5W 20V 500mA 2000MHz Power pkg:TO-126 2,3,1
.PARAM XECG2510  File:Mcebjt.lib

*Si 10W 50V 2.5A 140MHz Power pkg:TO-126 2,3,1
.PARAM XECG2517  File:Mcebjt.lib

*Si 8W 120V 300mA 400MHz Power pkg:TO-126 2,3,1
.PARAM XECG2508  File:Mcebjt.lib

*Si 10W 160V 1.5A 120MHz Power pkg:TO-126 2,3,1
.PARAM XECG2519  File:Mcebjt.lib

*Si 10W 250V 300mA 400MHz Power pkg:TO-126 2,3,1
.PARAM XECG2521  File:Mcebjt.lib

*Si 7W 300V 100mA 1500MHz Power pkg:TO-126 2,3,1
.PARAM XECG2501  File:Mcebjt.lib

*Si 1.2W 25V 2A 260MHz Power pkg:TO-126 2,3,1
.PARAM XECG2504  File:Mcebjt.lib

*Si 20W 50V 8A 180MHz Power pkg:TO-126 2,3,1
.PARAM XECG2513  File:Mcebjt.lib

*Si 20W 100V 4A 180MHz Power pkg:TO-126 2,3,1
.PARAM XECG2515  File:Mcebjt.lib

*Si 15W 45V 8A 250MHz Power pkg:TO-126 2,1,3
.PARAM XECG2522  File:Mcebjt.lib

*Si 20W 50V 8A 180MHz Power pkg:TO-126 2,1,3
.PARAM XECG2524  File:Mcebjt.lib

*Si 20W 100V 4A 180MHz Power pkg:TO-126 2,1,3
.PARAM XECG2526  File:Mcebjt.lib

*Si 15W 160V 1.5A 120MHz Power pkg:TO-126 2,1,3
.PARAM XECG2528  File:Mcebjt.lib

*Si 15W 400V 2A 60MHz Power pkg:TO-126 2,1,3
.PARAM XECG2530  File:Mcebjt.lib

*Si 12.5W 60V 3A 50MHz Power pkg:TO-126 2,1,3
.PARAM XECG186   File:Mcebjt.lib

*Si 10W 100V 2A 150MHz Power pkg:TO-126 3,2,1
.PARAM XECG49    File:Mcebjt.lib

*Si 10W 300V 500mA 75MHz Power pkg:TO-126 3,2,1
.PARAM XECG171   File:Mcebjt.lib

*Si 10W 50V 3A 150MHz Power pkg:TO-126 2,1,3
.PARAM XECG186A  File:Mcebjt.lib

*Si 10W 180V 1A 100MHz Power pkg:TO-126 3,2,1
.PARAM XECG190   File:Mcebjt.lib

*Si 250W 150V 50A 30MHz Power pkg:TO-126 1,2,3
.PARAM XECG70    File:Mcebjt.lib

*Si 60W 100V 7A 30MHz Power pkg:TO-126 1,2,3
.PARAM XECG96    File:Mcebjt.lib

*Si 50W 80V 5A 50MHz Power pkg:TO-126 1,2,3
.PARAM XECG75    File:Mcebjt.lib

*==========================================
*Zetex

*ZTX Si 1W 40V 1A 50MHz MedPwr pkg:TO-92B 1,2,3
.PARAM Q2N6715 File:Zetex.lib

*ZTX Si 1W 50V 2A 120MHz MedPwr pkg:SOT-89 2,1,3
.PARAM Q2SC2873 File:Zetex.lib

*ZTX Si 300mW 45V 200mA 150MHz GenPurp pkg:TO-18 3,2,1
.PARAM QBC107BP File:Zetex.lib

*ZTX Si 300mW 20V 200mA 150MHz GenPurp pkg:TO-18 3,2,1
.PARAM QBC108BP File:Zetex.lib

*ZTX Si 4dB 20V 50mA 150MHz LoNoise pkg:TO-18 3,2,1
.PARAM QBC109BP File:Zetex.lib

*ZTX Si 300mW 50V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC182BP File:Zetex.lib

*ZTX Si 300mW 30V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC183BP File:Zetex.lib

*ZTX Si 4dB 30V 200mA 150MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QBC184BP File:Zetex.lib

*ZTX Si 300mW 45V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC237BP File:Zetex.lib

*ZTX Si 300mW 20V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC238BP File:Zetex.lib

*ZTX Si 4dB 20V 50mA 150MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QBC239BP File:Zetex.lib

*ZTX Si 625mW 45V 800mA 100MHz MedPwr pkg:TO-92B 1,2,3
.PARAM QBC337AP File:Zetex.lib

*ZTX Si 625mW 25V 800mA 100MHz MedPwr pkg:TO-92B 1,2,3
.PARAM QBC338AP File:Zetex.lib

*ZTX Si 3dB 30V 100mA 250MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QBC413BP File:Zetex.lib

*ZTX Si 3dB 45V 100mA 250MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QBC414BP File:Zetex.lib

*ZTX Si 500mW 65V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC546BP File:Zetex.lib

*ZTX Si 500mW 45V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC547BP File:Zetex.lib

*ZTX Si 500mW 30V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC548BP File:Zetex.lib

*ZTX Si 4dB 30V 200mA 300MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QBC549BP File:Zetex.lib

*ZTX Si 3dB 45V 200mA 300MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QBC550BP File:Zetex.lib

*ZTX Si 350mW 65V 100mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC846B File:Zetex.lib

*ZTX Si 350mW 45V 100mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC847B File:Zetex.lib

*ZTX Si 350mW 30V 100mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC848B File:Zetex.lib

*ZTX Si 350mW 30V 100mA 300MHz LoNoise pkg:SOT-23 1,3,2
.PARAM QBC849B File:Zetex.lib

*ZTX Si 350mW 45V 100mA 300MHz LoNoise pkg:SOT-23 1,3,2
.PARAM QBC850B File:Zetex.lib

*ZTX Si 350mW 60V 100mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCV72 File:Zetex.lib

*ZTX Si 350mW 20V 100mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW32 File:Zetex.lib

*ZTX Si 350mW 32V 200mA 250MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW60C File:Zetex.lib

*ZTX Si 425mW 32V 800mA 100MHz MedPwr pkg:SOT-23 1,3,2
.PARAM QBCW65A File:Zetex.lib

*ZTX Si 425mW 45V 800mA 100MHz MedPwr pkg:SOT-23 1,3,2
.PARAM QBCW66F File:Zetex.lib

*ZTX Si 350mW 45V 100mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW72 File:Zetex.lib

*ZTX Si 350mW 45V 200mA 250MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCX70J File:Zetex.lib

*ZTX Si 350mW 15V 100mA 600MHz VHF/RF pkg:SOT-23 1,3,2
.PARAM QBFQ31 File:Zetex.lib

*ZTX Si 500mW 40V 1A 150MHz MedPwr pkg:TO-92B 1,2,3
.PARAM QBFS60 File:Zetex.lib

*ZTX Si 1.5W 400V 300mA 50MHz HiVolt pkg:SOT-89 2,1,3
.PARAM QFCX458 File:Zetex.lib

*ZTX Si 1.5W 25V 2A 240MHz MedPwr pkg:SOT-89 2,1,3
.PARAM QFCX649 File:Zetex.lib

*ZTX Si 350mW 15V 100mA 600MHz VHF/RF pkg:SOT-23 1,3,2
.PARAM QFMMT918 File:Zetex.lib

*ZTX Si 350mW 40V 100mA 125MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QFMMTA20 File:Zetex.lib

*ZTX Si 2W 25V 3A 150MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT649 File:Zetex.lib

*ZTX Si 2W 60V 3A 140MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT651 File:Zetex.lib

*ZTX Si 2W 300V 500mA 30MHz HiVolt pkg:SOT-223 2,1,3
.PARAM QFZT657 File:Zetex.lib

*ZTX Si 2W 400V 500mA 50MHz HiVolt pkg:SOT-223 2,1,3
.PARAM QFZT658 File:Zetex.lib

*ZTX Si 2W 15V 4A 150MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT688B File:Zetex.lib

*ZTX Si 2W 20V 3A 150MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT689B File:Zetex.lib

*ZTX Si 2W 45V 2A 150MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT690B File:Zetex.lib

*ZTX Si 2W 70V 1A 150MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT692B File:Zetex.lib

*ZTX Si 2W 120V 1A 130MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT694B File:Zetex.lib

*ZTX Si 2W 250V 500mA 70MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT696B File:Zetex.lib

*ZTX Si 500mW 40V 100mA 125MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPSA20 File:Zetex.lib

*ZTX Si 300mW 50V 100mA 350MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX107 File:Zetex.lib

*ZTX Si 300mW 50V 100mA 350MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX107B File:Zetex.lib

*ZTX Si 300mW 30V 100mA 350MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX108 File:Zetex.lib

*ZTX Si 300mW 30V 100mA 350MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX108B File:Zetex.lib

*ZTX Si 4dB 30V 100mA 350MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QZTX109 File:Zetex.lib

*ZTX Si 4dB 30V 100mA 350MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QZTX109B File:Zetex.lib

*ZTX Si 300mW 45V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX237 File:Zetex.lib

*ZTX Si 300mW 45V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX237B File:Zetex.lib

*ZTX Si 350mW 30V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX238 File:Zetex.lib

*ZTX Si 350mW 30V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX238B File:Zetex.lib

*ZTX Si 4dB 30V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX239 File:Zetex.lib

*ZTX Si 4dB 30V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX239B File:Zetex.lib

*ZTX Si 300mW 15V 500mA 600MHz HF/RF pkg:TO-92B 1,2,3
.PARAM QZTX320 File:Zetex.lib

*ZTX Si 300mW 15V 500mA 600MHz HF/RF pkg:TO-92B 1,2,3
.PARAM QZTX321 File:Zetex.lib

*ZTX Si 750mW 45V 800mA 200MHz MedPwr pkg:TO-92B 1,2,3
.PARAM QZTX337A File:Zetex.lib

*ZTX Si 750mW 25V 800mA 200MHz MedPwr pkg:TO-92B 1,2,3
.PARAM QZTX338A File:Zetex.lib

*ZTX Si 1W 45V 1A 50MHz MedPwr pkg:TO-92B 1,2,3
.PARAM QZTX450 File:Zetex.lib

*ZTX Si 1W 120V 1A 100MHz MedPwr/HiVolt pkg:TO-92B 1,2,3
.PARAM QZTX454 File:Zetex.lib

*ZTX Si 1W 140V 1A 100MHz MedPwr/HiVolt pkg:TO-92B 1,2,3
.PARAM QZTX455 File:Zetex.lib

*ZTX Si 1W 400V 500mA HiVolt pkg:TO-92B 1,2,3
.PARAM QZTX458 File:Zetex.lib

*ZTX Si 1W 25V 2A 150MHz SuperE-line pkg:TO-92B 1,2,3
.PARAM QZTX649 File:Zetex.lib

*ZTX Si 1W 45V 2A 140MHz SuperE-line pkg:TO-92B 1,2,3
.PARAM QZTX650 File:Zetex.lib

*ZTX Si 1W 60V 2A 140MHz SuperE-line pkg:TO-92B 1,2,3
.PARAM QZTX651 File:Zetex.lib

*ZTX Si 1W 300V 500mA HiVolt pkg:TO-92B 1,2,3
.PARAM QZTX657 File:Zetex.lib

*ZTX Si 1W 400V 500mA HiVolt pkg:TO-92B 1,2,3
.PARAM QZTX658 File:Zetex.lib

*ZTX Si 1W pkg:TO-92B 1,2,3
.PARAM QZTX688B File:Zetex.lib

*ZTX Si 1W 20V 2A 150MHz MedPwr/HiGain pkg:TO-92B 1,2,3
.PARAM QZTX689B File:Zetex.lib

*ZTX Si 1W 45V 2A 150MHz MedPwr/HiGain pkg:TO-92B 1,2,3
.PARAM QZTX690B File:Zetex.lib

*ZTX Si 1W 70V 1A 150MHz MedPwr/HiGain pkg:TO-92B 1,2,3
.PARAM QZTX692B File:Zetex.lib

*ZTX Si 1W 120V 500mA 150MHz MedPwr/HiGain pkg:TO-92B 1,2,3
.PARAM QZTX694B File:Zetex.lib

*ZTX Si 1W pkg:TO-92B 1,2,3
.PARAM QZTX696B File:Zetex.lib

*==============================================
*Motorola

*MOT Si 350mW 15V 1.3GHz HiFreq pkg:SOT-23 1,3,2 
.PARAM XBFS17 File:Motbjt.lib

*MOT Si 330mW 10V 80mA 8GHz HiFreq pkg:SOT-23 1,3,2
.PARAM XMMBR571 File:Motbjt.lib

*MOT Si 300mW 15V 30mA 2.5GHz HiFreq pkg:SOT-23 1,3,2 
.PARAM XMMBR901 File:Motbjt.lib

*MOT Si 150mW 5V 5mA 1GHz HiFreq pkg:SOT-23 1,3,2 
.PARAM XMMBR931 File:Motbjt.lib

*MOT Si 250mW 10V 50mA 8GHz LoNoise HiFreq pkg:SOT-23 1,3,2 
.PARAM XMMBR941 File:Motbjt.lib

*MOT Si 322mW 10V 100mA 8GHz LoNoise HiFreq pkg:SOT-23 1,3,2 
.PARAM XMMBR951 File:Motbjt.lib

*MOT Si 580mW 10V 80mA 8GHz HiFreq pkg:SOT-143 1,3,2 
.PARAM XMRF5711 File:Motbjt.lib

*MOT Si 1.88W 15V 200mA 1GHz HiFreq pkg:SMD8A 2,6,1 
.PARAM XMRF5812 File:Motbjt.lib

*MOT Si 300mW 15V 30mA 2.5GHz HiFreq pkg:SOT-143 1,3,2 
.PARAM XMRF9011 File:Motbjt.lib

*MOT Si 50mW 8V 2mA 1GHz HiFreq pkg:SOT-143 1,3,2 
.PARAM XMRF9331 File:Motbjt.lib

*MOT Si 250mW 10V 50mA 8GHz LoNoise HiFreq pkg:SOT-143 1,3,2 
.PARAM XMRF9411 File:Motbjt.lib

*MOT Si 188mW 10V 50mA 8GHz LoNoise HiFreq pkg:SOT-323 1,3,2 
.PARAM XMRF947 File:Motbjt.lib

*MOT Si 322mW 10V 100mA 8GHz LoNoise HiFreq pkg:SOT-143 1,3,2 
.PARAM XMRF9511 File:Motbjt.lib

*=======================================
*Harris Semiconductor

*HAR Si 600mW 12V 40mA 8GHz UHFArray pkg:SO-16 (A:1,2,3)(B:5,4,3)(C:8,6,7)(D:11,9,10)(E:14,12,13)
.PARAM XHFA3046 File:Harris.lib

*HAR Si 600mW 12V 40mA 8GHz UHFArray pkg:SO-16 (A:3,1,2)(B:6,5,4)(C:9,8,7)(D:12,11,10)(E:15,14,13) 
.PARAM XHFA3096 File:Harris.lib

*HAR Si 600mW 12V 40mA 8GHz UHFArray pkg:SO-16 (A:2,4,3)(B:6,8,7)(C:11,9,10)(D:12,14,13)(E:1,15,16) 
.PARAM XHFA3127 File:Harris.lib

*=======================================
*National Semiconductor

*NS Si 625mW 40V 1A 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QPN2222A/NS File:Nsbjt.lib

*NS Si 350mW 40V 1A 300MHz GenPurp alias:QPN2222A/NS pkg:SOT-23 1,3,2
.PARAM AMMBT2222A/NS

*NS Si 1W 40V 1A 300MHz GenPurp alias:QPN2222A/NS pkg:SOT-223 2,1,3
.PARAM APZT2222A/NS

*NS Si 625mW 40V 1A 300MHz GenPurp alias:QPN2222A/NS pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM AMMPQ2222/NS

*NS Si 350mW 15V 200mA Switching pkg:TO-92B 1,2,3
.PARAM QPN2369A/NS File:Nsbjt.lib

*NS Si 225mW 15V 200mA Switching alias:QPN2369A/NS pkg:SOT-23 1,3,2
.PARAM AMMBT2369A/NS

*NS Si 1W 15V 200mA Switching alias:QPN2369A/NS pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM AMMPQ2369A/NS

*NS Si 625mW 40V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N3904/NS File:Nsbjt.lib

*NS Si 350mW 40V 200mA 300MHz GenPurp alias:Q2N3904/NS pkg:SOT-23 1,3,2
.PARAM AMMBT3904/NS

*NS Si 1W 40V 200mA 300MHz GenPurp alias:Q2N3904/NS pkg:SOT-223 2,1,3
.PARAM APZT3904/NS

*NS Si 1W 40V 200mA 300MHz GenPurp alias:Q2N3904/NS pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM AMMPQ3904/NS

*NS Si 625mW 30V 100mA 50MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5088/NS File:Nsbjt.lib

*NS Si 350mW 30V 100mA 50MHz GenPurp alias:Q2N5088/NS pkg:SOT-23 1,3,2
.PARAM AMMBT5088/NS

*NS Si 350mW 12V 50mA 900MHz RF pkg:TO-92B 1,2,3
.PARAM QMPS5179/NS File:Nsbjt.lib

*NS Si 225mW 12V 50mA 900MHz RF alias:QMPS5179/NS pkg:SOT-23 1,3,2
.PARAM AMMBT5179/NS

*NS Si 625mW 160V 200mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5551/NS File:Nsbjt.lib

*NS Si 350mW 160V 200mA 200MHz GenPurp alias:Q2N5551/NS pkg:SOT-23 1,3,2
.PARAM AMMBT5551/NS

*NS Si 625mW 80V 500mA 100MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPSA06/NS File:Nsbjt.lib

*NS Si 350mW 80V 500mA 100MHz GenPurp alias:QMPSA06/NS pkg:SOT-23 1,3,2
.PARAM AMMBTA06/NS

*NS Si 1W 80V 500mA 100MHz GenPurp alias:QMPSA06/NS pkg:SOT-223 2,1,3
.PARAM APZTA06/NS

*NS Si 625mW 300V 200mA 50MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QMPSA42/NS File:Nsbjt.lib

*NS Si 350mW 300V 200mA 50MHz HiVolt alias:QMPSA42/NS pkg:SOT-23 1,3,2
.PARAM AMMBTA42/NS

*NS Si 350mW 300V 200mA 50MHz HiVolt alias:QMPSA42/NS pkg:SOT-223 2,1,3
.PARAM APZTA42/NS

*NS Si 350mW 25V 50mA 650MHz RF pkg:TO-92B 1,2,3
.PARAM QMPSH10/NS File:Nsbjt.lib

*NS Si 225mW 25V 50mA 650MHz RF alias:QMPSH10/NS pkg:SOT-23 1,3,2
.PARAM AMMBTH10/NS

*NS Si 350mW 40V 800mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBSR14/NS File:Nsbjt.lib

*NS Si 350mW 40V 200mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBSR17A/NS File:Nsbjt.lib

*NS Si 350mW 80V 200mA 60MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBSS64/NS File:Nsbjt.lib

*NS Si 225mW 12V 200mA 400MHz Switching pkg:SOT-23 1,3,2
.PARAM QBSV52/NS File:Nsbjt.lib
