*==============================================
*P-EMOS 3T pinout: D,G,S
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*==============================================
*MicroCode Engineering

*Default P-Channel MOSFET
.PARAM MPMOS~ File:Mcemos.lib

*100V 4A 1.2 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9510 File:Mcemos.lib

*100V 6.8A .6 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9520 File:Mcemos.lib

*100V 19A .2 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9540 File:Mcemos.lib

*200V 1.8A 3 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9610 File:Mcemos.lib

*200V 3.5A 1.5 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9620 File:Mcemos.lib

*200V 6.5A .8 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9630 File:Mcemos.lib

*200V 11A .5 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9640 File:Mcemos.lib

*60V 6.7A .5 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9Z14 File:Mcemos.lib

*60V 11A .28 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9Z24 File:Mcemos.lib

*60V 18A .14 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9Z34 File:Mcemos.lib

*30V 4A 0.095ohm Power MOSFET pkg:TSOP-6 1,3,4
.PARAM XSI3455DV File:Mcemos.lib

*30V 4A 0.085ohm Power MOSFET pkg:TSOP-6 1,3,4
.PARAM XSI3457DV File:Mcemos.lib

*30V 6A 0.017ohm Power MOSFET pkg:SMD8B 1,4,6
.PARAM XSI6415DQ File:Mcemos.lib

*60V 3A 0.112ohm Power MOSFET pkg:SMD8B 1,4,6
.PARAM XSI6459DQ File:Mcemos.lib

*30V 4A 0.059ohm Dual Power MOSFET pkg:SMD8B (A:1,4,3)(B:8,5,6)
.PARAM XSI6933DQ File:Mcemos.lib

*30V 4A 0.037ohm Triple Power MOSFET pkg:SMD28 (A:1,4,26)(B:6,9,21)(C:11,14,16)
.PARAM XSI6332DQ File:Mcemos.lib

*30V 11A 0.013ohm Power MOSFET pkg:SMD8A 5,4,1
.PARAM XSI4425DY File:Mcemos.lib

*30V 6A 0.031ohm Dual Power MOSFET pkg:SMD8A (A:8,2,1)(B:6,4,3)
.PARAM XSI4925DY File:Mcemos.lib

*60V 3A 0.112ohm Dual Power MOSFET pkg:SMD8A (A:8,2,1)(B:6,4,3)
.PARAM XSI4948EY File:Mcemos.lib

*12V 8A 0.022ohm Power MOSFET pkg:SMD8A 8,4,1
.PARAM XSI9424DY File:Mcemos.lib

*12V 5A 0.045ohm Power MOSFET pkg:SMD8A (A:8,2,1)(B:6,4,3)
.PARAM XSI9934DY File:Mcemos.lib

*20V 6A 0.038ohm Reduced Power MOSFET pkg:SMD8A 8,4,1
.PARAM XSI9803DY File:Mcemos.lib

*12V 3A .16ohm Dual Power MOSFET pkg:SMD8A (A:8,2,1)(B:6,4,3)
.PARAM XMMDF2P01HD File:Mcemos.lib

*25V 2A .19ohm Dual Power MOSFET pkg:SMD8A (A:8,2,1)(B:6,4,3)
.PARAM XMMDF2P02E File:Mcemos.lib

*20V 3A .118ohm Dual Power MOSFET pkg:SMD8A (A:8,2,1)(B:6,4,3)
.PARAM XMMDF2P02HD File:Mcemos.lib

*30V 3A .17ohm Dual Power MOSFET pkg:SMD8A (A:8,2,1)(B:6,4,3)
.PARAM XMMDF2P03HD File:Mcemos.lib

*60V 1A .3ohm Power MOSFET pkg:SOT-223 2,3,1
.PARAM XMMFT2955E File:Mcemos.lib

*20V 2A .19ohm Power MOSFET pkg:SMD8A 8,4,2
.PARAM XMMSF2P02E File:Mcemos.lib

*20V 6A .06ohm Power MOSFET pkg:SMD8A 8,4,2
.PARAM XMMSF3P02HD File:Mcemos.lib

*30V 5A .8ohm Power MOSFET pkg:SMD8A 8,4,2
.PARAM XMMSF3P03HD File:Mcemos.lib

*12V 5A .073ohm Power MOSFET pkg:SMD8A 8,4,2
.PARAM XMMSF4P01HD File:Mcemos.lib

*500V 2A 4.5ohm Power MOSFET pkg:D2PAK 1,2,3
.PARAM XMTB2P50E File:Mcemos.lib

*60V 23A .093ohm Power MOSFET pkg:D2PAK 1,2,3
.PARAM XMTB23P06V File:Mcemos.lib

*60V 30A .067ohm Power MOSFET pkg:D2PAK 1,2,3
.PARAM XMTB30P06V File:Mcemos.lib

*30V 50A 20.9ohm Power MOSFET pkg:D2PAK 1,2,3
.PARAM XMTB50P03HDL File:Mcemos.lib

*500V 1A 12ohm Power MOSFET pkg:DPAK 1,2,3
.PARAM XMTD1P50E File:Mcemos.lib

*60V 5A .34ohm Power MOSFET pkg:DPAK 1,2,3
.PARAM XMTD5P06V File:Mcemos.lib

*100V 6A .56ohm Power MOSFET pkg:DPAK 1,2,3
.PARAM XMTD6P10E File:Mcemos.lib

*30V 19A .12ohm Power MOSFET pkg:DPAK 1,2,3
.PARAM XMTD20P03HDL File:Mcemos.lib

*60V 15A .143ohm Power MOSFET pkg:DPAK 1,2,3
.PARAM XMTD20P06HDL File:Mcemos.lib

*60V 12A .185ohm Power MOSFET pkg:DPAK 1,2,3
.PARAM XMTD2955V File:Mcemos.lib

*500V 2A 4.5ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XMTP2P50E File:Mcemos.lib

*60V 5A .34ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XMTP5P06V File:Mcemos.lib

*200V 6A .81ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XMTP6P20E File:Mcemos.lib

*100V 12A .3ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XMTP12P10 File:Mcemos.lib

*60V 23A .093ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XMTP23P06V File:Mcemos.lib

*60V 30A .067ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XMTP30P06V File:Mcemos.lib

*30V 50A .02ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XMTP50P03HDL File:Mcemos.lib

*60V 12A .185ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XMTP2955V File:Mcemos.lib

*20V 2A .12ohm Power MOSFET pkg:SMD8B 8,4,1
.PARAM XMTSF1P02HD File:Mcemos.lib

*20V 2A .09ohm Power MOSFET pkg:SMD8B 8,4,1
.PARAM XMTSF2P02HD File:Mcemos.lib

*20V 2A .48ohm Power MOSFET pkg:SMD8A(A:8,1,2)(B:6,3,4)
.PARAM XIRF7202  File:Mcemos.lib

*20V 4A .279ohm Power MOSFET pkg:SMD8A(A:8,1,2)(B:6,3,4)
.PARAM XIRF7203  File:Mcemos.lib

*20V 5A .226ohm Power MOSFET pkg:SMD8A(A:8,1,2)(B:6,3,4)
.PARAM XIRF7204  File:Mcemos.lib

*20V 5A .226ohm Power MOSFET pkg:SMD8A(A:8,1,2)(B:6,3,4)
.PARAM XIRF7205  File:Mcemos.lib

*20V 2A .522ohm Power MOSFET pkg:SMD8A(A:8,1,2)(B:6,3,4)
.PARAM XIRF7104  File:Mcemos.lib

*60V 2A .667ohm Power MOSFET pkg:SOT-223 2,1,3
.PARAM XIRFL9014 File:Mcemos.lib

*100V 1A 1.09ohm Power MOSFET pkg:SOT-223 2,1,3
.PARAM XIRFL9110 File:Mcemos.lib

*60V 5A .235ohm Power MOSFET pkg:DPAK 2,1,3
.PARAM XIRFR9014 File:Mcemos.lib

*60V 9A .136ohm Power MOSFET pkg:DPAK 2,1,3
.PARAM XIRFR9024 File:Mcemos.lib

*100V 3A .387ohm Power MOSFET pkg:DPAK 2,1,3
.PARAM XIRFR9110 File:Mcemos.lib

*100V 6A .214ohm Power MOSFET pkg:DPAK 2,1,3
.PARAM XIRFR9120 File:Mcemos.lib

*200V 2A .632ohm Power MOSFET pkg:DPAK 2,1,3
.PARAM XIRFR9210 File:Mcemos.lib

*200V 4A .333ohm Power MOSFET pkg:DPAK 2,1,3
.PARAM XIRFR9220 File:Mcemos.lib

*60V 7A .179ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9Z14S File:Mcemos.lib

*60V 11A .109ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9Z24S File:Mcemos.lib

*60V 18A .0667ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9Z34S File:Mcemos.lib

*100V 4A .3ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9510S File:Mcemos.lib

*100V 7A .176ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9520S File:Mcemos.lib

*100V 12A .1ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9530S File:Mcemos.lib

*100V 19A .0632ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9540S File:Mcemos.lib

*200V 2A .667ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9610S File:Mcemos.lib

*200V 4A .343ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9620S File:Mcemos.lib

*200V 6A .185ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9630S File:Mcemos.lib

*200V 11A .109ohm Power MOSFET pkg:D2PAK 2,1,3
.PARAM XIRF9640S File:Mcemos.lib

*60V 5A .226ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9Z14G File:Mcemos.lib

*60V 8A .141ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9Z24G File:Mcemos.lib

*60V 12A .1ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9Z34G File:Mcemos.lib

*100V 5A .231ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9520G File:Mcemos.lib

*100V 8A .156ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9530G File:Mcemos.lib

*100V 11A .109ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9540G File:Mcemos.lib

*200V 3A .4ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9620G File:Mcemos.lib

*200V 4A .279ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9630G File:Mcemos.lib

*200V 6A .197ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9640G File:Mcemos.lib

*100V 15A .08ohm Power MOSFET pkg:TO-247 2,3,1
.PARAM XIRFIP9140 File:Mcemos.lib

*200V 9A .135ohm Power MOSFET pkg:TO-247 2,3,1
.PARAM XIRFIP9240 File:Mcemos.lib

*60V 1A 1.09ohm Power MOSFET pkg:DIP4 1,4,3
.PARAM XIRFD9014 File:Mcemos.lib

*60V 2A .75ohm Power MOSFET pkg:DIP4 1,4,3
.PARAM XIRFD9024 File:Mcemos.lib

*100V 1A 1.71ohm Power MOSFET pkg:DIP4 1,4,3
.PARAM XIRFD9110 File:Mcemos.lib

*100V 1A 1.2ohm Power MOSFET pkg:DIP4 1,4,3
.PARAM XIRFD9120 File:Mcemos.lib

*200V 0A 3ohm Power MOSFET pkg:DIP4 1,4,3
.PARAM XIRFD9210 File:Mcemos.lib

*200V 1A 2.14ohm Power MOSFET pkg:DIP4 1,4,3
.PARAM XIRFD9220 File:Mcemos.lib

*60V 5A .235ohm Power MOSFET pkg:TO-251 2,3,1
.PARAM XIRFU9014 File:Mcemos.lib

*60V 9A .136ohm Power MOSFET pkg:TO-251 2,3,1
.PARAM XIRFU9024 File:Mcemos.lib

*100V 3A .387ohm Power MOSFET pkg:TO-251 2,3,1
.PARAM XIRFU9110 File:Mcemos.lib

*100V 6A .214ohm Power MOSFET pkg:TO-251 2,3,1
.PARAM XIRFU9120 File:Mcemos.lib

*200V 2A .632ohm Power MOSFET pkg:TO-251 2,3,1
.PARAM XIRFU9210 File:Mcemos.lib

*200V 4A .333ohm Power MOSFET pkg:TO-251 2,3,1
.PARAM XIRFU9220 File:Mcemos.lib

*100V 21A .0571ohm Power MOSFET pkg:TO-247 2,3,1
.PARAM XIRFP9140 File:Mcemos.lib

*200V 12A .1ohm Power MOSFET pkg:TO-247 2,3,1
.PARAM XIRFP9240 File:Mcemos.lib

*100V 19A .15ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9140  File:Mcemos.lib

*80V 19A .15ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9141  File:Mcemos.lib

*100V 15A .15ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9142  File:Mcemos.lib

*80V 15A .15ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9143  File:Mcemos.lib

*200V 6A .5ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9230  File:Mcemos.lib

*150V 6A .5ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9231  File:Mcemos.lib

*200V 6A .5ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9232  File:Mcemos.lib

*150V 6A .5ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9233  File:Mcemos.lib

*200V 11A .35ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9240  File:Mcemos.lib

*150V 11A .35ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9241  File:Mcemos.lib

*200V 9A .35ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9242  File:Mcemos.lib

*150V 9A .35ohm Power MOSFET pkg:TO-3 3,1,2
.PARAM XIRF9243  File:Mcemos.lib

*80V 3A 1ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9511  File:Mcemos.lib

*100V 2A 1ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9512  File:Mcemos.lib

*80V 2A 1ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9513  File:Mcemos.lib

*80V 12A .25ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9531  File:Mcemos.lib

*100V 10A .25ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9532  File:Mcemos.lib

*80V 10A .25ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9533  File:Mcemos.lib

*100V 12A .25ohm Power MOSFET pkg:TO262AA 2,1,3
.PARAM XRF1S9530 File:Mcemos.lib

*100V 12A .25ohm Power MOSFET pkg:TO263AB 4,1,3
.PARAM XRF1S9530SM File:Mcemos.lib

*80V 19A .15ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9541  File:Mcemos.lib

*100V 15A .15ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9542  File:Mcemos.lib

*80V 15A .15ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9543  File:Mcemos.lib

*100V 19A .15ohm Power MOSFET pkg:TO262AA 2,1,3
.PARAM XRF1S9540 File:Mcemos.lib

*100V 19A .15ohm Power MOSFET pkg:TO263AB 4,1,3
.PARAM XRF1S9540SM File:Mcemos.lib

*150V 11A .35ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9641  File:Mcemos.lib

*200V 9A .35ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9642  File:Mcemos.lib

*150V 9A .35ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XIRF9643  File:Mcemos.lib

*200V 11A .35ohm Power MOSFET pkg:TO262AA 2,1,3
.PARAM XRF1S9640 File:Mcemos.lib

*200V 11A .35ohm Power MOSFET pkg:TO263AB 4,1,3
.PARAM XRF1S9640SM File:Mcemos.lib

*80V 1A 1ohm Power MOSFET pkg:DIP4 3,1,2
.PARAM XIRFD9113 File:Mcemos.lib

*150V 12A .38ohm Power MOSFET pkg:TO-247 2,1,3
.PARAM XIRFP9241 File:Mcemos.lib

*200V 10A .38ohm Power MOSFET pkg:TO-247 2,1,3
.PARAM XIRFP9242 File:Mcemos.lib

*150V 10A .38ohm Power MOSFET pkg:TO-247 2,1,3
.PARAM XIRFP9243 File:Mcemos.lib

*100V 3A 1.2ohm Power MOSFET pkg:TO251AA 2,1,3
.PARAM XIRFU9110 File:Mcemos.lib

*100V 6A .6ohm Power MOSFET pkg:TO251AA 2,1,3
.PARAM XIRFU9120 File:Mcemos.lib

*200V 4A 1.5ohm Power MOSFET pkg:TO251AA 2,1,3
.PARAM XIRFU9220 File:Mcemos.lib

*50V 30A .065ohm Power MOSFET pkg:TO-247 2,1,3
.PARAM XRFG30P05 File:Mcemos.lib

*50V 30A .065ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XRFP30P05 File:Mcemos.lib

*50V 30A .065ohm Power MOSFET pkg:TO262AA 2,1,3
.PARAM XRF1S30P05 File:Mcemos.lib

*50V 30A .065ohm Power MOSFET pkg:TO263AB 4,1,3
.PARAM XRF1S30P05SM File:Mcemos.lib

*60V 30A .065ohm Power MOSFET pkg:TO-247 2,1,3
.PARAM XRFG30P06 File:Mcemos.lib

*60V 30A .065ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XRFP30P06 File:Mcemos.lib

*60V 30A .065ohm Power MOSFET pkg:TO262AA 2,1,3
.PARAM XRF1S30P06 File:Mcemos.lib

*60V 30A .065ohm Power MOSFET pkg:TO263AB 4,1,3
.PARAM XRF1S30P06SM File:Mcemos.lib

*30V 60A .027ohm Power MOSFET pkg:TO-247 2,1,3
.PARAM XRFG60P03 File:Mcemos.lib

*30V 60A .027ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XRFP60P03 File:Mcemos.lib

*30V 60A .027ohm Power MOSFET pkg:TO262AA 2,1,3
.PARAM XRF1S60P03 File:Mcemos.lib

*30V 60A .027ohm Power MOSFET pkg:TO263AB 4,1,3
.PARAM XRF1S60P03SM File:Mcemos.lib

*50V 15A .15ohm Power MOSFET pkg:TO251AA 2,1,3
.PARAM XRFD15P05 File:Mcemos.lib

*50V 15A .15ohm Power MOSFET pkg:TO252AA 1,2,3
.PARAM XRFD15P05SM File:Mcemos.lib

*50V 15A .15ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XRFP15P05 File:Mcemos.lib

*60V 15A .15ohm Power MOSFET pkg:TO251AA 2,1,3
.PARAM XRFD15P06 File:Mcemos.lib

*60V 15A .15ohm Power MOSFET pkg:TO252AA 1,2,3
.PARAM XRFD15P06SM File:Mcemos.lib

*60V 15A .15ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XRFP15P06 File:Mcemos.lib

*60V 8A .3ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XRFP8P06E File:Mcemos.lib

*60V 8A .3ohm Power MOSFET pkg:TO252AA 1,2,3
.PARAM XRFD8P06ESM File:Mcemos.lib

*60V 8A .3ohm Power MOSFET pkg:TO251AA 2,1,3
.PARAM XRFD8P06E File:Mcemos.lib

*60V 8A .3ohm Power MOSFET pkg:TO251AA 2,1,3
.PARAM XRFD8P06LE File:Mcemos.lib

*60V 8A .3ohm Power MOSFET pkg:TO252AA 1,2,3
.PARAM XRFD8P06LESM File:Mcemos.lib

*60V 8A .3ohm Power MOSFET pkg:TO-220 2,1,3
.PARAM XRFP8P06LE File:Mcemos.lib

*60V 25A .03ohm Power MOSFET pkg:TO254AA 1,3,2
.PARAM XRFF60P06 File:Mcemos.lib

*50V 60A .03ohm Power MOSFET pkg:TO-247 2,1,3
.PARAM XRFG60P05E File:Mcemos.lib

*60V 60A .03ohm Power MOSFET pkg:TO-247 2,1,3
.PARAM XRFG60P06E File:Mcemos.lib

*60V 1A .215ohm Power MOSFET pkg:SOT223 4,1,3
.PARAM XRFT1P06E File:Mcemos.lib

*==============================================
*Harris Semiconductor

*HAR 100V 12A .3 ohm HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9530 File:Harris.lib

*==============================================
*Zetex

*ZTX 60V 280mA pkg:TO-92B
.PARAM XZVP2106 File:Zetex.lib

*ZTX 60V 450mA pkg:SOT-223
.PARAM XZVP2106G File:Zetex.lib

*ZTX 60V 160mA pkg:TO-92B
.PARAM XZVP3306 File:Zetex.lib

*==============================================
*Temic Semiconductors

*Tem 20V 3.3A pkg:TSOP-6
.PARAM XSi3441DV File:Siliconx.lib

*Tem 30V 5.8A pkg:SMD8A 6,4,2
.PARAM XSi4431DY File:Siliconx.lib

*Tem 30V 8A pkg:SMD8A 6,4,2
.PARAM XSi4435DY File:Siliconx.lib

*Tem Dual 30V 3.5A pkg:SMD8A (A:7,2,1)(B:5,4,3)
.PARAM XSi4947DY File:Siliconx.lib

*Tem Dual 30V 4.9A pkg:SMD8A (A:7,2,1)(B:5,4,3)
.PARAM XSi4953DY File:Siliconx.lib

*Tem 12V 4A pkg:SMD8B 5,4,2
.PARAM XSi6433DQ File:Siliconx.lib

*Tem 30V 4.5A pkg:SMD8B 5,4,2
.PARAM XSi6435DQ File:Siliconx.lib

*Tem 20V 3.2A pkg:SMD8B 5,4,2
.PARAM XSi6447DQ File:Siliconx.lib

*Tem Dual 12V 2.5A pkg:SMD8B (A:1,4,3)(B:8,5,6)
.PARAM XSi6943DQ File:Siliconx.lib

*Tem Dual 30V 4.9A pkg:SMD8A (A:7,2,1)(B:5,4,3)
.PARAM XSi6953DQ File:Siliconx.lib

*Tem Dual 30V 2.5A pkg:SMD8B (A:1,4,3)(B:8,5,6)
.PARAM XSi6955DQ File:Siliconx.lib

*Tem 12V 6.4A pkg:SMD8A 6,4,2
.PARAM XSi9434DY File:Siliconx.lib

*Tem Dual 20V 3.4A pkg:SMD8A (A:7,2,1)(B:5,4,3)
.PARAM XSi9933DY File:Siliconx.lib

*Tem Dual 20V 3.5A pkg:SMD8A (A:7,2,1)(B:5,4,3)
.PARAM XSi9947DY File:Siliconx.lib

*Tem 60V 65A pkg:TO-220 2,1,3
.PARAM XSUP65P06-20 File:Siliconx.lib
