*==============================================
*PJFET Pinout: 1=D, 2=G, 3=S
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*Default P-Ch J-FET pkg:TO-92 2,1,3
.PARAM JPJFET~ File:Mcejfets.lib

*Motorola Dep-Mode 20V 20mA 35.3ohm pkg:TO-92 2,1,3
.PARAM J2N5460 File:Mcejfets.lib

*pkg: TO-18 2,1,3
.PARAM J2N2608 File:Mcejfets.lib

*pkg: TO-18 3,2,1
.PARAM J2N2609 File:Mcejfets.lib

*pkg: TO-18 3,2,1
.PARAM J2N4381 File:Mcejfets.lib

*pkg: TO-18 
.PARAM J2N5018 File:Mcejfets.lib

*pkg: TO-18 
.PARAM J2N5019 File:Mcejfets.lib

*pkg: TO-18 
.PARAM J2N5020 File:Mcejfets.lib

*pkg: TO-18 
.PARAM J2N5021 File:Mcejfets.lib

*pkg: TO-18 
.PARAM J2N5114 File:Mcejfets.lib

*pkg: TO-18 
.PARAM J2N5115 File:Mcejfets.lib

*pkg: TO-18 
.PARAM J2N5116 File:Mcejfets.lib

