*==============================================
*PNP Trans pinout: C,B,E
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*========================================
*MicroCode Engineering

*Default PNP BJT pkg:TO-92B 1,2,3
.PARAM QPNP~ File:Mcebjt.lib

*Si 600mW 60V 600mA 300MHz pkg:TO-5 3,2,1
.PARAM Q2N2905A File:Mcebjt.lib

*Si 1.8W 60V 600mA 200MHz pkg:TO-18 3,2,1
.PARAM Q2N2907A File:Mcebjt.lib

*Si 360mW 60V 200mA 340MHz pkg:TO-18 3,2,1
.PARAM Q2N3251A File:Mcebjt.lib

*Si 1W 40V 1A 200MHz pkg:TO-5 3,2,1
.PARAM Q2N3467 File:Mcebjt.lib

*Si 1W 50V 1A 180MHz pkg:TO-5 3,2,1
.PARAM Q2N3468 File:Mcebjt.lib

*Si 360mW 60V 50mA 300MHz pkg:TO-18 3,2,1
.PARAM Q2N3799 File:Mcebjt.lib

*Si 310mW 40V 200mA 200MHz pkg:TO-92B 1,2,3
.PARAM Q2N3905 File:Mcebjt.lib

*Si 625mW 40V 200mA 250MHz pkg:TO-92B 1,2,3
.PARAM Q2N3906 File:Mcebjt.lib

*Si 1W 40V 200mA 250MHz alias:Q2N3906 pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM AMMPQ3906

*Si 1W 40V 200mA 250MHz alias:Q2N3906 pkg:SOT-223 2,1,3
.PARAM APZT3906

*Si 360mW 45V 200mA 300MHz pkg:TO-18 3,2,1
.PARAM Q2N3964 File:Mcebjt.lib

*Si 310mW 40V 600mA 150MHz pkg:TO-92B 1,2,3
.PARAM Q2N4402 File:Mcebjt.lib

*Si 625mW 40V 600mA 250MHz pkg:TO-92B 1,2,3
.PARAM Q2N4403 File:Mcebjt.lib

*Si 625mW 50V 50mA 400MHz pkg:TO-92B 1,2,3
.PARAM Q2N5087 File:Mcebjt.lib

*Si 625mW 150V 600mA 300MHz pkg:TO-92B 1,2,3
.PARAM Q2N5401 File:Mcebjt.lib

*Si 500mW 300V 500mA 300MHz pkg:TO-18 3,2,1
.PARAM Q2N6433 File:Mcebjt.lib

*Si 625mW 350V 500mA 84MHz pkg:TO-92B 1,2,3
.PARAM Q2N6520 File:Mcebjt.lib

*Si 1.5W 300V 100mA 363MHz pkg:SOT-223 2,1,3
.PARAM QBF721 File:Mcebjt.lib

*Si 1.5W 300V 1A 30MHz pkg:SOT-223 2,1,3
.PARAM QBSP16 File:Mcebjt.lib

*Si 35W 350V 2A HV AF PwrAmp HiSpeedSw pkg:TO-66 3,1,2
.PARAM XECG38 File:Mcebjt.lib

*Si 250W 250V 16A GenPurp HiPwrAmp pkg:TO-3 3,1,2
.PARAM XECG68 File:Mcebjt.lib

*Si 200W 250V 10A HiPwr LinearAmp pkg:TO-3 3,1,2
.PARAM XECG88 File:Mcebjt.lib

*Si 10W 80V 2A AF Driver PwrAmp pkg:TO-202
.PARAM XECG189 File:Mcebjt.lib

*Si 1W 300V 500mA HV AF Amp VideoOut pkg:TO-202
.PARAM XECG240 File:Mcebjt.lib

*Si 25W 150V 2A VertDefl AudioAmp pkg:TO-220 2,1,3
.PARAM XECG398 File:Mcebjt.lib

*Si 225mW 35V 150mA 300MHz pkg:SOT-23 1,3,2
.PARAM QMMBT404A File:Mcebjt.lib

*Si 300mW 60V 600mA 300MHz pkg:SOT-23 1,3,2
.PARAM QMMBT2907A File:Mcebjt.lib

*Si 300mW 12V 80mA 600MHz pkg:SOT-23 1,3,2
.PARAM QMMBT3640 File:Mcebjt.lib

*Si 300mW 40V 200mA 300MHz pkg:SOT-23 1,3,2
.PARAM QMMBT3906 File:Mcebjt.lib

*Si 300mW 40V 600mA 250MHz pkg:SOT-23 1,3,2
.PARAM QMMBT4403 File:Mcebjt.lib

*Si 225mW 50V 50mA 100MHz pkg:SOT-23 1,3,2
.PARAM QMMBT5087 File:Mcebjt.lib

*Si 225mW 150V 500mA 160MHz pkg:SOT-23 1,3,2
.PARAM QMMBT5401 File:Mcebjt.lib

*Si 225mW 350V 500mA 160MHz pkg:SOT-23 1,3,2
.PARAM QMMBT6520 File:Mcebjt.lib

*Si 225mW 80V 500mA 160MHz pkg:SOT-23 1,3,2
.PARAM QMMBT8599 File:Mcebjt.lib

*Si 225mW 80V 500mA 160MHz pkg:SOT-23 1,3,2
.PARAM QMMBTA56 File:Mcebjt.lib

*Si 225mW 300V 500mA 80MHz pkg:SOT-23 1,3,2
.PARAM QMMBTA92 File:Mcebjt.lib

*Si 625mW 35V 150mA 10MHz pkg:TO-92B 1,2,3
.PARAM QMPS404A File:Mcebjt.lib

*Si 625mW 10V 30mA 4.5GHz pkg:TO-92B 1,2,3
.PARAM QMPS536 File:Mcebjt.lib

*Si 625mW 60V 2A 80MHz pkg:TO-92B 1,2,3
.PARAM QMPS751 File:Mcebjt.lib

*Si 625mW 60V 600mA 330MHz pkg:TO-92B 1,2,3
.PARAM QMPS2907A File:Mcebjt.lib

*Si 625mW 40V 1A 200MHz pkg:TO-92B 1,2,3
.PARAM QMPS6652 File:Mcebjt.lib

*Si 625mW 80V 500mA 240MHz pkg:TO-92B 1,2,3
.PARAM QMPS8599 File:Mcebjt.lib

*Si 625mW 80V 500mA 155MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPSA56 File:Mcebjt.lib

*Si 1W 80V 500mA 155MHz GenPurp alias:QMPSA56 pkg:SOT-223 2,1,3
.PARAM APZTA56

*Si 625mW 300V 500mA 95MHz pkg:TO-92B 1,2,3
.PARAM QMPSA92 File:Mcebjt.lib

*Si 1W  40V 1A 200MHz pkg:TO-92B 1,2,3
.PARAM QMPSW51A File:Mcebjt.lib

*Si 1W  80V 500mA 155MHz pkg:TO-92B 1,2,3
.PARAM QMPSW56 File:Mcebjt.lib

*Si 1W 300V 500mA 85MHz pkg:TO-92B 1,2,3
.PARAM QMPSW92 File:Mcebjt.lib

*Si 200mW 30V 30mA 600MHz pkg:SC-59 1,3,2
.PARAM QMSA1022B File:Mcebjt.lib

*Si 200mW 30V 30mA 600MHz pkg:SC-59 1,3,2
.PARAM QMSA1022C File:Mcebjt.lib

*Si 200mW 25V 100mA 360MHz pkg:SC-59 1,3,2
.PARAM QMSB709R File:Mcebjt.lib

*Si 200mW 30V 500mA 160MHz pkg:SC-59 1,3,2
.PARAM QMSB710R File:Mcebjt.lib

*Si 1.5W 300V 500mA 80MHz pkg:SOT-223 2,1,3
.PARAM QPZTA92 File:Mcebjt.lib

*Si 1.5W 450V 500mA 160MHz pkg:SOT-223 2,1,3
.PARAM QPZTA96 File:Mcebjt.lib

*Si 25W 80V 3A 3MHz AF Pwr pkg:TO-66 3,1,2
.PARAM XECG218 File:Mcebjt.lib

*Si 625mW 60V 500mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QPN200 File:Mcebjt.lib

*Si 350mW 60V 500mA 250MHz GenPurp alias:QPN200 pkg:SOT-23 1,3,2
.PARAM AMMBT200

*Si 625mW 60V 500mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QPN200A File:Mcebjt.lib

*Si 350mW 60V 500mA 250MHz GenPurp pkg:SOT-23 1,3,2
.PARAM AMMBT200A

*Si 1W 60V 800mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QTN2905A File:Mcebjt.lib

*Si 625mW 60V 800mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QPN2907A File:Mcebjt.lib

*Si 1W 60V 800mA 200MHz GenPurp alias:QPN2907A pkg:SOT-223 2,1,3
.PARAM APZT2907A

*Si 1W 60V 800mA 200MHz GenPurp alias:QPN2907A pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM AMMPQ2907

*Si 1W 40V 1.2A 175MHz Switching pkg:TO-92B 1,2,3
.PARAM QTN3467A File:Mcebjt.lib

*Si 1W 40V 1.2A 175MHz Switching alias:QTN3467A pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM AMMPQ3467

*Si 350mW 12V 200mA 500MHz Switching pkg:TO-92B 1,2,3
.PARAM QPN3640 File:Mcebjt.lib

*Si 1W 80V 1A 160MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QTN4033A File:Mcebjt.lib

*Si 625mW 25V 200mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4126 File:Mcebjt.lib

*Si 350mW 25V 200mA 250MHz GenPurp alias:Q2N4126 pkg:SOT-23 1,3,2
.PARAM AMMBT4126

*Si 350mW 12V 200mA 700MHz Switching pkg:TO-92B 1,2,3
.PARAM Q2N4258 File:Mcebjt.lib

*Si 225mW 12V 200mA 700MHz Switching alias:Q2N4258 pkg:SOT-23 1,3,2
.PARAM AMMBT4258

*Si 625mW 80V 800mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QPN4356 File:Mcebjt.lib

*Si 625mW 50V 100mA 40MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5086 File:Mcebjt.lib

*Si 350mW 50V 100mA 40MHz GenPurp alias:Q2N5086 pkg:SOT-23 1,3,2
.PARAM AMMBT5086

*Si 625mW 50V 100mA 40MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5087 File:Mcebjt.lib

*Si 350mW 15V 200mA 700MHz Switching pkg:TO-92B 1,2,3
.PARAM Q2N5771 File:Mcebjt.lib

*Si 225mW 15V 200mA 700MHz Switching alias:Q2N5771 pkg:SOT-23 1,3,2
.PARAM AMMBT5771

*Si 1W 30V 1.5A 170MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QTN6726A File:Mcebjt.lib

*Si 1W 30V 1.5A 170MHz GenPurp alias:QTN6726A pkg:SOT-123 2,1,3
.PARAM ANZT6726

*Si 1W 60V 1.2A 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QTN6728A File:Mcebjt.lib

*Si 1W 60V 1.2A 150MHz GenPurp alias:QTN6728A pkg:SOT-123 2,1,3
.PARAM ANZT6728

*Si 1W 80V 1A 120MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QTN6729A File:Mcebjt.lib

*Si 1W 80V 1A 120MHz GenPurp alias:QTN6729A pkg:SOT-123 2,1,3
.PARAM ANZT6729

*Si 625mW 25V 800mA 125MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPS8550 File:Mcebjt.lib

*Si 350mW 20V 50mA 600MHz RF pkg:TO-92B 1,2,3
.PARAM QMPSH81 File:Mcebjt.lib

*Si 225mW 20V 50mA 600MHz RF alias:QMPSH81 pkg:SOT-23 1,3,2
.PARAM AMMBTH81

*Si 60W 60V 8A 40MHz PwrAmp pkg:TO-220 2,1,3
.PARAM XD45H8 File:Mcebjt.lib

*Si 1.5W 60V 8A 40MHz PwrAmp alias:XD45H8 pkg:SOT-223 2,1,3
.PARAM ANZT45H8

*Si 625mW 20V 1.5A 45MHz GenPurp pkg:TO-92B 2,1,3
.PARAM QBC369 File:Mcebjt.lib

*Si 350mW 45V 1.2A 45MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC807-16 File:Mcebjt.lib

*Si 350mW 45V 1.2A 45MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC807-25 File:Mcebjt.lib

*Si 350mW 45V 1.2A 45MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC807-40 File:Mcebjt.lib

*Si 350mW 45V 500mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC857B File:Mcebjt.lib

*Si 350mW 45V 500mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC857C File:Mcebjt.lib

*Si 1.5W 60V 1.2A 105MHz GenPurp pkg:SOT-223 2,1,3
.PARAM QBCP52 File:Mcebjt.lib

*Si 350mW 45V 800mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW68G File:Mcebjt.lib

*Si 350mW 45V 500mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCX71K File:Mcebjt.lib

*Si 1.2W 60V 4A 75MHz CurrentDrvr pkg:SOT-223 2,1,3
.PARAM XNZT751 File:Mcebjt.lib

*Si 625mW 30V 200mA 250MHz Amp pkg:TO-92B 1,2,3
.PARAM Q2N4125 File:Mcebjt.lib

*Si 625mW 120V 600mA 250MHz Amp pkg:TO-92B 1,2,3
.PARAM Q2N5400 File:Mcebjt.lib

*Si 625mW 300V 500mA 120MHz HiVolt pkg:TO-92B 1,2,3
.PARAM Q2N6519 File:Mcebjt.lib

*Si 350mW 50V 100mA 280MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC212 File:Mcebjt.lib

*Si 350mW 50V 100mA 280MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC212B File:Mcebjt.lib

*Si 350mW 30V 100mA 320MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC213 File:Mcebjt.lib

*Si 350mW 30V 100mA 360MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC214 File:Mcebjt.lib

*Si 350mW 45V 100mA 280MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC307 File:Mcebjt.lib

*Si 350mW 45V 100mA 280MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC307B File:Mcebjt.lib

*Si 350mW 45V 100mA 280MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC307C File:Mcebjt.lib

*Si 350mW 25V 100mA 320MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC308C File:Mcebjt.lib

*Si 350mW 25V 100mA 360MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC309B File:Mcebjt.lib

*Si 625mW 45V 800mA 260MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC327 File:Mcebjt.lib

*Si 625mW 45V 800mA 260MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC327-16 File:Mcebjt.lib

*Si 625mW 45V 800mA 260MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC327-25 File:Mcebjt.lib

*Si 625mW 25V 800mA 260MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC328 File:Mcebjt.lib

*Si 625mW 25V 800mA 260MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC328-16 File:Mcebjt.lib

*Si 625mW 25V 800mA 260MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC328-25 File:Mcebjt.lib

*Si 625mW 100V 300mA 200MHz HiVolt pkg:TO-92B 3,2,1
.PARAM QBC450 File:Mcebjt.lib

*Si 625mW 100V 300mA 200MHz HiVolt pkg:TO-92B 3,2,1
.PARAM QBC450A File:Mcebjt.lib

*Si 625mW 80V 500mA 150MHz HiCurr pkg:TO-92B 3,2,1
.PARAM QBC490 File:Mcebjt.lib

*Si 625mW 80V 500mA 150MHz HiCurr pkg:TO-92B 3,2,1
.PARAM QBC490A File:Mcebjt.lib

*Si 625mW 65V 100mA 280MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC556 File:Mcebjt.lib

*Si 625mW 65V 100mA 280MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC556B File:Mcebjt.lib

*Si 625mW 45V 100mA 320MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC557 File:Mcebjt.lib

*Si 625mW 45V 100mA 320MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC557A File:Mcebjt.lib

*Si 625mW 45V 100mA 320MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC557B File:Mcebjt.lib

*Si 625mW 45V 100mA 320MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC557C File:Mcebjt.lib

*Si 625mW 30V 100mA 320MHz Amp pkg:TO-92B 3,2,1
.PARAM QBC558B File:Mcebjt.lib

*Si 625mW 30V 100mA 250MHz LoNoise pkg:TO-92B 3,2,1
.PARAM QBC559 File:Mcebjt.lib

*Si 625mW 30V 100mA 250MHz LoNoise pkg:TO-92B 3,2,1
.PARAM QBC559B File:Mcebjt.lib

*Si 625mW 30V 100mA 250MHz LoNoise pkg:TO-92B 3,2,1
.PARAM QBC559C File:Mcebjt.lib

*Si 625mW 45V 100mA 250MHz LoNoise pkg:TO-92B 3,2,1
.PARAM QBC560B File:Mcebjt.lib

*Si 625mW 45V 100mA 250MHz LoNoise pkg:TO-92B 3,2,1
.PARAM QBC560C File:Mcebjt.lib

*Si 625mW 45V 500mA 150MHz HiCurr pkg:TO-92B 2,1,3
.PARAM QBC636 File:Mcebjt.lib

*Si 625mW 60V 500mA 150MHz HiCurr pkg:TO-92B 2,1,3
.PARAM QBC638 File:Mcebjt.lib

*Si 625mW 80V 500mA 150MHz HiCurr pkg:TO-92B 2,1,3
.PARAM QBC640 File:Mcebjt.lib

*Si 225mW 65V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC856ALT1 File:Mcebjt.lib

*Si 225mW 65V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC856BLT1 File:Mcebjt.lib

*Si 225mW 45V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC857ALT1 File:Mcebjt.lib

*Si 225mW 30V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC858ALT1 File:Mcebjt.lib

*Si 225mW 30V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC858BLT1 File:Mcebjt.lib

*Si 225mW 30V 100mA 100MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC858CLT1 File:Mcebjt.lib

*Si 1.5W 80V 1.5A 50MHz HiCurr pkg:SOT-223 2,1,3
.PARAM QBCP53T1 File:Mcebjt.lib

*Si 1.5W 25V 1A 60MHz HiCurr pkg:SOT-223 2,1,3
.PARAM QBCP69T1 File:Mcebjt.lib

*Si 225mW 32V 100mA 360MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW29LT1 File:Mcebjt.lib

*Si 225mW 32V 100mA 360MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW30LT1 File:Mcebjt.lib

*Si 225mW 32V 100mA 360MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW61BLT1 File:Mcebjt.lib

*Si 225mW 32V 100mA 360MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW61CLT1 File:Mcebjt.lib

*Si 225mW 32V 100mA 360MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW61DLT1 File:Mcebjt.lib

*Si 225mW 45V 100mA 360MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW69LT1 File:Mcebjt.lib

*Si 225mW 45V 100mA 360MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW70LT1 File:Mcebjt.lib

*Si 225mW 45V 500mA 160MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCX17LT1 File:Mcebjt.lib

*Si 225mW 25V 500mA 160MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCX18LT1 File:Mcebjt.lib

*Si 1W 80V 500mA 80MHz Amp pkg:TO-92B 1,2,3
.PARAM QBDB02C File:Mcebjt.lib

*Si 1W 100V 500mA 80MHz Amp pkg:TO-92B 1,2,3
.PARAM QBDB02D File:Mcebjt.lib

*Si 1W 100V 500mA 80MHz Amp pkg:TO-92B 2,1,3
.PARAM QBDC02D File:Mcebjt.lib

*Si 625mW 300V 500mA 90MHz HiVolt pkg:TO-92B 2,1,3
.PARAM QBF421 File:Mcebjt.lib

*Si 625mW 250V 500mA 90MHz HiVolt pkg:TO-92B 2,1,3
.PARAM QBF423 File:Mcebjt.lib

*Si 625mW 250V 500mA 80MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QBF492 File:Mcebjt.lib

*Si 625mW 300V 500mA 80MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QBF493 File:Mcebjt.lib

*Si 625mW 350V 500mA 80MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QBF493S File:Mcebjt.lib

*Si 225mW 100V 100mA 95MHz HiVolt pkg:SOT-23 1,3,2
.PARAM QBSS63LT1 File:Mcebjt.lib

*Si 225mW 40V 600mA 250MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QMMBT2907LT1 File:Mcebjt.lib

*Si 225mW 60V 500mA 90MHz Driver pkg:SOT-23 1,3,2
.PARAM QMMBTA55LT1 File:Mcebjt.lib

*Si 225mW 40V 100mA 150MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QMMBTA70LT1 File:Mcebjt.lib

*Si 225mW 200V 500mA 90MHz HiVolt pkg:SOT-23 1,3,2
.PARAM QMMBTA93LT1 File:Mcebjt.lib

*Si 720mW 60V 200mA 250MHz Quad Amp pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM QMMPQ3799 File:Mcebjt.lib

*Si 1.9W 40V 600mA 300MHz Quad GenPurp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ2906 File:Mcebjt.lib

*Si 1.9W 40V 600mA 300MHz Quad GenPurp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ2907 File:Mcebjt.lib

*Si 1.9W 60V 600mA 300MHz Quad GenPurp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ2907A File:Mcebjt.lib

*Si 1.5W 40V 1A 190MHz Quad MemDrvr pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ3467 File:Mcebjt.lib

*Si 1.7W 40V 1.5A 275MHz Quad MemDrvr pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ3762 File:Mcebjt.lib

*Si 900mW 40V 50mA 250MHz Quad Amp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ3798 File:Mcebjt.lib

*Si 900mW 60V 50mA 250MHz Quad Amp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ3799 File:Mcebjt.lib

*Si 900mW 40V 200mA 250MHz Quad AmpSwitch pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ3906 File:Mcebjt.lib

*Si 1.7W 150V 500mA 70MHz Quad Amp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ7091 File:Mcebjt.lib

*Si 1.7W 250V 500mA 70MHz Quad Amp pkg:DIP14 (A:1,2,3)(B:7,6,5)(C:8,9,10)(D:14,13,12)
.PARAM QMPQ7093 File:Mcebjt.lib

*Si 625mW 40V 2A 100MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS750 File:Mcebjt.lib

*Si 625mW 40V 600mA 250MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS2907 File:Mcebjt.lib

*Si 625mW 25V 500mA 150MHz Switch pkg:TO-92B 1,2,3
.PARAM QMPS3638 File:Mcebjt.lib

*Si 625mW 25V 500mA 200MHz Switch pkg:TO-92B 1,2,3
.PARAM QMPS3638A File:Mcebjt.lib

*Si 625mW 12V 80mA 500MHz Switch pkg:TO-92B 1,2,3
.PARAM QMPS3640 File:Mcebjt.lib

*Si 625mW 40V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPS3906 File:Mcebjt.lib

*Si 625mW 30V 200mA 200MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS4125 File:Mcebjt.lib

*Si 625mW 25V 200mA 230MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS4126 File:Mcebjt.lib

*Si 625mW 12V 80mA 700MHz Switch pkg:TO-92B 1,2,3
.PARAM QMPS4258 File:Mcebjt.lib

*Si 625mW 15V 50mA 514MHz Switch pkg:TO-92B 1,2,3
.PARAM QMPS5771 File:Mcebjt.lib

*Si 625mW 25V 100mA 364MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6523 File:Mcebjt.lib

*Si 625mW 25V 500mA 90MHz Audio pkg:TO-92B 1,2,3
.PARAM QMPS6562 File:Mcebjt.lib

*Si 625mW 25V 1A 120MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6651 File:Mcebjt.lib

*Si 1W 30V 1A 115MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6726 File:Mcebjt.lib

*Si 1W 40V 1A 115MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS6727 File:Mcebjt.lib

*Si 625mW 40V 200mA 257MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPS8093 File:Mcebjt.lib

*Si 625mW 60V 500mA 180MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPS8598 File:Mcebjt.lib

*Si 625mW 60V 500mA 150MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSA55 File:Mcebjt.lib

*Si 625mW 40V 100mA 100MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSA70 File:Mcebjt.lib

*Si 625mW 200V 500mA 80MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QMPSA93 File:Mcebjt.lib

*Si 625mW 100V 600mA 90MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSL51 File:Mcebjt.lib

*Si 1W 30V 1A 80MHz HiCurr pkg:TO-92B 1,2,3
.PARAM QMPSW51 File:Mcebjt.lib

*Si 1W 60V 500mA 80MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSW55 File:Mcebjt.lib

*Si 200mW 25V 100mA 364MHz GenPurpAmp pkg:SOT-23 1,3,2
.PARAM QMSB709-ST1 File:Mcebjt.lib

*Si 200mW 30V 500mA 163MHz GenPurpAmp pkg:SOT-23 1,3,2
.PARAM QMSB710-QT1 File:Mcebjt.lib

*Si 150mW 45V 100mA 364MHz GenPurpAmp pkg:SOT-23 1,3,2
.PARAM QMSB1218A-RT1 File:Mcebjt.lib

*Si 150mW 45V 100mA 364MHz GenPurpAmp pkg:SOT-23 1,3,2
.PARAM QMSB1218A-ST1 File:Mcebjt.lib

*Si 625mW 300V 500mA 80MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QPBF493 File:Mcebjt.lib

*Si 625mW 300V 500mA 80MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QPBF493S File:Mcebjt.lib

*Si 625mW 300V 500mA 80MHz HiVolt pkg:TO-92B 3,2,1
.PARAM QPBF493R File:Mcebjt.lib

*Si 625mW 300V 500mA 80MHz HiVolt pkg:TO-92B 3,2,1
.PARAM QPBF493RS File:Mcebjt.lib

*Si 625mW 60V 600mA 250MHz Amp pkg:TO-92B 3,2,1
.PARAM QP2N2907A File:Mcebjt.lib

*Si 800mW 60V 2A 100MHz HiCurr pkg:SOT-223 2,1,3
.PARAM QPZT751T1 File:Mcebjt.lib

*Si 600mW 40V 600mA 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N2904 File:Mcebjt.lib

*Si 600mW 60V 600mA 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N2904A File:Mcebjt.lib

*Si 600mW 40V 600mA 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N2905 File:Mcebjt.lib

*Si 400mW 40V 600mA 250MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2906 File:Mcebjt.lib

*Si 400mW 60V 600mA 250MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2906A File:Mcebjt.lib

*Si 400mW 40V 600mA 250MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2907 File:Mcebjt.lib

*Si 1W 40V 1A 200MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3244 File:Mcebjt.lib

*Si 360mW 40V 200mA 300MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N3250 File:Mcebjt.lib

*Si 360mW 40V 200mA 350MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N3251 File:Mcebjt.lib

*Si 400mW 120V 100mA 200MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N3497 File:Mcebjt.lib

*Si 360mW 12V 200mA 800MHz Switch pkg:TO-18 3,2,1
.PARAM Q2N3546 File:Mcebjt.lib

*Si 1W 140V 1A 200MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3634 File:Mcebjt.lib

*Si 1W 140V 1A 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3635 File:Mcebjt.lib

*Si 1W 175V 1A 200MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3636 File:Mcebjt.lib

*Si 1W 175V 1A 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3637 File:Mcebjt.lib

*Si 360mW 80V 200mA 257MHz Amp pkg:TO-18 3,2,1
.PARAM Q2N3963 File:Mcebjt.lib

*Si 800mW 60V 1A 115MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4032 File:Mcebjt.lib

*Si 800mW 80V 1A 115MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4033 File:Mcebjt.lib

*Si 1W 65V 1A 115MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4036 File:Mcebjt.lib

*Si 1W 40V 1A 115MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4037 File:Mcebjt.lib

*Si 1.25W 80V 1A 350MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4405 File:Mcebjt.lib

*Si 1.25W 80V 2A 450MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4407 File:Mcebjt.lib

*Si 1W 250V 50mA 110MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4931 File:Mcebjt.lib

*Si 800mW 40V 1A 80MHz Amp pkg:TO-39 3,2,1
.PARAM QBC160-16 File:Mcebjt.lib

*Si 800mW 60V 1A 80MHz Amp pkg:TO-39 3,2,1
.PARAM QBC161-16 File:Mcebjt.lib

*Si 600mW 45V 200mA 300MHz pkg:TO-18 3,2,1
.PARAM QBC177 File:Mcebjt.lib

*Si 600mW 45V 200mA 300MHz pkg:TO-18 3,2,1
.PARAM QBC177A File:Mcebjt.lib

*Si 600mW 45V 200mA 300MHz pkg:TO-18 3,2,1
.PARAM QBC177B File:Mcebjt.lib

*Si 400mW 180V 500mA 110MHz HiVolt pkg:TO-18 3,2,1
.PARAM QBC393 File:Mcebjt.lib

*Si 360mW 40V 200mA 300MHz pkg:TO-18 3,2,1
.PARAM QBCY70 File:Mcebjt.lib

*Si 360mW 45V 200mA 300MHz pkg:TO-18 3,2,1
.PARAM QBCY71 File:Mcebjt.lib

*Si 360mW 25V 200mA 300MHz pkg:TO-18 3,2,1
.PARAM QBCY72 File:Mcebjt.lib

*Si 400mW 150V 100mA 110MHz HiVolt pkg:TO-18 3,2,1
.PARAM QBFW43 File:Mcebjt.lib

*Si 500mW 200V 500mA 110MHz HiVolt pkg:TO-18 3,2,1
.PARAM QBSS74 File:Mcebjt.lib

*Si 500mW 250V 500mA 110MHz HiVolt pkg:TO-18 3,2,1
.PARAM QBSS75 File:Mcebjt.lib

*Si 500mW 300V 500mA 110MHz HiVolt pkg:TO-18 3,2,1
.PARAM QBSS76 File:Mcebjt.lib

*Si 1.25W 60V 1A 100MHz Amp pkg:TO-39 3,2,1
.PARAM QBSV16-10 File:Mcebjt.lib

*Si 1W 150V 500mA 163MHz GenPurp pkg:TO-39 3,2,1
.PARAM QMM4001 File:Mcebjt.lib

*Si 750mW 18V 5A 120MHz pkg:TO-92B 2,1,3
.PARAM QECG12 PNP File:Mcebjt.lib

*Si 750mW 80V 700mA 130MHz pkg:TO-126 2,3,1
.PARAM QECG14 PNP File:Mcebjt.lib

*Si 300mW 40V 100mA 140MHz pkg:TO-126 2,3,1
.PARAM QECG17 PNP File:Mcebjt.lib

*Si 1W 80V 700mA 120MHz pkg:TO-126 2,3,1
.PARAM QECG19 PNP File:Mcebjt.lib

*Si 1W 32V 2A 100MHz pkg:TO-126 2,3,1
.PARAM QECG21 PNP File:Mcebjt.lib

*Si 1W 80V 1.25A 50MHz pkg:TO-92B 1,2,3
.PARAM QECG25 PNP File:Mcebjt.lib

*Ge 170W 45V 60A 10KHz pkg:TO-3 3,2,1
.PARAM QECG27 PNP File:Mcebjt.lib

*Ge 170W 45V 60A 10KHz pkg:TO-126 3,1,2
.PARAM QECG28 PNP File:Mcebjt.lib

*Si 900mW 160V 1A 20MHz pkg:TO-92B 1,2,3
.PARAM QECG32 PNP File:Mcebjt.lib

*Si 400mW 100V 50mA 150MHz Dual pkg:SIP5 (2,1,3)(4,5,3)
.PARAM QECG41 PNP File:Mcebjt.lib

*Si 400mW 50V 100mA 100MHz Dual pkg:SIP5 (2,1,3)(4,5,3)
.PARAM QECG43 PNP File:Mcebjt.lib

*Si 400mW 100V 100mA 100MHz Dual pkg:SIP5 (2,3,1)(4,3,5)
.PARAM QECG45 PNP File:Mcebjt.lib

*Si 200W 200V 17A 20MHz pkg:TB-35 2,1,3
.PARAM QECG59 PNP File:Mcebjt.lib

*Si 600mW 60V 600mA 250MHz Dual pkg:CAN8 (1,2,3)(7,6,5)
.PARAM QECG82 PNP File:Mcebjt.lib

*Si 750mW 120V 50mA 150MHz pkg:TO-92B 2,1,3
.PARAM QECG91 PNP File:Mcebjt.lib

*Ge 150mW 20V 300mA .455MHz pkg:TO-5 3,2,1
.PARAM QECG100 PNP File:Mcebjt.lib

*Ge 150mW 16V 300mA 2MHz pkg:TO-5 3,2,1
.PARAM QECG102 PNP File:Mcebjt.lib

*Ge 900mW 32V 500mA 2.3MHz pkg:TO-1 3,2,1
.PARAM QECG102A PNP File:Mcebjt.lib

*Si 250mW 15V 75mA 500MHz pkg:TO-18 3,2,1
.PARAM QECG106 PNP File:Mcebjt.lib

*Ge 300mW 15V 50mA 250MHz pkg:TO-18 3,2,1
.PARAM QECG126A PNP File:Mcebjt.lib

*Si 1W 80V 1A 120MHz pkg:TO-39 3,2,1
.PARAM QECG129 PNP File:Mcebjt.lib

*Si 1W 80V 1A 150MHz pkg:TO-92B 1,2,3
.PARAM QECG129P PNP File:Mcebjt.lib

*Si 600mW 80V 1A 200MHz pkg:TO-92B 1,2,3
.PARAM QECG159 PNP File:Mcebjt.lib

*Ge 200mW 20V 10mA 400MHz pkg:TO-72 3,2,1
.PARAM QECG160 PNP File:Mcebjt.lib

*Si 200W 100V 30A 3MHz pkg:TO-3 3,2,1
.PARAM QECG180 PNP File:Mcebjt.lib

*Si 700mW 70V 1A 130MHz pkg:TO-92B 1,2,3
.PARAM QECG193 PNP File:Mcebjt.lib

*Si 600mW 70V 500mA 120MHz pkg:TO-92B 1,2,3
.PARAM QECG193A PNP File:Mcebjt.lib

*Si 1.33W 75V 1A 200MHz pkg:TO-126 3,2,1
.PARAM QECG211 PNP File:Mcebjt.lib

*Ge 170W 65V 30A 270KHz pkg:TO-126 1,2,3
.PARAM QECG213 PNP File:Mcebjt.lib

*Si 1W 40V 1A 175MHz pkg:TO-92B 1,2,3
.PARAM QECG217 PNP File:Mcebjt.lib

*Si 150W 70V 15A 5MHz pkg:TO-3 3,2,1
.PARAM QECG219 PNP File:Mcebjt.lib

*Si 200mW 50V 50mA 90MHz pkg:TO-92B 2,1,3
.PARAM QECG234 PNP File:Mcebjt.lib

*Si 60W 80V 4A 2MHz pkg:TO-3 2,1,3
.PARAM QECG242 PNP File:Mcebjt.lib

*Si 100W 140V 12A 6MHz pkg:TO-3 3,2,1
.PARAM QECG281 PNP File:Mcebjt.lib

*Si 625mW 300V 500mA 50MHz pkg:TO-92B 1,2,3
.PARAM QECG288 PNP File:Mcebjt.lib

*Si 7W 40V 1.5A 70MHz pkg:TO-126 1,2,3
.PARAM QECG307 PNP File:Mcebjt.lib

*Si 90W 100V 15A 5MHz pkg:TO-3 2,1,3
.PARAM QECG332 PNP File:Mcebjt.lib

*Si 8W 18V 1A 150MHz pkg:TO-126 1,2,3
.PARAM QECG353  PNP File:Mcebjt.lib

*Si 20W 18V 2.5A 150MHz pkg:TO-126 1,2,3
.PARAM QECG354 PNP File:Mcebjt.lib

*Si 40W 18V 4A 150MHz pkg:TO-126 1,2,3
.PARAM QECG355 PNP File:Mcebjt.lib

*Si 60W 18V 6A 150MHz pkg:TO-126 1,2,3
.PARAM QECG356 PNP File:Mcebjt.lib

*Si 1W 160V 1.5A 140MHz pkg:TO-126 2,3,1
.PARAM QECG374 PNP File:Mcebjt.lib

*Si 900mW 100V 1A 140MHz pkg:TO-92B 2,1,3
.PARAM QECG383 PNP File:Mcebjt.lib

*Si 360mW 25V 50mA 2300MHz pkg:TO-72 3,2,1
.PARAM QECG395 PNP File:Mcebjt.lib

*Si 10W 300V 1A 30MHz pkg:TO-39 3,2,1
.PARAM QECG397 PNP File:Mcebjt.lib

*Si 90W 50V 15A 20MHz pkg:TO-3 2,1,3
.PARAM QECG2314 PNP File:Mcebjt.lib

*Si 1.9W 40V 500mA 350MHz Quad pkg:DIP14 (1,2,3)(7,6,5)(8,9,10)(14,13,12)
.PARAM QECG2322 PNP File:Mcebjt.lib

*Si 1W 50V 2A 150MHz pkg:TO-92B 2,1,3
.PARAM QECG2364 PNP File:Mcebjt.lib

*Si 900mW 300V 100mA 50MHz pkg:TO-92B 2,1,3
.PARAM QECG2366 PNP File:Mcebjt.lib

*Si 1W 80V 1A 100MHz pkg:TO-92B 2,1,3
.PARAM QECG2429 PNP File:Mcebjt.lib

*Si 1W 300V 1A 15MHz pkg:TO-89 2,1,3
.PARAM QECG2431 PNP File:Mcebjt.lib

*Si 7W 300V 100mA 150MHz pkg:TO-126 2,3,1
.PARAM QECG2502 PNP File:Mcebjt.lib

*Si 10W 60V 500mA 800MHz pkg:TO-126 2,3,1
.PARAM QECG2512 PNP File:Mcebjt.lib

*Si 10W 50V 2.5A 140MHz pkg:TO-126 2,3,1
.PARAM QECG2518 PNP File:Mcebjt.lib

*Si 10W 160V 1.5A 120MHz pkg:TO-126 2,3,1
.PARAM QECG2520 PNP File:Mcebjt.lib

*Si 15W 40V 8A 250MHz pkg:TO-126 2,1,3
.PARAM QECG2523 PNP File:Mcebjt.lib

*Si 20W 50V 8A 180MHz pkg:TO-126 2,1,3
.PARAM QECG2525 PNP File:Mcebjt.lib

*Si 20W 100V 4A 180MHz pkg:TO-126 2,1,3
.PARAM QECG2527 PNP File:Mcebjt.lib

*Si 15W 160V 1.5A 120MHz pkg:TO-126 2,1,3
.PARAM QECG2529 PNP File:Mcebjt.lib

*Si 15W 400V 2A 60MHz pkg:TO-126 2,1,3
.PARAM QECG2531 PNP File:Mcebjt.lib

*Si 80W 80V 12A 20MHz pkg:TO-3 2,1,3
.PARAM QECG2535 PNP File:Mcebjt.lib

*Si 150W 100V 40A 18.2MHz pkg:TO-3 2,1,3
.PARAM QECG2537 PNP File:Mcebjt.lib

*Si 25W 30V 12A 120MHz pkg:TO-220 2,1,3
.PARAM QECG2563 PNP File:Mcebjt.lib

*Si 30W 60V 10A 100MHz pkg:TO-220 2,1,3
.PARAM QECG2569 PNP File:Mcebjt.lib

*Si 30W 80V 7A 20MHz pkg:TO-220 2,1,3
.PARAM QECG2571 PNP File:Mcebjt.lib

*Si 10W 120V 400mA 400MHz pkg:TO-220 2,1,3
.PARAM QECG2575 PNP File:Mcebjt.lib

*Si 20W 180V 2A 60MHz pkg:TO-220 2,1,3
.PARAM QECG2577 PNP File:Mcebjt.lib

*Ge 150mW 25V 100mA 364MHz pkg:TO-18 3,2,1
.PARAM Q2N2955 PNP File:Mcebjt.lib

*Si 300W 80V 50A 2MHz Power pkg:TO-3 3,2,1
.PARAM XECG30    PNP File:Mcebjt.lib

*Si 250W 140V 20A 2MHz Power pkg:TO-3 3,2,1
.PARAM XECG61    PNP File:Mcebjt.lib

*Si 150W 180V 16A 6MHz Power pkg:TO-3 3,2,1
.PARAM XECG285   PNP File:Mcebjt.lib

*Si 150W 200V 15A 30MHz Power pkg:TO-3 2,1,3
.PARAM XECG2329  PNP File:Mcebjt.lib

*Si 150W 200V 15A 20MHz Power pkg:TB-35 2,1,3
.PARAM XECG93    PNP File:Mcebjt.lib

*Si 80W 120V 7A 9MHz Power pkg:TB-33 2,1,3
.PARAM XECG381   PNP File:Mcebjt.lib

*Si 80W 100V 10A 3MHz Power pkg:TO-3 2,1,3
.PARAM XECG391   PNP File:Mcebjt.lib

*Si 125W 100V 25A 3MHz Power pkg:TO-3 2,1,3
.PARAM XECG393   PNP File:Mcebjt.lib

*Si 125W 160V 16A 1MHz Power pkg:TO-3 2,1,3
.PARAM XECG2306  PNP File:Mcebjt.lib

*Si 100W 140V 12A 15MHz Power pkg:TO-3 2,1,3
.PARAM XECG37    PNP File:Mcebjt.lib

*Si 50W 60V 7A 10MHz Power pkg:TO-220 2,1,3
.PARAM XECG153   PNP File:Mcebjt.lib

*Si 50W 80V 10A 50MHz Power pkg:TO-220 2,1,3
.PARAM XECG378   PNP File:Mcebjt.lib

*Si 50W 80V 7A 800KHz Power pkg:TO-220 2,1,3
.PARAM XECG197   PNP File:Mcebjt.lib

*Si 40W 120V 4A 4MHz Power pkg:TO-220 2,1,3
.PARAM XECG292   PNP File:Mcebjt.lib

*Si 50W 150V 8A 85MHz Power pkg:TO-220 2,1,3
.PARAM XECG55    PNP File:Mcebjt.lib

*Si 30W 50V 12A 10MHz Power pkg:TO-220 2,1,3
.PARAM XECG2567  PNP File:Mcebjt.lib

*Si 30W 30V 8A 120MHz Power pkg:TO-220 2,1,3
.PARAM XECG2565  PNP File:Mcebjt.lib

*Si 40W 80V 4A 2MHz Power pkg:TO-126 2,3,1
.PARAM XECG185   PNP File:Mcebjt.lib

*Si 20.8W 300V 500mA 10MHz Power pkg:TO-126 2,3,1
.PARAM XECG39    PNP File:Mcebjt.lib

*Si 8W 120V 300mA 400MHz Power pkg:TO-126 2,3,1
.PARAM XECG2509  PNP File:Mcebjt.lib

*Si 20W 50V 8A 180MHz Power pkg:TO-126 2,3,1
.PARAM XECG2514  PNP File:Mcebjt.lib

*Si 20W 100V 4A 180MHz Power pkg:TO-126 2,3,1
.PARAM XECG2516  PNP File:Mcebjt.lib

*Si 12.5W 60V 3A 50MHz Power pkg:TO-126 2,1,3
.PARAM XECG187   PNP File:Mcebjt.lib

*Si 10W 100V 2A 150MHz Power pkg:TO-126 2,1,3
.PARAM XECG50    PNP File:Mcebjt.lib

*Si 10W 50V 3A 150MHz Power pkg:TO-126 2,1,3
.PARAM XECG187A  PNP File:Mcebjt.lib

*============================================
*Zetex

*ZTX Si 1W 40V 1A 50MHz MedPwr pkg:TO-92B  1,2,3
.PARAM Q2N6727 File:Zetex.lib

*ZTX Si 1W 50V 2A 120MHz MedPwr pkg:SOT-89 2,1,3
.PARAM 2SA1213 File:Zetex.lib

*ZTX 300mW 45V 200mA 130MHz GenPurp pkg:TO-18 3,2,1
.PARAM QBC177AP File:Zetex.lib

*ZTX 300mW 25V 200mA 130MHz GenPurp pkg:TO-18 3,2,1
.PARAM QBC178AP File:Zetex.lib

*ZTX Si 300mW 50V 200mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC212AP File:Zetex.lib

*ZTX Si 300mW 30V 200mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC213AP File:Zetex.lib

*ZTX 300mW 45V 200mA 130MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC307AP File:Zetex.lib

*ZTX Si 300mW 25V 200mA 130MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC308AP File:Zetex.lib

*ZTX Si 2dB 30V 100mA 200MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QBC415AP File:Zetex.lib

*ZTX Si 2dB 45V 100mA 200MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QBC416AP File:Zetex.lib

*ZTX Si 500mW 65V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC556AP File:Zetex.lib

*ZTX Si 500mW 45V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC557AP File:Zetex.lib

*ZTX Si 5W 30V 200mA 150MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QBC558AP File:Zetex.lib

*ZTX Si 4dB 30V 200mA 300MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QBC559AP File:Zetex.lib

*ZTX Si 2dB 45V 200mA 300MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QBC560AP File:Zetex.lib

*ZTX Si 350mW 65V 100mA 150MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC856A File:Zetex.lib

*ZTX Si 350mW 45V 100mA 150MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC857A File:Zetex.lib

*ZTX Si 350mW 30V 100mA 150MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC858A File:Zetex.lib

*ZTX Si 350mW 30V 100mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM BC859A File:Zetex.lib

*ZTX Si 350mW 45V 100mA 300MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBC860A File:Zetex.lib

*ZTX Si 350mW 20V 100mA 150MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW29 File:Zetex.lib

*ZTX Si 350mW 32V 200mA 180MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW61A File:Zetex.lib

*ZTX Si 425mW 30V 800mA 100MHz MedPwr pkg:SOT-23 1,3,2
.PARAM QBCW67A File:Zetex.lib

*ZTX Si 425mW 45V 800mA 100MHz MedPwr pkg:SOT-23 1,3,2
.PARAM QBCW68F File:Zetex.lib

*ZTX Si 350mW 45V 100mA 150MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW69 File:Zetex.lib

*ZTX Si 350mW 60V 100mA 150MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCW89 File:Zetex.lib

*ZTX Si 350mW 45V 200mA 180MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBCX71G File:Zetex.lib

*ZTX Si 1W 400V 200mA 50MHz HiVolt pkg:SOT-89 2,1,3
.PARAM QFCX558 File:Zetex.lib

*ZTX Si 1.5W 25V 2A 100MHz MedPwr pkg:SOT-89 2,1,3
.PARAM QFCX749 File:Zetex.lib

*ZTX Si 500mW 300V 500mA 75MHz HiVolt pkg:SOT-23 1,3,2
.PARAM QFMMT597 File:Zetex.lib

*ZTX Si 330mW 40V 100mA 125MHz SmallSig pkg:SOT-23 1,3,2
.PARAM QFMMTA70 File:Zetex.lib

*ZTX Si 2W 25V 3A 100MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT749 File:Zetex.lib

*ZTX Si 2W 60V 3A 100MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT751 File:Zetex.lib

*ZTX Si 2W 300V 500mA 30MHz HiVolt pkg:SOT-223 2,1,3
.PARAM QFZT757 File:Zetex.lib

*ZTX Si 2W 400V 500mA 50MHz HiVolt pkg:SOT-223 2,1,3
.PARAM QFZT758 File:Zetex.lib

*ZTX Si pkg:SOT-223 2,1,3
.PARAM QFZT788A File:Zetex.lib

*ZTX Si 2W 15V 3A 100MHz HiGain pkg:SOT-223 2,1,3
.PARAM QFZT788B File:Zetex.lib

*ZTX Si 2W 25V 3A 100MHz MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT789A File:Zetex.lib

*ZTX Si 2W 40V 2A 100MHz HiGain pkg:SOT-223 2,1,3
.PARAM QFZT790A File:Zetex.lib

*ZTX Si 2W 70V 3A 100MHz HiGain/MedPwr pkg:SOT-223 2,1,3
.PARAM QFZT792A File:Zetex.lib

*ZTX Si 500mW 50V 200mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX212 File:Zetex.lib

*ZTX Si 500mW 50V 200mA 200MHz pkg:TO-92B 1,2,3
.PARAM QZTX212A File:Zetex.lib

*ZTX Si 500mW 30V 200mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QZTX213 File:Zetex.lib

*ZTX Si 2dB 30V 200mA 200MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QZTX214 File:Zetex.lib

*ZTX Si 2dB 30V 200mA 200MHz LoNoise pkg:TO-92B 1,2,3
.PARAM QZTX214A File:Zetex.lib

*ZTX Si pkg:TO-92B 1,2,3
.PARAM QZTX231A File:Zetex.lib

*ZTX Si 1W 45V 1A 150MHz GenPurp/MedPwr pkg:TO-92B 1,2,3
.PARAM QZTX550 File:Zetex.lib

*ZTX Si 1W 400V 500mA HiVolt pkg:TO-92B 1,2,3
.PARAM QZTX558 File:Zetex.lib

*ZTX Si 1W 25V 2A 100MHz MedPwr pkg:TO-92B 1,2,3
.PARAM QZTX749 File:Zetex.lib

*ZTX Si 1W  45V 2A 100MHz MedPwr pkg:TO-92B 1,2,3
.PARAM QZTX750 File:Zetex.lib

*ZTX Si 1W 60V 2A 100MHz MedPwr pkg:TO-92B 1,2,3
.PARAM QZTX751 File:Zetex.lib

*ZTX Si 1W 300V 500mA 30MHz MedPwr/HiVolt pkg:TO-92B 1,2,3
.PARAM QZTX757 File:Zetex.lib

*ZTX Si 1W 400V 500mA HiVolt pkg:TO-92B 1,2,3
.PARAM QZTX758 File:Zetex.lib

*ZTX Si pkg:TO-92B 1,2,3
.PARAM QZTX788A File:Zetex.lib

*ZTX Si 1W 15V 3A 100MHz pkg:TO-92B 1,2,3
.PARAM QZTX788B File:Zetex.lib

*ZTX Si 1W 25V 3A 100MHz pkg:TO-92B 1,2,3
.PARAM QZTX789A File:Zetex.lib

*ZTX Si 1W 40V 2A 100MHz pkg:TO-92B 1,2,3
.PARAM QZTX790A File:Zetex.lib

*ZTX Si 1W 70V 2A 100MHz pkg:TO-92B 1,2,3
.PARAM QZTX792A File:Zetex.lib

*ZTX Si 1W 140V 500mA 100MHz pkg:TO-92B 1,2,3
.PARAM QZTX795A File:Zetex.lib

*ZTX Si 1W 200V 500mA 100MHz pkg:TO-92B 1,2,3
.PARAM QZTX796A File:Zetex.lib

*ZTX Si 1.2W 20V 4.5A 80MHz pkg:TO-92B 1,2,3
.PARAM QZTX948 File:Zetex.lib

*ZTX Si 1.2W 30V 4.5A 100MHz pkg:TO-92B 1,2,3
.PARAM QZTX949 File:Zetex.lib

*ZTX Si 1.2W 60V 4A 120MHz pkg:TO-92B 1,2,3
.PARAM QZTX951 File:Zetex.lib

*ZTX Si 1.2W 100V 3.5A 125MHz pkg:TO-92B 1,2,3
.PARAM QZTX953 File:Zetex.lib

*ZTX Si 1.2W 140V 3A 110MHz pkg:TO-92B 1,2,3
.PARAM QZTX955 File:Zetex.lib

*ZTX Si 1.2W 200V 2A 110MHz pkg:TO-92B 1,2,3
.PARAM QZTX956 File:Zetex.lib

*ZTX Si 1.2W 300V 1A 85MHz pkg:TO-92B 1,2,3
.PARAM QZTX957 File:Zetex.lib

*ZTX Si 1.2W 400V 500mA 85MHz pkg:TO-92B 1,2,3
.PARAM QZTX958 File:Zetex.lib

*ZTX Si 1.2W 12V 4.5A 85MHz pkg:TO-92B 1,2,3
.PARAM QZTX968 File:Zetex.lib

*==============================================
*Motorola

*MOT Si 333mW 10V 70mA 3.5GHz pkg:SOT-23 1,3,2
.PARAM XMMBR521 File:Motbjt.lib

*=======================================
*Harris Semiconductor

*HAR Si 600mW 12V 40mA 8GHz UHFArray pkg:SO-16 (A:2,4,3)(B:6,8,7)(C:11,9,10)(D:12,14,13)(E:1,15,16) 
.PARAM XHFA3128 File:Harris.lib

*=======================================
*National Semiconductor

*NS Si 625mW 60V 800mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QPN2907A/NS File:Nsbjt.lib

*NS Si 350mW 60V 800mA 200MHz GenPurp alias:QPN2907A/NS pkg:SOT-23 1,3,2
.PARAM AMMBT2907A/NS

*NS Si 1W 60V 800mA 200MHz GenPurp alias:QPN2907A/NS pkg:SOT-223 2,1,3
.PARAM APZT2907A/NS

*NS Si 1W 60V 800mA 200MHz GenPurp alias:QPN2907A/NS pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM AMMPQ2907/NS

*NS Si 625mW 40V 200mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N3906/NS File:Nsbjt.lib

*NS Si 350mW 40V 200mA 250MHz GenPurp alias:Q2N3906/NS pkg:SOT-23 1,3,2
.PARAM AMMBT3906/NS

*NS Si 1W 40V 200mA 250MHz GenPurp alias:Q2N3906/NS pkg:SOT-223 2,1,3
.PARAM APZT3906/NS

*NS Si 1W 40V 200mA 250MHz GenPurp alias:Q2N3906/NS pkg:SMD16A (A:1,15,16)(B:3,13,14)(C:5,11,12)(D:7,9,10)
.PARAM AMMPQ3906/NS

*NS Si 350mW 12V 200mA 700MHz Switching pkg:TO-92B 1,2,3
.PARAM QPN4258/NS File:Nsbjt.lib

*NS Si 225mW 12V 200mA 700MHz Switching alias:PN4258/NS pkg:SOT-23 1,3,2
.PARAM AMMBT4258/NS

*NS Si 625mW 50V 100mA 40MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5086/NS File:Nsbjt.lib

*NS Si 350mW 50V 100mA 40MHz GenPurp alias:Q2N5086/NS pkg:SOT-23 1,3,2
.PARAM AMMBT5086/NS

*NS Si 625mW 150V 200mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5401/NS File:Nsbjt.lib

*NS Si 350mW 150V 200mA 200MHz GenPurp alias:Q2N5401/NS pkg:SOT-23 1,3,2
.PARAM AMMBT5401/NS

*NS Si 625mW 80V 500mA 50MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPSA56/NS File:Nsbjt.lib

*NS Si 350mW 80V 500mA 50MHz GenPurp alias:QMPSA56/NS pkg:SOT-23 1,3,2
.PARAM AMMBTA56/NS

*NS Si 1W 80V 500mA 50MHz GenPurp alias:QMPSA56/NS pkg:SOT-223 2,1,3
.PARAM APZTA56/NS

*NS Si 625mW 300V 100mA 50MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QMPSA92/NS File:Nsbjt.lib

*NS Si 350mW 300V 100mA 50MHz HiVolt alias:QMPSA92/NS pkg:SOT-23 1,3,2
.PARAM AMMBTA92/NS

*NS Si 1W 300V 100mA 50MHz HiVolt alias:QMPSA92/NS pkg:SOT-223 2,1,3
.PARAM APZTA92/NS

*NS Si 350mW 40V 800mA 200MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBSR15/NS File:Nsbjt.lib

*NS Si 350mW 40V 200mA 250MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBSR18A/NS File:Nsbjt.lib

*NS Si 350mW 100V 200mA 50MHz GenPurp pkg:SOT-23 1,3,2
.PARAM QBSS63/NS File:Nsbjt.lib
