*===============================
*Schottky Diode Pinout: 1=A, 2=K
*===============================

*Default schottky diode parameters pkg:DO-41 1,2
.PARAM DSKYDIODE~ File:Mcediode.lib

*MCE 30V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ03 File:Mcediode.lib

*MCE 40V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ04 File:Mcediode.lib

*MCE 50V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ05 File:Mcediode.lib

*MCE 60V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ06 File:Mcediode.lib

*MCE 90V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ09 File:Mcediode.lib

*MCE 100V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ10 File:Mcediode.lib

*MCE 40V 30A pkg:DIODE0.4 A,K
.PARAM D1N5828 File:Mcediode.lib

*MCE 40V 60A pkg:DIODE0.4 A,K
.PARAM D1N5834 File:Mcediode.lib

*MCE 30V 25A pkg:DIODE0.4 A,K
.PARAM D1N6095 File:Mcediode.lib

*MCE 40V 25A pkg:DIODE0.4 A,K
.PARAM D1N6096 File:Mcediode.lib

*MCE 30V 50A pkg:DIODE0.4 A,K
.PARAM D1N6097 File:Mcediode.lib

*MCE 40V 50A pkg:DIODE0.4 A,K
.PARAM D1N6098 File:Mcediode.lib

*MCE 45V 25A pkg:DIODE0.4 A,K
.PARAM D1N6391 File:Mcediode.lib

*MCE 45V 60A pkg:DIODE0.4 A,K
.PARAM D1N6392 File:Mcediode.lib

*MCE 40V 1.1A 3us pkg:D0213AA/KA 2,1
.PARAM D10MQ040 File:Mcediode.lib

*MCE 60V .77A 3us pkg:D0213AA/KA 2,1
.PARAM D10MQ060 File:Mcediode.lib

*MCE 90V .77A 3us pkg:D0213AA/KA 2,1
.PARAM D10MQ090 File:Mcediode.lib

*MCE 40V 1.7A 3us pkg:D0213AA/KA 2,1
.PARAM D15MQ040 File:Mcediode.lib

*MCE 15V 1A 3us pkg:D0213AB/KA 2,1
.PARAM D10BQ015 File:Mcediode.lib

*MCE 40V 1A 3us pkg:D0213AB/KA 2,1
.PARAM D10BQ040 File:Mcediode.lib

*MCE 60V 1A 3us pkg:D0213AB/KA 2,1
.PARAM D10BQ060 File:Mcediode.lib

*MCE 100V 1A 3us pkg:D0213AB/KA 2,1
.PARAM D10BQ100 File:Mcediode.lib

*MCE 15V 3A 3us pkg:D0214AB/KA 2,1
.PARAM D30BQ015 File:Mcediode.lib

*MCE 40V 3A 3us pkg:D0214AB/KA 2,1
.PARAM D30BQ040 File:Mcediode.lib

*MCE 60V 3A 3us pkg:D0214AB/KA 2,1
.PARAM D30BQ060 File:Mcediode.lib

*MCE 100V 3A 3us pkg:D0214AB/KA 2,1
.PARAM D30BQ100 File:Mcediode.lib

*MCE 30V 3.3A 3us pkg:DPAK 3,2
.PARAM D30WQ03F File:Mcediode.lib

*MCE 40V 3.3A 3us pkg:DPAK 3,2
.PARAM D30WQ04F File:Mcediode.lib

*MCE 50V 3.3A 3us pkg:DPAK 3,2
.PARAM D30WQ05F File:Mcediode.lib

*MCE 60V 3.3A 3us pkg:DPAK 3,2
.PARAM D30WQ06F File:Mcediode.lib

*MCE 90V 3.3A 3us pkg:DPAK 3,2
.PARAM D30WQ09F File:Mcediode.lib

*MCE 100V 3.3A 3us pkg:DPAK 3,2
.PARAM D30WQ10F File:Mcediode.lib

*MCE 30V 5.5A 3us pkg:DPAK 3,2
.PARAM D50WQ03F File:Mcediode.lib

*MCE 40V 5.5A 3us pkg:DPAK 3,2
.PARAM D50WQ04F File:Mcediode.lib

*MCE 50V 5.5A 3us pkg:DPAK 3,2
.PARAM D50WQ05F File:Mcediode.lib

*MCE 60V 5.5A 3us pkg:DPAK 3,2
.PARAM D50WQ06F File:Mcediode.lib

*MCE 90V 5.5A 3us pkg:DPAK 3,2
.PARAM D50WQ09F File:Mcediode.lib

*MCE 100V 5.5A 3us pkg:DPAK 3,2
.PARAM D50WQ10F File:Mcediode.lib

*MCE 35V 6A 3us pkg:D2PAK 3,1
.PARAM D6TQ035S File:Mcediode.lib

*MCE 45V 6A 3us pkg:D2PAK 3,1
.PARAM D6TQ045S File:Mcediode.lib

*MCE 80V 8A 3us pkg:D2PAK 3,1
.PARAM D8TQ080S File:Mcediode.lib

*MCE 100V 8A 3us pkg:D2PAK 3,1
.PARAM D8TQ100S File:Mcediode.lib

*MCE 35V 10A 3us pkg:D2PAK 3,1
.PARAM D10TQ035S File:Mcediode.lib

*MCE 45V 10A 3us pkg:D2PAK 3,1
.PARAM D10TQ045S File:Mcediode.lib

*MCE 35V 15A 3us pkg:D2PAK 3,1
.PARAM D12TQ035S File:Mcediode.lib

*MCE 45V 15A 3us pkg:D2PAK 3,1
.PARAM D12TQ045S File:Mcediode.lib

*MCE 35V 18A 3us pkg:D2PAK 3,1
.PARAM D18TQ035S File:Mcediode.lib

*MCE 45V 18A 3us pkg:D2PAK 3,1
.PARAM D18TQ045S File:Mcediode.lib

*MCE 15V 19A 3us pkg:D2PAK 3,1
.PARAM D19TQ015S File:Mcediode.lib

*MCE 35V 20A 3us pkg:D2PAK 3,1
.PARAM D20TQ035S File:Mcediode.lib

*MCE 45V 20A 3us pkg:D2PAK 3,1
.PARAM D20TQ045S File:Mcediode.lib

*MCE 30V 3.3A 3us pkg:DIODE0.7 A,K
.PARAM D31DQ03 File:Mcediode.lib

*MCE 40V 3.3A 3us pkg:DIODE0.7 A,K
.PARAM D31DQ04 File:Mcediode.lib

*MCE 50V 3.3A 3us pkg:DIODE0.7 A,K
.PARAM D31DQ05 File:Mcediode.lib

*MCE 60V 3.3A 3us pkg:DIODE0.7 A,K
.PARAM D31DQ06 File:Mcediode.lib

*MCE 90V 3.3A 3us pkg:DIODE0.7 A,K
.PARAM D31DQ09 File:Mcediode.lib

*MCE 100V 3.3A 3us pkg:DIODE0.7 A,K
.PARAM D31DQ10 File:Mcediode.lib

*MCE 80V 5A 3us pkg:DIODE0.7 A,K
.PARAM D50SQ080 File:Mcediode.lib

*MCE 100V 5A 3us pkg:DIODE0.7 A,K
.PARAM D50SQ100 File:Mcediode.lib

*MCE 35V 8A 3us pkg:DIODE0.7 A,K
.PARAM D80SQ035 File:Mcediode.lib

*MCE 40V 8A 3us pkg:DIODE0.7 A,K
.PARAM D80SQ040 File:Mcediode.lib

*MCE 45V 8A 3us pkg:DIODE0.7 A,K
.PARAM D80SQ045 File:Mcediode.lib

*MCE 35V 9A 3us pkg:DIODE0.7 A,K
.PARAM D90SQ035 File:Mcediode.lib

*MCE 40V 9A 3us pkg:DIODE0.7 A,K
.PARAM D90SQ040 File:Mcediode.lib

*MCE 45V 9A 3us pkg:DIODE0.7 A,K
.PARAM D90SQ045 File:Mcediode.lib

*MCE 15V 9A 3us pkg:DIODE0.7 A,K
.PARAM D95SQ015 File:Mcediode.lib

*MCE 35V 6A 3us pkg:TO-220 3,1
.PARAM D6TQ035 File:Mcediode.lib

*MCE 40V 6A 3us pkg:TO-220 3,1
.PARAM D6TQ040 File:Mcediode.lib

*MCE 45V 6A 3us pkg:TO-220 3,1
.PARAM D6TQ045 File:Mcediode.lib

*MCE 35V 7.5A 3us pkg:TO-220 3,1
.PARAM DMBR735 File:Mcediode.lib

*MCE 45V 7.5A 3us pkg:TO-220 3,1
.PARAM DMBR745 File:Mcediode.lib

*MCE 80V 8A 3us pkg:TO-220 3,1
.PARAM D8TQ080 File:Mcediode.lib

*MCE 100V 8A 3us pkg:TO-220 3,1
.PARAM D8TQ100 File:Mcediode.lib

*MCE 35V 10A 3us pkg:TO-220 3,1
.PARAM DMBR1035 File:Mcediode.lib

*MCE 45V 10A 3us pkg:TO-220 3,1
.PARAM DMBR1045 File:Mcediode.lib

*MCE 35V 10A 3us pkg:TO-220 3,1
.PARAM D10TQ035 File:Mcediode.lib

*MCE 40V 10A 3us pkg:TO-220 3,1
.PARAM D10TQ040 File:Mcediode.lib

*MCE 45V 10A 3us pkg:TO-220 3,1
.PARAM D10TQ045 File:Mcediode.lib

*MCE 35V 15A 3us pkg:TO-220 3,1
.PARAM D12TQ035 File:Mcediode.lib

*MCE 40V 15A 3us pkg:TO-220 3,1
.PARAM D12TQ040 File:Mcediode.lib

*MCE 45V 15A 3us pkg:TO-220 3,1
.PARAM D12TQ045 File:Mcediode.lib

*MCE 35V 16A 3us pkg:TO-220 3,1
.PARAM DMBR1635 File:Mcediode.lib

*MCE 45V 16A 3us pkg:TO-220 3,1
.PARAM DMBR1645 File:Mcediode.lib

*MCE 35V 18A 3us pkg:TO-220 3,1
.PARAM D18TQ035 File:Mcediode.lib

*MCE 40V 18A 3us pkg:TO-220 3,1
.PARAM D18TQ040 File:Mcediode.lib

*MCE 45V 18A 3us pkg:TO-220 3,1
.PARAM D18TQ045 File:Mcediode.lib

*MCE 15V 19A 3us pkg:TO-220 3,1
.PARAM D19TQ015 File:Mcediode.lib

*MCE 35V 20A 3us pkg:TO-220 3,1
.PARAM D20TQ035 File:Mcediode.lib

*MCE 40V 20A 3us pkg:TO-220 3,1
.PARAM D20TQ040 File:Mcediode.lib

*MCE 45V 20A 3us pkg:TO-220 3,1
.PARAM D20TQ045 File:Mcediode.lib

*MCE 35V 30A 3us pkg:DIODE0.7 A,K
.PARAM DSD41 File:Mcediode.lib

*MCE 35V 30A 3us pkg:DIODE0.7 A,K
.PARAM D20FQ035 File:Mcediode.lib

*MCE 40V 30A 3us pkg:DIODE0.7 A,K
.PARAM D20FQ040 File:Mcediode.lib

*MCE 45V 30A 3us pkg:DIODE0.7 A,K
.PARAM D20FQ045 File:Mcediode.lib

*MCE 35V 30A 3us pkg:DIODE0.7 A,K
.PARAM D21FQ035 File:Mcediode.lib

*MCE 40V 30A 3us pkg:DIODE0.7 A,K
.PARAM D21FQ040 File:Mcediode.lib

*MCE 45V 30A 3us pkg:DIODE0.7 A,K
.PARAM D21FQ045 File:Mcediode.lib

*MCE 35V 30A 3us pkg:DIODE0.7 A,K
.PARAM D30FQ035 File:Mcediode.lib

*MCE 40V 30A 3us pkg:DIODE0.7 A,K
.PARAM D30FQ040 File:Mcediode.lib

*MCE 45V 30A 3us pkg:DIODE0.7 A,K
.PARAM D30FQ045 File:Mcediode.lib

*MCE 35V 60A 3us pkg:DIODE0.7 A,K
.PARAM DSD51 File:Mcediode.lib

*MCE 35V 60A 3us pkg:DIODE0.7 A,K
.PARAM D50HQ035 File:Mcediode.lib

*MCE 40V 60A 3us pkg:DIODE0.7 A,K
.PARAM D50HQ040 File:Mcediode.lib

*MCE 45V 60A 3us pkg:DIODE0.7 A,K
.PARAM D50HQ045 File:Mcediode.lib

*MCE 35V 60A 3us pkg:DIODE0.7 A,K
.PARAM D51HQ035 File:Mcediode.lib

*MCE 40V 60A 3us pkg:DIODE0.7 A,K
.PARAM D51HQ040 File:Mcediode.lib

*MCE 45V 60A 3us pkg:DIODE0.7 A,K
.PARAM D51HQ045 File:Mcediode.lib

*MCE 30V 60A 3us pkg:DIODE0.7 A,K
.PARAM D55HQ030 File:Mcediode.lib

*MCE 80V 60A 3us pkg:DIODE0.7 A,K
.PARAM D60HQ080 File:Mcediode.lib

*MCE 100V 60A 3us pkg:DIODE0.7 A,K
.PARAM D60HQ100 File:Mcediode.lib

*MCE 35V 75A 3us pkg:DIODE0.7 A,K
.PARAM D75HQ035 File:Mcediode.lib

*MCE 40V 75A 3us pkg:DIODE0.7 A,K
.PARAM D75HQ040 File:Mcediode.lib

*MCE 45V 75A 3us pkg:DIODE0.7 A,K
.PARAM D75HQ045 File:Mcediode.lib

*MCE 35V 75A 3us pkg:DIODE0.7 A,K
.PARAM DMBR7535 File:Mcediode.lib

*MCE 45V 75A 3us pkg:DIODE0.7 A,K
.PARAM DMBR7545 File:Mcediode.lib

*MCE 35V 85A 3us pkg:DIODE0.7 A,K
.PARAM D85HQ035 File:Mcediode.lib

*MCE 40V 85A 3us pkg:DIODE0.7 A,K
.PARAM D85HQ040 File:Mcediode.lib

*MCE 45V 85A 3us pkg:DIODE0.7 A,K
.PARAM D85HQ045 File:Mcediode.lib

*MCE 15V 95A 3us pkg:DIODE0.7 A,K
.PARAM D95HQ015 File:Mcediode.lib

*MCE 35V 120A 3us pkg:DIODE0.7 A,K
.PARAM D120NQ035 File:Mcediode.lib

*MCE 40V 120A 3us pkg:DIODE0.7 A,K
.PARAM D120NQ040 File:Mcediode.lib

*MCE 45V 120A 3us pkg:DIODE0.7 A,K
.PARAM D120NQ045 File:Mcediode.lib

*MCE 45V 120A 3us pkg:DIODE0.7 A,K
.PARAM D120NQ045R File:Mcediode.lib

*MCE 35V 120A 3us pkg:DIODE0.7 A,K
.PARAM D121NQ035 File:Mcediode.lib

*MCE 40V 120A 3us pkg:DIODE0.7 A,K
.PARAM D121NQ040 File:Mcediode.lib

*MCE 45V 120A 3us pkg:DIODE0.7 A,K
.PARAM D121NQ045 File:Mcediode.lib

*MCE 45V 120A 3us pkg:DIODE0.7 A,K
.PARAM D121NQ045R File:Mcediode.lib

*MCE 30V 120A 3us pkg:DIODE0.7 A,K
.PARAM D122NQ030 File:Mcediode.lib

*MCE 30V 120A 3us pkg:DIODE0.7 A,K
.PARAM D122NQ030R File:Mcediode.lib

*MCE 80V 120A 3us pkg:DIODE0.7 A,K
.PARAM D123NQ080 File:Mcediode.lib

*MCE 100V 120A 3us pkg:DIODE0.7 A,K
.PARAM D123NQ100 File:Mcediode.lib

*MCE 100V 120A 3us pkg:DIODE0.7 A,K
.PARAM D123NQ100R File:Mcediode.lib

*MCE 35V 120A 3us pkg:DIODE0.7 A,K
.PARAM D124NQ035 File:Mcediode.lib

*MCE 40V 120A 3us pkg:DIODE0.7 A,K
.PARAM D124NQ040 File:Mcediode.lib

*MCE 45V 120A 3us pkg:DIODE0.7 A,K
.PARAM D124NQ045 File:Mcediode.lib

*MCE 45V 120A 3us pkg:DIODE0.7 A,K
.PARAM D124NQ045R File:Mcediode.lib

*MCE 15V 120A 3us pkg:DIODE0.7 A,K
.PARAM D125NQ015 File:Mcediode.lib

*MCE 15V 120A 3us pkg:DIODE0.7 A,K
.PARAM D125NQ015R File:Mcediode.lib

*MCE 60V 120A 3us pkg:DIODE0.7 A,K
.PARAM D128NQ060 File:Mcediode.lib

*MCE 60V 120A 3us pkg:DIODE0.7 A,K
.PARAM D128NQ060R File:Mcediode.lib

*MCE 150V 120A 3us pkg:DIODE0.7 A,K
.PARAM D129NQ150 File:Mcediode.lib

*MCE 150V 120A 3us pkg:DIODE0.7 A,K
.PARAM D129NQ150R File:Mcediode.lib

*MCE 35V 180A 3us pkg:DIODE0.7 A,K
.PARAM D180NQ035 File:Mcediode.lib

*MCE 40V 180A 3us pkg:DIODE0.7 A,K
.PARAM D180NQ040 File:Mcediode.lib

*MCE 45V 180A 3us pkg:DIODE0.7 A,K
.PARAM D180NQ045 File:Mcediode.lib

*MCE 45V 180A 3us pkg:DIODE0.7 A,K
.PARAM D180NQ045R File:Mcediode.lib

*MCE 35V 180A 3us pkg:DIODE0.7 A,K
.PARAM D181NQ035 File:Mcediode.lib

*MCE 40V 180A 3us pkg:DIODE0.7 A,K
.PARAM D181NQ040 File:Mcediode.lib

*MCE 45V 180A 3us pkg:DIODE0.7 A,K
.PARAM D181NQ045 File:Mcediode.lib

*MCE 45V 180A 3us pkg:DIODE0.7 A,K
.PARAM D181NQ045R File:Mcediode.lib

*MCE 30V 180A 3us pkg:DIODE0.7 A,K
.PARAM D182NQ030 File:Mcediode.lib

*MCE 30V 180A 3us pkg:DIODE0.7 A,K
.PARAM D182NQ030R File:Mcediode.lib

*MCE 80V 180A 3us pkg:DIODE0.7 A,K
.PARAM D183NQ080 File:Mcediode.lib

*MCE 100V 180A 3us pkg:DIODE0.7 A,K
.PARAM D183NQ100 File:Mcediode.lib

*MCE 100V 180A 3us pkg:DIODE0.7 A,K
.PARAM D183NQ100R File:Mcediode.lib

*MCE 15V 180A 3us pkg:DIODE0.7 A,K
.PARAM D185NQ015 File:Mcediode.lib

*MCE 15V 180A 3us pkg:DIODE0.7 A,K
.PARAM D185NQ015R File:Mcediode.lib

*MCE 60V 180A 3us pkg:DIODE0.7 A,K
.PARAM D188NQ060 File:Mcediode.lib

*MCE 60V 180A 3us pkg:DIODE0.7 A,K
.PARAM D188NQ060R File:Mcediode.lib

*MCE 150V 180A 3us pkg:DIODE0.7 A,K
.PARAM D189NQ150 File:Mcediode.lib

*MCE 150V 180A 3us pkg:DIODE0.7 A,K
.PARAM D189NQ150R File:Mcediode.lib

*MCE 35V 240A 3us pkg:DIODE0.7 A,K
.PARAM D240NQ035 File:Mcediode.lib

*MCE 40V 240A 3us pkg:DIODE0.7 A,K
.PARAM D240NQ040 File:Mcediode.lib

*MCE 45V 240A 3us pkg:DIODE0.7 A,K
.PARAM D240NQ045 File:Mcediode.lib

*MCE 45V 240A 3us pkg:DIODE0.7 A,K
.PARAM D240NQ045R File:Mcediode.lib

*MCE 35V 240A 3us pkg:DIODE0.7 A,K
.PARAM D241NQ035 File:Mcediode.lib

*MCE 40V 240A 3us pkg:DIODE0.7 A,K
.PARAM D241NQ040 File:Mcediode.lib

*MCE 45V 240A 3us pkg:DIODE0.7 A,K
.PARAM D241NQ045 File:Mcediode.lib

*MCE 45V 240A 3us pkg:DIODE0.7 A,K
.PARAM D241NQ045R File:Mcediode.lib

*MCE 30V 240A 3us pkg:DIODE0.7 A,K
.PARAM D242NQ030 File:Mcediode.lib

*MCE 30V 240A 3us pkg:DIODE0.7 A,K
.PARAM D242NQ030R File:Mcediode.lib

*MCE 80V 240A 3us pkg:DIODE0.7 A,K
.PARAM D243NQ080 File:Mcediode.lib

*MCE 100V 240A 3us pkg:DIODE0.7 A,K
.PARAM D243NQ100 File:Mcediode.lib

*MCE 100V 240A 3us pkg:DIODE0.7 A,K
.PARAM D243NQ100R File:Mcediode.lib

*MCE 35V 240A 3us pkg:DIODE0.7 A,K
.PARAM D244NQ035 File:Mcediode.lib

*MCE 40V 240A 3us pkg:DIODE0.7 A,K
.PARAM D244NQ040 File:Mcediode.lib

*MCE 45V 240A 3us pkg:DIODE0.7 A,K
.PARAM D244NQ045 File:Mcediode.lib

*MCE 45V 240A 3us pkg:DIODE0.7 A,K
.PARAM D244NQ045R File:Mcediode.lib

*MCE 15V 240A 3us pkg:DIODE0.7 A,K
.PARAM D245NQ015 File:Mcediode.lib

*MCE 15V 240A 3us pkg:DIODE0.7 A,K
.PARAM D245NQ015R File:Mcediode.lib

*MCE 60V 240A 3us pkg:DIODE0.7 A,K
.PARAM D248NQ060 File:Mcediode.lib

*MCE 60V 240A 3us pkg:DIODE0.7 A,K
.PARAM D248NQ060R File:Mcediode.lib

*MCE 150V 240A 3us pkg:DIODE0.7 A,K
.PARAM D249NQ150 File:Mcediode.lib

*MCE 150V 240A 3us pkg:DIODE0.7 A,K
.PARAM D249NQ150R File:Mcediode.lib

