*==============================================
*Varactor Diode Pinout: 1=A, 2=K
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*==============================================
*Zetex

*ZTX 28V Cd=1.80pF/2.80pF Si pkg:SOT-23 3,1
.PARAM DBBY31 File:Zetex.lib

*ZTX 28V Cd=4.30pF/6.00pF Si pkg:SOT-23 3,1
.PARAM DBBY40 File:Zetex.lib

*ZTX 30V Cd=1.80pF/2.80pF Q=250 Si pkg:SOT-23 3,1
.PARAM DFMMV105G File:Zetex.lib

*ZTX 30V Cd=26.0pF/32.0pF Q=250 Si pkg:SOT-23 3,1
.PARAM DFMMV109 File:Zetex.lib

*ZTX 30V Cd=6.10pF/7.50pF Q=450 Si pkg:SOT-23 3,1
.PARAM DFMMV2101 File:Zetex.lib

*ZTX 30V Cd=7.30pF/9.00pF Q=450 Si pkg:SOT-23 3,1
.PARAM DFMMV2102 File:Zetex.lib

*ZTX 30V Cd=9.00pF/11.0pF Q=400 Si pkg:SOT-23 3,1
.PARAM DFMMV2103 File:Zetex.lib

*ZTX 30V Cd=10.8pF/13.2pF Q=400 Si pkg:SOT-23 3,1
.PARAM DFMMV2104 File:Zetex.lib

*ZTX 30V Cd=13.5pF/16.5pF Q=400 Si pkg:SOT-23 3,1
.PARAM DFMMV2105 File:Zetex.lib

*ZTX 30V Cd=16.2pF/19.8pF Q=350 Si pkg:SOT-23 3,1
.PARAM DFMMV2106 File:Zetex.lib

*ZTX 30V Cd=19.8pF/24.2pF Q=350 Si pkg:SOT-23 3,1
.PARAM DFMMV2107 File:Zetex.lib

*ZTX 30V Cd=24.3pF/29.7pF Q=300 Si pkg:SOT-23 3,1
.PARAM DFMMV2108 File:Zetex.lib

*ZTX 30V Cd=29.3pF/36.3pF Q=280 Si pkg:SOT-23 3,1
.PARAM DFMMV2109 File:Zetex.lib

*ZTX 30V Cd=20.0pF/25.0pF Q=200 Si pkg:SOT-23 3,1
.PARAM DFMMV3102 File:Zetex.lib

*ZTX 25V Cd=8.00pF/12.0pF Q=300 Si pkg:SOT-23 3,1
.PARAM DZC820A File:Zetex.lib

*ZTX 25V Cd=12.0pF/18.0pF Q=300 Si pkg:SOT-23 3,1
.PARAM DZC821A File:Zetex.lib

*ZTX 25V Cd=17.6pF/26.4pF Q=200 Si pkg:SOT-23 3,1
.PARAM DZC822A File:Zetex.lib

*ZTX 25V Cd=26.4pF/39.6pF Q=200 Si pkg:SOT-23 3,1
.PARAM DZC823A File:Zetex.lib

*ZTX 25V Cd=37.6pF/56.4pF Q=200 Si pkg:SOT-23 3,1
.PARAM DZC824A File:Zetex.lib

*ZTX 25V Cd=54.4pF/81.6pF Q=100 Si pkg:SOT-23 3,1
.PARAM DZC825A File:Zetex.lib

*ZTX 25V Cd=80.0pF/120.pF Q=100 Si pkg:SOT-23 3,1
.PARAM DZC826A File:Zetex.lib

*ZTX 25V Cd=9.00pF/11.0pF Q=300 Si pkg:SOT-23 3,1
.PARAM DZC830A File:Zetex.lib

*ZTX 25V Cd=13.5pF/16.5pF Q=300 Si pkg:SOT-23 3,1
.PARAM DZC831A File:Zetex.lib

*ZTX 25V Cd=19.8pF/24.2pF Q=200 Si pkg:SOT-23 3,1
.PARAM DZC832A File:Zetex.lib

*ZTX 25V Cd=29.7pF/36.3pF Q=200 Si pkg:SOT-23 3,1
.PARAM DZC833A File:Zetex.lib

*ZTX 25V Cd=42.3pF/51.7pF Q=200 Si pkg:SOT-23 3,1
.PARAM DZC834A File:Zetex.lib

*ZTX 25V Cd=61.2pF/74.8pF Q=100 Si pkg:SOT-23 3,1
.PARAM DZC835A File:Zetex.lib

*ZTX 25V Cd=90.0pF/110.pF Q=100 Si pkg:SOT-23 3,1
.PARAM DZC836A File:Zetex.lib
