*==============================================
*Zener Diode Pinout 1=A, 2=K
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*Default Zener 10V @ 10mA pkg:DIODE0.4 A,K
.PARAM DZENER~ File:Mcediode.lib

*3.3V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N746 File:Mcediode.lib

*3.6V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N747 File:Mcediode.lib

*3.9V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N748 File:Mcediode.lib

*4.3V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N749 File:Mcediode.lib

*4.7V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N750 File:Mcediode.lib

*5.1V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N751 File:Mcediode.lib

*5.6V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N752 File:Mcediode.lib

*6.2V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N753 File:Mcediode.lib

*6.8V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N754 File:Mcediode.lib

*7.5V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N755 File:Mcediode.lib

*8.2V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N756 File:Mcediode.lib

*9.1V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N757 File:Mcediode.lib

*10V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N758 File:Mcediode.lib

*12V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N759 File:Mcediode.lib

*3.3V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4728 File:Mcediode.lib

*3.6V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4729 File:Mcediode.lib

*3.9V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4730 File:Mcediode.lib

*4.3V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4731 File:Mcediode.lib

*4.7V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4732 File:Mcediode.lib

*5.1V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4733 File:Mcediode.lib

*5.6V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4734 File:Mcediode.lib

*6.2V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4735 File:Mcediode.lib

*6.8V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4736 File:Mcediode.lib

*7.5V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4737 File:Mcediode.lib

*8.2V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4738 File:Mcediode.lib

*9.1V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4739 File:Mcediode.lib

*10V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4740 File:Mcediode.lib

*11V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4741 File:Mcediode.lib

*12V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4742 File:Mcediode.lib

*13V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4743 File:Mcediode.lib

*15V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4744 File:Mcediode.lib

*16V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4745 File:Mcediode.lib

*18V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4746 File:Mcediode.lib

*20V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4747 File:Mcediode.lib

*22V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4748 File:Mcediode.lib

*24V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4749 File:Mcediode.lib

*27V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4750 File:Mcediode.lib

*30V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4751 File:Mcediode.lib

*33V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4752 File:Mcediode.lib

*36V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4753 File:Mcediode.lib

*39V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4754 File:Mcediode.lib

*43V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4755 File:Mcediode.lib

*47V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4756 File:Mcediode.lib

*51V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4757 File:Mcediode.lib

*56V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4758 File:Mcediode.lib

*62V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4759 File:Mcediode.lib

*68V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4760 File:Mcediode.lib

*75V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4761 File:Mcediode.lib

*82V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4762 File:Mcediode.lib

*91V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4763 File:Mcediode.lib

*100V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4764 File:Mcediode.lib

*6.8V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5342B File:Mcediode.lib

*8.2V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5344B File:Mcediode.lib

*9.1V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5346B File:Mcediode.lib

*11V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5348B File:Mcediode.lib

*13V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5350B File:Mcediode.lib

*14V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5351B File:Mcediode.lib

*16V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5353B File:Mcediode.lib

*18V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5355B File:Mcediode.lib

*20V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5357B File:Mcediode.lib

*24V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5359B File:Mcediode.lib

*27V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5361B File:Mcediode.lib

*30V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5363B File:Mcediode.lib

*36V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5365B File:Mcediode.lib

*43V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5367B File:Mcediode.lib

*51V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5369B File:Mcediode.lib

*60V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5371B File:Mcediode.lib

*68V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5373B File:Mcediode.lib

*82V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5375B File:Mcediode.lib

*91V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5377B File:Mcediode.lib

*110V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5379B File:Mcediode.lib

*130V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5381B File:Mcediode.lib

*150V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5383B File:Mcediode.lib

*170V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5385B File:Mcediode.lib

*190V 5W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N5387B File:Mcediode.lib

*3.3V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N746A   File:Mcediode.lib

*3.6V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N747A   File:Mcediode.lib

*3.9V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N748A   File:Mcediode.lib

*4.3V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N749A   File:Mcediode.lib

*4.7V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N750A   File:Mcediode.lib

*5.1V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N751A   File:Mcediode.lib

*5.6V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N752A   File:Mcediode.lib

*6.2V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N753A   File:Mcediode.lib

*6.8V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N754A   File:Mcediode.lib

*7.5V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N755A   File:Mcediode.lib

*8.2V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N756A   File:Mcediode.lib

*9.1V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N757A   File:Mcediode.lib

*10V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N758A   File:Mcediode.lib

*12V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N759A   File:Mcediode.lib

*6.8V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N957B   File:Mcediode.lib

*7.5V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N958B   File:Mcediode.lib

*8.2V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N959B   File:Mcediode.lib

*9.1V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N960B   File:Mcediode.lib

*10V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N961B   File:Mcediode.lib

*11V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N962B   File:Mcediode.lib

*12V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N963B    File:Mcediode.lib

*13V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N964B   File:Mcediode.lib

*15V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N965B   File:Mcediode.lib

*16V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N966B   File:Mcediode.lib

*18V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N967B   File:Mcediode.lib

*20V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N968B   File:Mcediode.lib

*22V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N969B   File:Mcediode.lib

*24V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N970B   File:Mcediode.lib

*27V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N971B   File:Mcediode.lib

*30V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N972B   File:Mcediode.lib

*33V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N973B   File:Mcediode.lib

*3.3V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4728A  File:Mcediode.lib

*3.6V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4729A  File:Mcediode.lib

*3.9V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4730A  File:Mcediode.lib

*4.3V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4731A  File:Mcediode.lib

*4.7V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4732A  File:Mcediode.lib

*5.1V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4733A  File:Mcediode.lib

*5.6V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4734A  File:Mcediode.lib

*6.2V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4735A  File:Mcediode.lib

*6.8V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4736A  File:Mcediode.lib

*7.5V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4737A  File:Mcediode.lib

*8.2V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4738A  File:Mcediode.lib

*9.1V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4739A  File:Mcediode.lib

*10V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4740A  File:Mcediode.lib

*11V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4741A  File:Mcediode.lib

*12V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4742A  File:Mcediode.lib

*13V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4743A  File:Mcediode.lib

*15V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4744A  File:Mcediode.lib

*16V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4745A  File:Mcediode.lib

*18V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4746A   File:Mcediode.lib

*20V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4747A  File:Mcediode.lib

*22V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4748A  File:Mcediode.lib

*24V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4749A  File:Mcediode.lib

*27V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4750A  File:Mcediode.lib

*30V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4751B  File:Mcediode.lib

*33V 1W Si pkg:DIODE0.4 A,K
.PARAM X1N4752A  File:Mcediode.lib

*3.3V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5226B  File:Mcediode.lib

*3.6V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5227B  File:Mcediode.lib

*3.9V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5228B  File:Mcediode.lib

*4.3V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N229B   File:Mcediode.lib

*4.7V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5230B  File:Mcediode.lib

*5.1V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5231B  File:Mcediode.lib

*5.6V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5232B  File:Mcediode.lib

*6V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5233B  File:Mcediode.lib

*6.2V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5234B  File:Mcediode.lib

*6.8V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5235B  File:Mcediode.lib

*7.5V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5236B  File:Mcediode.lib

*8.2V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5237B  File:Mcediode.lib

*8.7V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5238B  File:Mcediode.lib

*9.1V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5239B  File:Mcediode.lib

*10V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5240B  File:Mcediode.lib

*11V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5241B  File:Mcediode.lib

*12V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5242B  File:Mcediode.lib

*13V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5243B  File:Mcediode.lib

*14V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5244B  File:Mcediode.lib

*15V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5245A  File:Mcediode.lib

*16V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5246B  File:Mcediode.lib

*17V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5247B  File:Mcediode.lib

*18V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5248B  File:Mcediode.lib

*19V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5249B  File:Mcediode.lib

*20V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5250B  File:Mcediode.lib

*22V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5251B  File:Mcediode.lib

*24V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5252B  File:Mcediode.lib

*25V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5253B  File:Mcediode.lib

*27V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5254B  File:Mcediode.lib

*28V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5255B  File:Mcediode.lib

*30V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5256B  File:Mcediode.lib

*33V 500mW Si pkg:DIODE0.4 A,K
.PARAM X1N5257B  File:Mcediode.lib

*2.4V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C2V4LT1 File:Mcediode.lib

*2.7V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C2V7LT1 File:Mcediode.lib

*3V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C3V0LT1 File:Mcediode.lib

*3.3V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C3V3LT1 File:Mcediode.lib

*3.6V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C3V6LT1 File:Mcediode.lib

*3.9V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C3V9LT1 File:Mcediode.lib

*4.3V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C4V3LT1 File:Mcediode.lib

*4.7V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C4V7LT1 File:Mcediode.lib

*5.1V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C5V1LT1 File:Mcediode.lib

*5.6V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C5V6LT1 File:Mcediode.lib

*6.2V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C6V2LT1 File:Mcediode.lib

*6.8V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C6V8LT1 File:Mcediode.lib

*7.5V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C7V5LT1 File:Mcediode.lib

*8.2V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C8V2LT1 File:Mcediode.lib

*9.1V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C9V1LT1 File:Mcediode.lib

*10V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C10LT1 File:Mcediode.lib

*11V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C11LT1 File:Mcediode.lib

*12V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C12LT1 File:Mcediode.lib

*13V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C13LT1 File:Mcediode.lib

*15V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C15LT1 File:Mcediode.lib

*16V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C16LT1 File:Mcediode.lib

*18V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C18LT1 File:Mcediode.lib

*20V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C20LT1 File:Mcediode.lib

*22V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C22LT1 File:Mcediode.lib

*24V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C24LT1 File:Mcediode.lib

*27V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C27LT1 File:Mcediode.lib

*30V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C30LT1 File:Mcediode.lib

*33V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C33LT1 File:Mcediode.lib

*36V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C36LT1 File:Mcediode.lib

*39V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C39LT1 File:Mcediode.lib

*43V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C43LT1 File:Mcediode.lib

*47V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C47LT1 File:Mcediode.lib

*51V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C51LT1 File:Mcediode.lib

*56V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C56LT1 File:Mcediode.lib

*62V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C62L File:Mcediode.lib

*68V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C68LT1 File:Mcediode.lib

*75V 1000mW Si pkg:SOT-23 1,3
.PARAM XBZX84C75LT1 File:Mcediode.lib

*2.4V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5221BLT1 File:Mcediode.lib

*2.5V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5222BLT1 File:Mcediode.lib

*2.7V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5223BLT1 File:Mcediode.lib

*2.8V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5224BLT1 File:Mcediode.lib

*3V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5225BLT1 File:Mcediode.lib

*3.3V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5226BLT1 File:Mcediode.lib

*3.6V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5227BLT1 File:Mcediode.lib

*3.9V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5228BLT1 File:Mcediode.lib

*4.3V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5229BLT1 File:Mcediode.lib

*4.7V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5230BLT1 File:Mcediode.lib

*5.1V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5231BLT1 File:Mcediode.lib

*5.6V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5232BLT1 File:Mcediode.lib

*6V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5233BLT1 File:Mcediode.lib

*6.2V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5234BLT1 File:Mcediode.lib

*6.8V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5235BLT1 File:Mcediode.lib

*7.5V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5236BLT1 File:Mcediode.lib

*8.2V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5237BLT1 File:Mcediode.lib

*8.7V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5258BLT1 File:Mcediode.lib

*9.1V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5259BLT1 File:Mcediode.lib

*10V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5240BLT1 File:Mcediode.lib

*11V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5241BLT1 File:Mcediode.lib

*12V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5242BLT1 File:Mcediode.lib

*13V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5243B File:Mcediode.lib

*14V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5244BLT1 File:Mcediode.lib

*15V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5245BLT1 File:Mcediode.lib

*16V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5246BLT1 File:Mcediode.lib

*17V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5247BLT1 File:Mcediode.lib

*18V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5248BLT1 File:Mcediode.lib

*19V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5249BLT1 File:Mcediode.lib

*20V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5250BLT1 File:Mcediode.lib

*22V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5251BLT1 File:Mcediode.lib

*24V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5252BLT1 File:Mcediode.lib

*25V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5253BLT1 File:Mcediode.lib

*27V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5254BLT1 File:Mcediode.lib

*28V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5255BLT1 File:Mcediode.lib

*30V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5256BLT1 File:Mcediode.lib

*33V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5257BLT1 File:Mcediode.lib

*36V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5258BLT1 File:Mcediode.lib

*39V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5259BLT1 File:Mcediode.lib

*43V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5260BLT1 File:Mcediode.lib

*47V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5261BLT1 File:Mcediode.lib

*51V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5262BLT1 File:Mcediode.lib

*56V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5263BLT1 File:Mcediode.lib

*60V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5264BLT1 File:Mcediode.lib

*62V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5265BLT1 File:Mcediode.lib

*68V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5266BLT1 File:Mcediode.lib

*75V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5267BLT1 File:Mcediode.lib

*82V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5268BLT1 File:Mcediode.lib

*87V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5269BLT1 File:Mcediode.lib

*91V 1000mW Si pkg:SOT-23 1,3
.PARAM XMMBZ5270BLT1 File:Mcediode.lib

*2.4V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ2V4T1 File:Mcediode.lib

*2.7V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ2V7T1 File:Mcediode.lib

*3V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMBZ3V0T1 File:Mcediode.lib

*3.3V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ3V3T1 File:Mcediode.lib

*3.6V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ3V6T1 File:Mcediode.lib

*3.9V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ3V9T1 File:Mcediode.lib

*4.3V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ4V3T1 File:Mcediode.lib

*4.7V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ4V7T1 File:Mcediode.lib

*5.1V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ5V1T1 File:Mcediode.lib

*5.6V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ5V6T1 File:Mcediode.lib

*6.2V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ6V2T1 File:Mcediode.lib

*6.8V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ6V8T1 File:Mcediode.lib

*7.5V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ7V5T1 File:Mcediode.lib

*8.2V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ8V2T1 File:Mcediode.lib

*9.1V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ9V1T1 File:Mcediode.lib

*10V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ10T1 File:Mcediode.lib

*11V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ11T1 File:Mcediode.lib

*12V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ12T1 File:Mcediode.lib

*13V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ13T1 File:Mcediode.lib

*15V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ15T1 File:Mcediode.lib

*16V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ16T1 File:Mcediode.lib

*18V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ18T1 File:Mcediode.lib

*20V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ20T1 File:Mcediode.lib

*22V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ22T1 File:Mcediode.lib

*24V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ24T1 File:Mcediode.lib

*27V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ27T1 File:Mcediode.lib

*30V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ30T1 File:Mcediode.lib

*33V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ33T1 File:Mcediode.lib

*36V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ36T1 File:Mcediode.lib

*39V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ39T1 File:Mcediode.lib

*43V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ43T1 File:Mcediode.lib

*47V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ47T1 File:Mcediode.lib

*51V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ51T1 File:Mcediode.lib

*56V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ56T1 File:Mcediode.lib

*62V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ62T1 File:Mcediode.lib

*68V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ68T1 File:Mcediode.lib

*75V 1000mW Si pkg:SOD-123 1,2
.PARAM XMMSZ75T1 File:Mcediode.lib

*36V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N974B   File:Mcediode.lib

*4.3V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5229B  File:Mcediode.lib

*15V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5245B  File:Mcediode.lib

*36V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5258B  File:Mcediode.lib

*39V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5259B  File:Mcediode.lib

*43V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5260B  File:Mcediode.lib

*47V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5261B  File:Mcediode.lib

*51V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5262B  File:Mcediode.lib

*50V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4751A  File:Mcediode.lib

*36V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4753A  File:Mcediode.lib

*39V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4754A  File:Mcediode.lib

*43V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4755A  File:Mcediode.lib

*47V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4756A  File:Mcediode.lib

*51V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4757A  File:Mcediode.lib

*56V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4758A  File:Mcediode.lib

*62V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4759A  File:Mcediode.lib

*68V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4760A  File:Mcediode.lib

*75V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4761A  File:Mcediode.lib

*82V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4762A  File:Mcediode.lib

*91V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4763A  File:Mcediode.lib

*100V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N4764A  File:Mcediode.lib

*7.5V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5343B  File:Mcediode.lib

*8.7V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5345B  File:Mcediode.lib

*10V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5347B  File:Mcediode.lib

*12V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5349B  File:Mcediode.lib

*15V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5352B  File:Mcediode.lib

*17V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5354B  File:Mcediode.lib

*19V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5356B  File:Mcediode.lib

*22V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5358B  File:Mcediode.lib

*25V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5360B  File:Mcediode.lib

*28V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5362B  File:Mcediode.lib

*33V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5364B  File:Mcediode.lib

*39V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5366B  File:Mcediode.lib

*47V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5368B  File:Mcediode.lib

*56V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5370B  File:Mcediode.lib

*62V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5372B  File:Mcediode.lib

*75V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5374B  File:Mcediode.lib

*87V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5376B  File:Mcediode.lib

*100V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5378B  File:Mcediode.lib

*120V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5380B  File:Mcediode.lib

*140V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5382B  File:Mcediode.lib

*160V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5384B  File:Mcediode.lib

*180V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5386B  File:Mcediode.lib

*200V 1000mW Si pkg:DIODE0.7 A,K
.PARAM X1N5388B  File:Mcediode.lib

*2.4V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C2V4 File:Mcediode.lib

*2.7V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C2V7 File:Mcediode.lib

*3V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C3V0 File:Mcediode.lib

*3.3V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C3V3 File:Mcediode.lib

*3.6V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C3V6 File:Mcediode.lib

*3.9V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C3V9 File:Mcediode.lib

*4.3V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C4V3 File:Mcediode.lib

*4.7V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C4V7 File:Mcediode.lib

*5.1V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C5V1 File:Mcediode.lib

*5.6V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C5V6 File:Mcediode.lib

*6.2V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C6V2 File:Mcediode.lib

*6.8V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C6V8 File:Mcediode.lib

*7.5V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C7V5 File:Mcediode.lib

*8.2V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C8V2 File:Mcediode.lib

*9.1V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C9V1 File:Mcediode.lib

*10V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C10 File:Mcediode.lib

*11V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C11 File:Mcediode.lib

*12V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C12 File:Mcediode.lib

*13V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C13 File:Mcediode.lib

*15V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C15 File:Mcediode.lib

*16V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C16 File:Mcediode.lib

*18V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C18 File:Mcediode.lib

*20V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C20 File:Mcediode.lib

*22V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C22 File:Mcediode.lib

*24V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C24 File:Mcediode.lib

*27V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C27 File:Mcediode.lib

*30V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C30 File:Mcediode.lib

*33V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C33 File:Mcediode.lib

*36V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C36 File:Mcediode.lib

*39V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C39 File:Mcediode.lib

*43V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C43 File:Mcediode.lib

*47V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C47 File:Mcediode.lib

*51V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C51 File:Mcediode.lib

*56V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C56 File:Mcediode.lib

*62V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C62 File:Mcediode.lib

*68V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C68 File:Mcediode.lib

*75V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX55C75 File:Mcediode.lib

*2.4V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM X1N5221B  File:Mcediode.lib

*2.5V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM X1N52222B File:Mcediode.lib

*2.7V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM X1N5223B  File:Mcediode.lib

*2.8V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM X1N5224B  File:Mcediode.lib

*3V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM X1N5225B  File:Mcediode.lib

*56V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM X1N5263B  File:Mcediode.lib

*60V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM X1N5264B  File:Mcediode.lib

*62V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM X1N5265B  File:Mcediode.lib

*68V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM X1N5266B  File:Mcediode.lib

*75V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM X1N5267B  File:Mcediode.lib

*2.7V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C2V7 File:Mcediode.lib

*3V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C3V0 File:Mcediode.lib

*3.3V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C3V3 File:Mcediode.lib

*3.6V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C3V6 File:Mcediode.lib

*3.9V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C3V9 File:Mcediode.lib

*4.3V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C4V3 File:Mcediode.lib

*4.7V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C4V7 File:Mcediode.lib

*5.1V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C5V1 File:Mcediode.lib

*5.6V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C5V6 File:Mcediode.lib

*6.2V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C6V2 File:Mcediode.lib

*6.8V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C6V8 File:Mcediode.lib

*7.5V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C7V5 File:Mcediode.lib

*8.2V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C8V2 File:Mcediode.lib

*9.1V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C9V1 File:Mcediode.lib

*10V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C10 File:Mcediode.lib

*11V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C11 File:Mcediode.lib

*12V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C12 File:Mcediode.lib

*13V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C13 File:Mcediode.lib

*15V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C15 File:Mcediode.lib

*16V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C16 File:Mcediode.lib

*18V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C18 File:Mcediode.lib

*20V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C20 File:Mcediode.lib

*22V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C22 File:Mcediode.lib

*24V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C24 File:Mcediode.lib

*27V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C27 File:Mcediode.lib

*30V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C30 File:Mcediode.lib

*33V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C33 File:Mcediode.lib

*36V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C36 File:Mcediode.lib

*39V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C39 File:Mcediode.lib

*43V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C43 File:Mcediode.lib

*47V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C47 File:Mcediode.lib

*51V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C51 File:Mcediode.lib

*56V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C56 File:Mcediode.lib

*62V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C62 File:Mcediode.lib

*68V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C68 File:Mcediode.lib

*75V 1300mW Si Zener pkg:DIODE0.4 A,K
.PARAM XBZX85C75 File:Mcediode.lib

*10V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C10 File:Mcediode.lib

*11V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C11 File:Mcediode.lib

*12V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C12 File:Mcediode.lib

*13V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C13 File:Mcediode.lib

*15V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C15 File:Mcediode.lib

*16V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C16 File:Mcediode.lib

*18V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C18 File:Mcediode.lib

*20V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C20 File:Mcediode.lib

*22V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C22 File:Mcediode.lib

*24V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C24 File:Mcediode.lib

*27V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C27 File:Mcediode.lib

*30V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C30 File:Mcediode.lib

*33V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C33 File:Mcediode.lib

*36V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C36 File:Mcediode.lib

*39V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C39 File:Mcediode.lib

*43V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C43 File:Mcediode.lib

*47V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C47 File:Mcediode.lib

*51V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C51 File:Mcediode.lib

*56V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C56 File:Mcediode.lib

*62V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C62 File:Mcediode.lib

*68V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C68 File:Mcediode.lib

*75V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C75 File:Mcediode.lib

*82V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C82 File:Mcediode.lib

*91V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C91 File:Mcediode.lib

*100V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C100 File:Mcediode.lib

*110V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C110 File:Mcediode.lib

*120V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C120 File:Mcediode.lib

*130V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C130 File:Mcediode.lib

*150V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C150 File:Mcediode.lib

*160V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C160 File:Mcediode.lib

*180V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C180 File:Mcediode.lib

*200V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C200 File:Mcediode.lib

*220V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C220 File:Mcediode.lib

*240V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C240 File:Mcediode.lib

*270V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG03C270 File:Mcediode.lib

*3.3V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C3V3 File:Mcediode.lib

*3.6V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C3V6 File:Mcediode.lib

*3.9V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C3V9 File:Mcediode.lib

*4.3V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C4V3 File:Mcediode.lib

*4.7V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C4V7 File:Mcediode.lib

*5.1V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C5V1 File:Mcediode.lib

*5.6V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C5V6 File:Mcediode.lib

*6.2V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C6V2 File:Mcediode.lib

*6.8V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C6V8 File:Mcediode.lib

*7.5V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C7V5 File:Mcediode.lib

*8.2V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C8V2 File:Mcediode.lib

*9.1V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C9V1 File:Mcediode.lib

*10V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C10 File:Mcediode.lib

*11V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C11 File:Mcediode.lib

*12V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C12 File:Mcediode.lib

*13V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C13 File:Mcediode.lib

*15V 3W Si Zener pkg:DO214 1,2
.PARAM XBZG05C15 File:Mcediode.lib

*2.7V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C2V7 File:Mcediode.lib

*3V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C3  File:Mcediode.lib

*3.3V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C3V3 File:Mcediode.lib

*3.6V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C3V6 File:Mcediode.lib

*3.9V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C3V9 File:Mcediode.lib

*4.3V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C4V3 File:Mcediode.lib

*4.7V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C4V7 File:Mcediode.lib

*5.1V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C5V1 File:Mcediode.lib

*5.6V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C5V6 File:Mcediode.lib

*6.2V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C6V2 File:Mcediode.lib

*6.8V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C6V8 File:Mcediode.lib

*7.5V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C7V5 File:Mcediode.lib

*8.2V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C8V2 File:Mcediode.lib

*9.1V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C9V1 File:Mcediode.lib

*10V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C10 File:Mcediode.lib

*11V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C11 File:Mcediode.lib

*12V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C12 File:Mcediode.lib

*13V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C13 File:Mcediode.lib

*15V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C15 File:Mcediode.lib

*16V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C16 File:Mcediode.lib

*18V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C18 File:Mcediode.lib

*20V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C20 File:Mcediode.lib

*22V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C22 File:Mcediode.lib

*24V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C24 File:Mcediode.lib

*27V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C27 File:Mcediode.lib

*30V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C30 File:Mcediode.lib

*33V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C33 File:Mcediode.lib

*36V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C36 File:Mcediode.lib

*39V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C39 File:Mcediode.lib

*43V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C43 File:Mcediode.lib

*47V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C47 File:Mcediode.lib

*51V 410mW Si Zener pkg:60A2 1,2
.PARAM XBZT52C51 File:Mcediode.lib

*3.3V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5226B  File:Mcediode.lib

*3.6V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5227B  File:Mcediode.lib

*3.9V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5228B  File:Mcediode.lib

*4.3V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5229B  File:Mcediode.lib

*4.7V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5230B   File:Mcediode.lib

*5.1V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5231B  File:Mcediode.lib

*5.6V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5232B  File:Mcediode.lib

*6V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5233B  File:Mcediode.lib

*6.2V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5234B  File:Mcediode.lib

*6.8V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5235B  File:Mcediode.lib

*7.5V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5236B  File:Mcediode.lib

*8.2V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5237B  File:Mcediode.lib

*8.7V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5238B  File:Mcediode.lib

*9.1V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5239B  File:Mcediode.lib

*10V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5240B  File:Mcediode.lib

*11V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5241B  File:Mcediode.lib

*12V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5242B  File:Mcediode.lib

*13V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5243B  File:Mcediode.lib

*14V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5244B  File:Mcediode.lib

*15V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5245B  File:Mcediode.lib

*16V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5246B  File:Mcediode.lib

*17V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5247B  File:Mcediode.lib

*18V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5248B  File:Mcediode.lib

*19V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5249B  File:Mcediode.lib

*20V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5250B  File:Mcediode.lib

*22V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5251B  File:Mcediode.lib

*24V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5252B  File:Mcediode.lib

*25V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5253B  File:Mcediode.lib

*27V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5254B  File:Mcediode.lib

*28V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5255B  File:Mcediode.lib

*30V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5256B  File:Mcediode.lib

*33V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5257B  File:Mcediode.lib

*36V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5258B  File:Mcediode.lib

*39V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5259B  File:Mcediode.lib

*43V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5260B  File:Mcediode.lib

*47V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5261B  File:Mcediode.lib

*51V 500mW Si Zener pkg:DL-35 1,2
.PARAM XDL5262B  File:Mcediode.lib

*3.9V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4730A  File:Mcediode.lib

*4.3V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4731A  File:Mcediode.lib

*4.7V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4732A  File:Mcediode.lib

*5.1V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4733A  File:Mcediode.lib

*5.6V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4734A  File:Mcediode.lib

*6.2V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4735A  File:Mcediode.lib

*6.8V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4736A  File:Mcediode.lib

*7.5V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4737A  File:Mcediode.lib

*8.2V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4738A  File:Mcediode.lib

*9.1V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4739A  File:Mcediode.lib

*10V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4740A  File:Mcediode.lib

*11V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4741A  File:Mcediode.lib

*12V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4742A  File:Mcediode.lib

*13V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4743A  File:Mcediode.lib

*15V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4744A  File:Mcediode.lib

*16V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4745A  File:Mcediode.lib

*18V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4746A  File:Mcediode.lib

*20V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4747A  File:Mcediode.lib

*22V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4748A  File:Mcediode.lib

*24V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4749A  File:Mcediode.lib

*27V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4750A  File:Mcediode.lib

*30V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4751A  File:Mcediode.lib

*33V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4752A  File:Mcediode.lib

*36V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4753A  File:Mcediode.lib

*39V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4754A  File:Mcediode.lib

*43V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4755A  File:Mcediode.lib

*47V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4756A  File:Mcediode.lib

*51V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4757A  File:Mcediode.lib

*56V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4758A  File:Mcediode.lib

*62V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4759A  File:Mcediode.lib

*68V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4760A  File:Mcediode.lib

*75V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4761A  File:Mcediode.lib

*82V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4762A  File:Mcediode.lib

*91V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4763A  File:Mcediode.lib

*100V 1W Si Zener pkg:DL-41 1,2
.PARAM XDL4764A  File:Mcediode.lib

*100V 1W Si Zener pkg:DL-41 1,2
.PARAM XZMU100   File:Mcediode.lib

*120V 1W Si Zener pkg:DL-41 1,2
.PARAM XZMU120   File:Mcediode.lib

*150V 1W Si Zener pkg:DL-41 1,2
.PARAM XZMU150   File:Mcediode.lib

*180V 1W Si Zener pkg:DL-41 1,2
.PARAM XZMU180   File:Mcediode.lib

*1V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY1     File:Mcediode.lib

*3.9V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY3_9   File:Mcediode.lib

*4.3V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY4_3   File:Mcediode.lib

*4.7V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY4_7   File:Mcediode.lib

*5.1V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY5_1   File:Mcediode.lib

*5.6V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY5_6   File:Mcediode.lib

*6.2V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY6_2   File:Mcediode.lib

*6.8V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY6_8   File:Mcediode.lib

*7.5V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY7_5   File:Mcediode.lib

*8.2V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY8_2   File:Mcediode.lib

*9.1V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY9_1   File:Mcediode.lib

*10V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY10    File:Mcediode.lib

*11V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY11    File:Mcediode.lib

*12V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY12    File:Mcediode.lib

*13V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY13    File:Mcediode.lib

*15V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY15    File:Mcediode.lib

*16V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY16    File:Mcediode.lib

*18V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY18    File:Mcediode.lib

*20V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY20    File:Mcediode.lib

*22V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY22    File:Mcediode.lib

*24V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY24    File:Mcediode.lib

*27V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY27    File:Mcediode.lib

*30V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY30    File:Mcediode.lib

*33V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY33    File:Mcediode.lib

*36V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY36    File:Mcediode.lib

*39V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY39    File:Mcediode.lib

*43V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY43    File:Mcediode.lib

*47V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY47    File:Mcediode.lib

*51V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY51    File:Mcediode.lib

*56V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY56    File:Mcediode.lib

*62V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY62    File:Mcediode.lib

*68V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY68    File:Mcediode.lib

*75V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY75    File:Mcediode.lib

*82V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY82    File:Mcediode.lib

*91V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY91    File:Mcediode.lib

*100V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPY100   File:Mcediode.lib

*100V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPU100   File:Mcediode.lib

*120V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPU120   File:Mcediode.lib

*150V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPU150   File:Mcediode.lib

*180V 1.3W Si Zener pkg:DIODE0.7 A,K
.PARAM XZPU180   File:Mcediode.lib

*1V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY1      File:Mcediode.lib

*3.9V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY3_9    File:Mcediode.lib

*4.3V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY4_3    File:Mcediode.lib

*4.7V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY4_7    File:Mcediode.lib

*5.1V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY5_1    File:Mcediode.lib

*5.6V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY5_6    File:Mcediode.lib

*6.2V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY6_2    File:Mcediode.lib

*6.8V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY6_8    File:Mcediode.lib

*7.5V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY7_5    File:Mcediode.lib

*8.2V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY8_2    File:Mcediode.lib

*9.1V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY9_1    File:Mcediode.lib

*10V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY10     File:Mcediode.lib

*11V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY11     File:Mcediode.lib

*12V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY12     File:Mcediode.lib

*13V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY13     File:Mcediode.lib

*15V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY15     File:Mcediode.lib

*16V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY16     File:Mcediode.lib

*18V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY18     File:Mcediode.lib

*20V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY20     File:Mcediode.lib

*22V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY22     File:Mcediode.lib

*24V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY24     File:Mcediode.lib

*27V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY27     File:Mcediode.lib

*30V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY30     File:Mcediode.lib

*33V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY33     File:Mcediode.lib

*36V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY36     File:Mcediode.lib

*39V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY39     File:Mcediode.lib

*43V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY43     File:Mcediode.lib

*51V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY51     File:Mcediode.lib

*56V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY56     File:Mcediode.lib

*62V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY62     File:Mcediode.lib

*68V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY68     File:Mcediode.lib

*75V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY75     File:Mcediode.lib

*82V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY82     File:Mcediode.lib

*91V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY91     File:Mcediode.lib

*100V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY100    File:Mcediode.lib

*110V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY110    File:Mcediode.lib

*120V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY120    File:Mcediode.lib

*130V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY130    File:Mcediode.lib

*150V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY150    File:Mcediode.lib

*160V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY160    File:Mcediode.lib

*180V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY180    File:Mcediode.lib

*200V 2W Si Zener pkg:DIODE0.7 A,K
.PARAM XZY200    File:Mcediode.lib
